### ISSUE TITLE
"Unlock" doesn't work on desktop app

### ISSUE THREAD

**Issue by nofxy** [bitwarden/clients#10112]
### Steps To Reproduce

1. Open the desktop app. 
2. Type in master password. 
3. Click eye icon to verify password is correct.
4. Click "Unlock"

### Expected Result

My vault unlocks. 

### Actual Result

The "Unlock" button visually appears to get stuck clicked, after multiple seconds it "unclicks". The vault is not unlocked and I'm not visually presented with any feedback of what just happened. 

### Additional Context

This is logged in `app.log` when I click the "Unlock" button on the desktop app:

```
[2024-07-14 19:07:09.667] [info]  Checking for update
[2024-07-14 19:07:10.047] [info]  Update for version 2024.6.4 is not available (latest version: 2024.6.4, downgrade is disallowed).
[2024-07-14 19:08:25.486] [error] mac failed.
[2024-07-14 19:08:25.490] [error] Unhandled error in angular Error: Uncaught (in promise): Error: No key provided. Lock the user to clear the key
Error: No key provided. Lock the user to clear the key
    at useClass.<anonymous> (file:///C:/Program%20Files/Bitwarden/resources/app.asar/app/main.js:1:272099)
    at Generator.next (<anonymous>)
    at file:///C:/Program%20Files/Bitwarden/resources/app.asar/app/main.js:1:271466
    at new N (file:///C:/Program%20Files/Bitwarden/resources/app.asar/app/vendor.js:2:828481)
    at Lh (file:///C:/Program%20Files/Bitwarden/resources/app.asar/app/main.js:1:271211)
    at useClass.setUserKey (file:///C:/Program%20Files/Bitwarden/resources/app.asar/app/main.js:1:272047)
    at pO.<anonymous> (file:///C:/Program%20Files/Bitwarden/resources/app.asar/app/main.js:1:1024508)
    at Generator.next (<anonymous>)
    at file:///C:/Program%20Files/Bitwarden/resources/app.asar/app/main.js:1:1019653
    at new N (file:///C:/Program%20Files/Bitwarden/resources/app.asar/app/vendor.js:2:828481)
```

### Operating System

Windows

### Operating System Version

Window 10 22H2 (OS Build 19045.4651)

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2024.6.4; Shell 29.4.2; Renderer 122.0.6261.156; Node 20.9.0; Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration - as this can involve sensitive communication, it's best to contact the support team directly to work on this issue.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/).

The issue here will be closed.

Thanks!
