### ISSUE TITLE
CLI randomly fails to find organization or create collection/item

### ISSUE THREAD

**Issue by Saeden** [bitwarden/clients#10287]
### Steps To Reproduce

1. Run the following script
```bash
#!/bin/bash

set -e
function create_secret {
  secret_name=$1
  username=$2
  password=$3
  uris=$4
  secret_desc=$5

  cat $COMMON_DIR/templates/item_template.json                              |\
    jq --arg collection_id "$collection_id" '.collectionIds=$collection_id' |\
    jq --arg secret_name "$secret_name"     '.name=$secret_name'            |\
    jq --arg username "$username"           '.login.username=$username'     |\
    jq --arg password "$password"           '.login.password=$password'     |\
    jq --arg uris "$uris"                   '.login.uris=[$uris]'           |\
    bw encode                                                               |\
    bw create item --organizationid $ORG_ID
}
# Do all the logging in 
bw login --apikey
export BW_SESSION=$(cat bitwarden.json | jq -r '.bitwarden.master_pass' | bw unlock --raw)
ORG_ID="********-****-****-****-************"
sleep 3
set -x

collection_name="DevOps + CS/$PROJECT_NAME"
# Check if the collection already exists if so exit early
collection_id=$(bw list org-collections --organizationid $ORG_ID | jq -r --arg collection_name "$collection_name" '.[] | select(.name==$collection_name) | .id')
if [[ "$collection_id" != "" ]]; then
  bw logout
  exit 0
fi
# Else, create the collection
{ 
  collection_id=$(cat $COMMON_DIR/templates/collection_template.json | jq --arg collection_name "$collection_name" '.name=$collection_name' | bw encode | bw create org-collection --organizationid $ORG_ID | jq -r '.id')
  # And create all the secrets
  create_secret "Login 1" "" "password1" "uri1" "desc1"
  create_secret "Login 2" "username2" "password2" "uri2" "desc2"
  create_secret "Login 3" "username3" "password3" "uri3" "desc3"
} || {
  bw logout
}

bw logout
```

Good to note that all vars in CAPITALS are env vars that are set before the script is run, things like BW_CLIENTID, BW_CLIENTSECRET. And also good to note that I have obfuscated some IDs etc without changing the base functionality of the script.

### Expected Result

Creating/listing a collection and creating items in the collection

### Actual Result

Most times (4 out 5 times) nothing goes wrong, but sometimes randomly an error is thrown: "Organization not found" 
```
Error: Cannot encrypt cipher for organization. No key.
    at CipherService.<anonymous> (/snapshot/clients/apps/cli/build/bw.js:43267:31)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/clients/apps/cli/build/bw.js:43124:58)

Node.js v20.11.1
```
+ collection_name='DevOps/dev'
++ bw list org-collections --organizationid ********-****-****-************
++ jq -r --arg collection_name '$collection_name' '.[] | select(.name==$collection_name) | .id'
Organization not found.
+ collection_id=
```

### Screenshots or Videos

_No response_

### Additional Context

_No response_

### Operating System

Linux

### Operating System Version

Fedora 40

### Shell

Bash

### Build Version

2024.6.0 

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by closebot-bw** [comment]
⚠️ **Stale Issue Notice**

This issue has been automatically marked as stale due to inactivity. It will be closed in **2 weeks** (October 15, 2025) if no further activity occurs.

If this issue is still relevant and you would like to keep it open, please:
- Comment on this issue to show continued interest
- Provide any additional information or updates
- Confirm that the issue still exists in the latest version

Thank you for your contribution to this project! 🙏

**Comment by closebot-bw** [comment]
🔒 **Issue Closed Due to Inactivity**

This issue has been automatically closed due to lack of activity for an extended period. We periodically review and close inactive issues to help maintain our issue tracker and focus on current priorities.

**If this issue is still relevant:**
- Please create a new issue with updated information
- Include steps to reproduce the problem if it's a bug report
- Mention if this issue still occurs in the latest version

Thank you for your contribution to this project. Your feedback helps us improve! 🙏
