### ISSUE TITLE
Unknown condition caused data.json to be truncated, results in appimage not displaying the UI

### ISSUE THREAD

**Issue by xnm3YQNfEx** [bitwarden/clients#11030]
### Steps To Reproduce

No known steps to replicate. When condition is set, the issue is replicated with 100% occurrence rate.
When condition occurs, the steps to replicate are to simply try to run the appimage.

### Expected Result

Bitwarden UI is displayed,  and ready for user to provide password information

### Actual Result

UI is never displayed.
Checking output of `ps -e | grep bitwarden` will display the process is running
Checking the logs from <userprofile>/.config/Bitwarden/app.log shows an error repeated over and over. See "Additional Context" for a more complete log snippet from when this issue first occurred

Error repeated in the app.log is:
[2024-09-09 21:05:47.474] [error] Unhandled error in angular Error: Uncaught (in promise): Error: Error invoking remote method 'storageService': SyntaxError: Unterminated string in JSON at position 110592 (line 2764 column 66)
Error: Error invoking remote method 'storageService': SyntaxError: Unterminated string in JSON at position 110592 (line 2764 column 66)

Inspecting the data.json file within the <userprofile>/.config/Bitwarden/ directory shows that the data.json file is truncated for some reason. The file contains an incomplete json data structure, and ends in the middle of an encrypted password string for one of the entries. No trailing quote, no further json curly brackets.

### Additional Context

```
[2024-09-08 14:15:11.972] [info]  Staging percentage: 1, percentage: 0.3712648878272774, user id: 3c261580-fef1-551d-a0fd-5bfa5f0b3737
[2024-09-08 14:15:11.972] [info]  Found version 2024.8.2 (url: Bitwarden-2024.8.2-x86_64.AppImage, Bitwarden-2024.8.2-amd64.deb, Bitwarden-2024.8.2-amd64.deb, Bitwarden-2024.8.2-amd64.deb, Bitwarden-2024.8.2-x86_64.rpm, Bitwarden-2024.8.2-x86_64.rpm, Bitwarden-2024.8.2-x86_64.rpm)
[2024-09-08 14:15:11.973] [info]  Downloading update from Bitwarden-2024.8.2-x86_64.AppImage, Bitwarden-2024.8.2-amd64.deb, Bitwarden-2024.8.2-amd64.deb, Bitwarden-2024.8.2-amd64.deb, Bitwarden-2024.8.2-x86_64.rpm, Bitwarden-2024.8.2-x86_64.rpm, Bitwarden-2024.8.2-x86_64.rpm
[2024-09-08 14:15:11.975] [info]  Cached update sha512 checksum doesn't match the latest available update. New update must be downloaded. Cached: LCiF3wBX72ossB5rN9weA+kOSVkYz/i2PJG053M1SltB5wOe5x4UHn1JLVH5ccqOo+NGMQwEvQpi6slvWCWhnw==, expected: JgZsappm9fqoN/W/ysgVKCPmeN74CyvSOoeRHocAqBVvF8wzRD8Zxyu59+FG0oytNKiGtmrRZg+o98yLYtxjdw==. Directory for cached update will be cleaned
[2024-09-08 14:15:12.179] [info]  File has 462 changed blocks
[2024-09-08 14:15:12.195] [info]  Full: 116,467.51 KB, To download: 9,355.46 KB (8%)
[2024-09-08 14:15:12.215] [error] Cannot download differentially, fallback to full download: HttpError: 501 
Headers: {
  "accept-ranges": "bytes",
  "content-length": "461",
  "content-type": "text/html; charset=utf-8",
  "date": "Sun, 08 Sep 2024 18:15:12 GMT",
  "retry-after": "0",
  "server": "Varnish",
  "strict-transport-security": "max-age=31536000",
  "via": "1.1 varnish",
  "x-cache": "MISS",
  "x-cache-hits": "0",
  "x-content-type-options": "nosniff",
  "x-served-by": "cache-yyz4560-YYZ",
  "x-timer": "S1725819312.198403,VS0,VE0"
}
    at createHttpError (/tmp/.mount_BitwarTd575O/resources/app.asar/main.js:13585:12)
    at checkIsRangesSupported (/tmp/.mount_BitwarTd575O/resources/app.asar/main.js:23184:59)
    at ClientRequest.<anonymous> (/tmp/.mount_BitwarTd575O/resources/app.asar/main.js:23159:14)
    at ClientRequest.emit (node:events:519:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:115224)
    at SimpleURLLoaderWrapper.emit (node:events:519:28)
[2024-09-08 14:15:13.436] [info]  Starting decryption using multithreading
[2024-09-08 14:15:13.572] [info]  Finished search indexing
[2024-09-08 14:15:24.309] [info]  New version 2024.8.2 has been downloaded to /home/user/.cache/bitwarden-updater/pending/Bitwarden-2024.8.2-x86_64.AppImage
[2024-09-09 21:05:16.295] [error] Error: Error invoking remote method 'storageService': SyntaxError: Unterminated string in JSON at position 110592 (line 2764 column 66)
[2024-09-09 21:05:17.471] [error] Unhandled error in angular Error: Uncaught (in promise): Error: Error invoking remote method 'storageService': SyntaxError: Unterminated string in JSON at position 110592 (line 2764 column 66)
Error: Error invoking remote method 'storageService': SyntaxError: Unterminated string in JSON at position 110592 (line 2764 column 66)
[2024-09-09 21:05:27.470] [error] Unhandled error in angular Error: Uncaught (in promise): Error: Error invoking remote method 'storageService': SyntaxError: Unterminated string in JSON at position 110592 (line 2764 column 66)
Error: Error invoking remote method 'storageService': SyntaxError: Unterminated string in JSON at position 110592 (line 2764 column 66)
[2024-09-09 21:05:37.474] [error] Unhandled error in angular Error: Uncaught (in promise): Error: Error invoking remote method 'storageService': SyntaxError: Unterminated string in JSON at position 110592 (line 2764 column 66)
Error: Error invoking remote method 'storageService': SyntaxError: Unterminated string in JSON at position 110592 (line 2764 column 66)
[2024-09-09 21:05:47.474] [error] Unhandled error in angular Error: Uncaught (in promise): Error: Error invoking remote method 'storageService': SyntaxError: Unterminated string in JSON at position 110592 (line 2764 column 66)
Error: Error invoking remote method 'storageService': SyntaxError: Unterminated string in JSON at position 110592 (line 2764 column 66)
```

### Operating System

Linux

### Operating System Version

Linux Mint 21.2 Cinnamon 64-bit

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.8.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by xnm3YQNfEx** [comment]
Workaround to restore functionality was to rename the <userdir>/.config/Bitwarden directory.
I first use ps -e | grep bitwarden to get the process ID's for all bitwarden processes
Killed all running processes just in case 

Afterwards, renaming the directory to retain a backup just in case, and then re-launching bitwarden resulted in the app working as expected.

**Comment by Krychaz** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by xnm3YQNfEx** [comment]
Hey! I unfortunately don't have much more. I believe this issue occurred while updating to 2024.8.2 version of the appimage, and there is another, similar (Linux, JSON being truncated after 2024.8.2 update) report here:

https://github.com/bitwarden/clients/issues/11044

The behaviour in the failure state (app not opening at all) is not ideal. I think there should be better error/exception handling around cases like this that fail "gracefully". Prompting the user with an error dialog that the offline cache is corrupted when they run the program and the json fails to parse with options for remove/rename the corrupted data file.

**Comment by closebot-bw** [comment]
⚠️ **Stale Issue Notice**

This issue has been automatically marked as stale due to inactivity. It will be closed in **2 weeks** (October 15, 2025) if no further activity occurs.

If this issue is still relevant and you would like to keep it open, please:
- Comment on this issue to show continued interest
- Provide any additional information or updates
- Confirm that the issue still exists in the latest version

Thank you for your contribution to this project! 🙏

**Comment by closebot-bw** [comment]
🔒 **Issue Closed Due to Inactivity**

This issue has been automatically closed due to lack of activity for an extended period. We periodically review and close inactive issues to help maintain our issue tracker and focus on current priorities.

**If this issue is still relevant:**
- Please create a new issue with updated information
- Include steps to reproduce the problem if it's a bug report
- Mention if this issue still occurs in the latest version

Thank you for your contribution to this project. Your feedback helps us improve! 🙏

**Comment by nh2** [comment]
## Fixing Bitwarden not corrupting its state when the disk gets full

I found an underlying cause of Bitwarden's `data.json` being corrupted:

The [`atomically`](https://github.com/fabiospampinato/atomically) library that bitwarden uses doesn't write files atomically in all cases, notably it doesn't handle short writes correctly. I made a PR for it:

* https://github.com/fabiospampinato/atomically/pull/18

Some further ideas:

* Maybe some of the [$100M VC money Bitwarden raised](https://techcrunch.com/2022/09/06/open-source-password-manager-bitwarden-raises-100m/) should go in checking that it can ... write files to disk correctly.
* Or run an LLM on Bitwarden's dependencies, or sponsor those to do it. The prompt `Check the source code for bugs. Only list severe ones` immediately pointed out this bug (and also listed lots that I didn't investigate).

As a paying Bitwarden customer, I'd actually appreciate that.

---

This of course does not fix the GUI problem that this issue is actually about and that the closebot so helpfully closed -- of course it still exists; when `data.json` _is_ corrupted, Bitwarden still runs in the background but shows no GUI, leaving the user puzzled.
