### ISSUE TITLE
Bitwarden Extension Causing issues with Website

### ISSUE THREAD

**Issue by bscmattanderson** [bitwarden/clients#11268]
### Steps To Reproduce

1. Install bitwarden extension on Microsoft Edge (Version 2024.9.1) - You do not even need to sign in
2. Go to https://gis.bigstonecounty.gov/link/wab/
3. Click on top right 4 squares to change to a new base map
4. Page does not load new base map menu.

### Expected Result

New basemap should be shown. If you remove the extension it works, if you view in private mode without extension it works. Version of browser does not matter, clean browser does not matter.

### Actual Result

No item loads, errors in dev console.

widget [widgets/OverviewMap/Widget] created.
WidgetManager.js?wab_dv=2.20:121 widget [widgets/Search/Widget] created.
WidgetManager.js?wab_dv=2.20:121 widget [widgets/AttributeTable/Widget] created.
AbsolutePositionLayoutManager.js?wab_dv=2.20:110 Load widgetOnScreen: 502.97802734375 ms
init.js:116  TypeError: Cannot read properties of null (reading 'insertBefore')
    at d.injectUrl (init.js:36:479)
    at global.avoidRequireCache.require.injectUrl (env.js:324:7)
    at Sa (init.js:33:338)
    at a (init.js:10:436)
    at init.js:20:121
    at Na (init.js:29:294)
    at ua (init.js:20:107)
    at sa (init.js:20:467)
    at G (init.js:21:132)
    at x.loadPBFReader (init.js:2801:160) "TypeError: Cannot read properties of null (reading 'insertBefore')\n    at d.injectUrl (https://js.arcgis.com/3.36/init.js:36:479)\n    at global.avoidRequireCache.require.injectUrl (https://gis.bigstonecounty.gov/link/wab/env.js:324:7)\n    at Sa (https://js.arcgis.com/3.36/init.js:33:338)\n    at a (https://js.arcgis.com/3.36/init.js:10:436)\n    at https://js.arcgis.com/3.36/init.js:20:121\n    at Na (https://js.arcgis.com/3.36/init.js:29:294)\n    at ua (https://js.arcgis.com/3.36/init.js:20:107)\n    at sa (https://js.arcgis.com/3.36/init.js:20:467)\n    at G (https://js.arcgis.com/3.36/init.js:21:132)\n    at x.loadPBFReader (https://js.arcgis.com/3.36/init.js:2801:160)"
r @ init.js:116
init.js:29  Uncaught TypeError: Cannot read properties of null (reading 'insertBefore')
    at d.injectUrl (init.js:36:479)
    at global.avoidRequireCache.require.injectUrl (env.js:324:7)
    at Sa (init.js:33:338)
    at a (init.js:10:436)
    at init.js:20:121
    at Na (init.js:29:294)
    at ua (init.js:20:107)
    at sa (init.js:20:467)
    at G (init.js:21:132)
    at Object._loadPanelClass (PanelManager.js?wab_dv=2.20:623:7)
init.js:29  Uncaught TypeError: Cannot read properties of null (reading 'insertBefore')
    at d.injectUrl (init.js:36:479)
    at global.avoidRequireCache.require.injectUrl (env.js:324:7)
    at Sa (init.js:33:338)
    at a (init.js:10:436)
    at init.js:20:121
    at Na (init.js:29:294)
    at ua (init.js:20:107)
    at sa (init.js:20:467)
    at G (init.js:21:132)
    at d (init.js:78:10)

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/236e352f-1f81-4434-ae6e-0ee8af0f52e3)

### Operating System

Windows

### Operating System Version

Windows 11 23H2

### Web Browser

Microsoft Edge

### Browser Version

129.0.2792.52

### Build Version

2024.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by bscmattanderson** [comment]
Closing, duplicate to https://github.com/bitwarden/clients/issues/11234
