### ISSUE TITLE
Can't unlock vault

### ISSUE THREAD

**Issue by olafcatsnake** [bitwarden/clients#11432]
### Steps To Reproduce

1. Open Bitwarden desktop
2. Fill in master password
3. Click 'Unlock'

### Expected Result

Vault is unlocked

### Actual Result

Vault is not unlocked, button changes color on click so at least on some level it responds.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/d9d72612-83a3-465e-948a-9abac85259aa)

### Additional Context

Typing wrong vault password returns invalid password popup, correct password does nothing.

### Operating System

Windows

### Operating System Version

23H2, 22631.4249

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2024.9.0 Shell 32.0.1 Renderer 128.0.6613.36 Node 20.16.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @olafcatsnake,

Thank you for this report. This reminds of this [report GitHub](https://github.com/bitwarden/clients/issues/11191) report which I was not able to reproduce; Are you still encountering this behaviour? If you are, could you please [get in touch with us](https://bitwarden.com/help/)? We'd like to review the desktop client's app.log file, which is located in its [installation folder](https://bitwarden.com/help/data-storage/#on-your-local-machine).

Thank you in advance,

**Comment by olafcatsnake** [comment]
Hi,

I was able to resolve this by the same way as the other guy, full log out and log in. However I can still provide the logs if needed. If I remember correctly the issue began sometime after changing KDF iterations.

Heres snapshot from the logs around the time of error:

[2024-10-06 19:47:11.125] [error] MAC comparison failed. Key or payload has changed.
[2024-10-06 19:47:11.126] [error] Unhandled error in angular Error: Uncaught (in promise): Error: No key provided. Lock the user to clear the key
Error: No key provided. Lock the user to clear the key
    at useClass.<anonymous> (file:///C:/Program%20Files/Bitwarden/resources/app.asar/app/main.js:80:142557)
    at Generator.next (<anonymous>)
    at file:///C:/Program%20Files/Bitwarden/resources/app.asar/app/main.js:80:141924
    at new N (file:///C:/Program%20Files/Bitwarden/resources/app.asar/app/vendor.js:2:823890)
    at My (file:///C:/Program%20Files/Bitwarden/resources/app.asar/app/main.js:80:141669)
    at useClass.setUserKey (file:///C:/Program%20Files/Bitwarden/resources/app.asar/app/main.js:80:142505)
    at sG.<anonymous> (file:///C:/Program%20Files/Bitwarden/resources/app.asar/app/main.js:154:282174)
    at Generator.next (<anonymous>)
    at file:///C:/Program%20Files/Bitwarden/resources/app.asar/app/main.js:154:277439
    at new N (file:///C:/Program%20Files/Bitwarden/resources/app.asar/app/vendor.js:2:823890)

**Comment by SergeantConfused** [comment]
Hi @olafcatsnake,

Thank you. I was able to reproduce this like so:
1. Log into an individual Bitwarden account via the Bitwarden desktop client.
2. Quit the Bitwarden desktop client. Please note that the [Vault Timeout Action](https://bitwarden.com/help/vault-timeout/) should be set to Lock, in this case.
3. Log into the same individual Bitwarden account via the Bitwarden [Web App](https://vault.bitwarden.com/#/login) and modify the [KDF configuration](https://bitwarden.com/help/kdf-algorithms/).
4. Launch the Bitwarden desktop client, and attempt to unlock it.

It seems that when the desktop client is not in an active state, it does not log out after the KDF configuration is modified; When this was tested whilst the Bitwarden desktop client was active in the background, it logged out of the individual Bitwarden account in question as expected.

I have flagged this to the Engineering department; Please feel free to post additional information, such as screenshots or a screen video recordings, if you wish.

Thank you again,

**Comment by dscottwarren** [comment]
@SergeantConfused - Arrived here via the now closed but related / mentioned MacOS ticket here: [11191](https://github.com/bitwarden/clients/issues/11191). Just chiming in to say in MacOS 15.0.1 on a M3 MBP I ran into the same issue -- attempted to log in via both master password and alternate device. Neither worked. 

I didn't attempt a "full logout", but uninstalling / reinstalling the app resolved it in my case.
