### ISSUE TITLE
Performance Issue with Autofill Functionality in Vite + Vue 3 Application

### ISSUE THREAD

**Issue by manuelgoi** [bitwarden/clients#12031]
### Steps To Reproduce

1. Start the application with Bitwarden extension enabled.
2. Perform drag-and-drop operations on elements within any scrollable area.
3. Observe the performance impact and frequent calls to requestIdleCallbackPolyfill() in Chrome's performance profile.

### Expected Result

The autofill functionality should not significantly impact application performance and should handle idle callbacks more efficiently.

### Actual Result

The autofill process significantly affects the application's responsiveness and performance, especially during drag-and-drop interactions within scrollable areas.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/29d65bc3-af51-4ea4-890d-7fa5ffe7dd05)

### Additional Context

I am experiencing a significant performance issue in a web application developed using Vite, Vue 3, TypeScript, and Pinia. The issue becomes evident when performing drag-and-drop operations on elements within a layer that has overflow scrolling enabled. The problem is associated with the bootstrap-legacy-autofill-overlay.js file, specifically the requestIdleCallbackPolyfill() function.

Issue Details:

Environment: Vite + Vue 3 + TypeScript + Pinia
The performance profiling tools in Chrome DevTools indicate that the requestIdleCallbackPolyfill() function is frequently triggered and consumes a significant amount of CPU time. This function is called as part of the autofill process initiated by Bitwarden, and it severely impacts the application's performance, particularly during user interactions involving scrolling and element manipulation.

The profiling data shows repeated activations of the polyfill function, particularly when inactive scroll activation tasks are triggered. It appears that the autofill functionality is interacting in a way that significantly degrades performance during these operations.

### Operating System

macOS, Linux

### Operating System Version

Macos 15.1

### Web Browser

Chrome

### Browser Version

130.0.6723.117

### Build Version

(Build oficial) (arm64)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by ejallier** [comment]
Hello, same problem for me.
My website is really slower when the extension is activated.
I have the error related to bootstrap-legacy-autofill-overlay.js

**Comment by cagonzalezcs** [comment]
@jprusik 

The performance issues described here are related to similar reports in the past for instance: https://github.com/bitwarden/clients/issues/11077

Some recent improvements in the extension have helped with this kind of concern, but it is tricky improving the performance cost of autofill. The main issue at hand is going to be the `MutationObsevers` that need to identify when changes occur in the DOM to re-capture form field data...

**Comment by manuelgoi** [comment]
Hello,

First of all, I’d like to thank you for taking the time to address my report and for the continuous improvements you’ve made to Bitwarden. I greatly appreciate all the work that goes into maintaining such an essential tool.

After reviewing your response regarding the performance issue and understanding that the autofill functionality relies on MutationObservers, I still have one main question that I’d like to ask in a humble way.

Why is the requestIdleCallbackPolyfill() being used in the latest versions of Chrome, which natively supports requestIdleCallback? My understanding is that polyfills are generally meant to be active only when their native counterpart isn’t available or supported in the current environment. Could you help clarify why the polyfill is being triggered even in modern browsers where requestIdleCallback is fully implemented?

If it’s due to specific browser inconsistencies or additional functionality provided by the polyfill, I’d love to understand more about this decision, as it seems to impact performance in my use case (drag-and-drop interactions in scrollable areas).

I hope my question doesn’t come across as critical—I’m just trying to better understand how the extension operates and how I might mitigate the performance issue on my end.

Thank you again for your time and support!

**Comment by cagonzalezcs** [comment]
@manuelgoi 

`requestCallbackPolyfill` does call `requiredIdleCallback` in browsers that support it.

https://github.com/bitwarden/clients/blob/21855595c56f72a779906d7796060f4782409d6a/apps/browser/src/autofill/utils/index.ts#L29

The method is a wrapper that fallsback to `setTimeout` in cases where the API does not exist, such as in Safari.

**Comment by Zaczero** [comment]
I am noticing the same behavior and I have additional information.

I am using a very recent chromium browser and while requiredIdleCallback is there, it calls debounce method which uses timer, completely removing benefits of requiredIdleCallback and forcing renders during web use.

I am attaching chrome profile from https://rapideditor.org where the issue is clearly present (open the editor and drag something around the map):
[Trace-20241230T095016.json.gz](https://github.com/user-attachments/files/18273257/Trace-20241230T095016.json.gz)

You can see see the mutations are fired by a timer:
![image](https://github.com/user-attachments/assets/c033a134-a924-47f7-82db-f1a476da44fa)

...which is installed during requiredIdleCallback (and not executed):
![image](https://github.com/user-attachments/assets/ef3956d3-d91b-4043-948a-ff097682ed04)

This configuration causes the heavy computation to be done in a timer callback, while idle callback only installs the timer. Ruining the responsiveness and performance of web apps.

**Comment by Zaczero** [comment]
PS. On the other side, processMutations seems to be *very* badly optimized. Around 100ms to finish on a well specd device. It is called quite frequently too:

![image](https://github.com/user-attachments/assets/54f2e9c1-01ee-4319-bef8-aab8c0258afa)

**Comment by cagonzalezcs** [comment]
@Zaczero 

> while requiredIdleCallback is there, it calls debounce method which uses timer, removing benefits of requiredIdleCallback and forcing renders during web use

Hmm... that's not entirely accurate. 

The debounce was placed there to account for multiple mutations that occur in quick succession, ensuring that the list of mutations is processed at most every "x milliseconds". 

Beyond that timeout, each mutation is then also processed within a subsequent `requestIdleCallback` call that is not debounced. 

https://github.com/bitwarden/clients/blob/21855595c56f72a779906d7796060f4782409d6a/apps/browser/src/autofill/services/collect-autofill-content.service.ts#L996

The issue with this "jank" being introduced comes down to having to be thorough in checking for ShadowDOM elements within a set of mutations. It's pretty taxing given the number of tasks that need to be done when re-assessing if a form element has been added to the page (checking for visibility of the element, position, gather attributes, etc...). That's why nested calls to `requestIdleCallback` are used to attempt to avoid processing mutations until the event loop is free to do so without affecting user experience. While some improvements could still be made to that, it is definitely much more performant at this point than was previously when the ShadowDOM fix was first introduced.

I'm no longer working at Bitwarden, but [based on recent PRs put up the by the team](https://github.com/bitwarden/clients/pull/11826), I believe some work is being done to guard against injection of these kinds of content scripts on a per domain basis. That should help with the performance concerns that are found on SPA implementations.

Beyond that, I'm positive the team at Bitwarden is aware of your concern and it's likely that any concrete suggestions or ideas for how to improve this would be appreciated.

**Comment by jprusik** [comment]
Just to add; the Autofill team is mindful of this and performance improvements we can make, but we have nothing specific we can report on just yet.

**Comment by Zaczero** [comment]
@cagonzalezcs The screenshots from the profiler I have attached illustrate that the heavy computation is done during timer event and not idle callback. Near the top of the callstack there is a label indicating what triggered the function (it's visible on the screenshots).

**Comment by cagonzalezcs** [comment]
Then maybe what needs to happen is simply a debounce that isn't wrapped by the idle callback within the top level callback of the Mutation Observer.

The debounce only acts as a means to build a list of mutated nodes and act on those nodes once within a 100ms period, rather than at the time they are inserted.

**Comment by cagonzalezcs** [comment]
@jprusik 

This might resolve the issue that @Zaczero is speaking about...

It's worth checking to ensure that Shadow DOM elements are no longer being affected... not sure if tests pass on this, doubt it.

https://github.com/bitwarden/clients/compare/main...cagonzalezcs:bitwarden-clients:patch-1

**Comment by rhoot** [comment]
Looks like the merged PR with the potential fix was reverted again?

I bumped into this while profiling why YouTube keeps locking up in my browser (Firefox/Linux), and the answer appears to be hundreds of idle callback handlers scheduled at the same time. Disabling the extension not only fixes the issue, but also makes navigating the site _significantly_ more responsive.

But I'm not sure if it's the same issue, despite having similar symptoms.

![Image](https://github.com/user-attachments/assets/96d79d21-437b-4b66-b0aa-283a29e5c4d6)

![Image](https://github.com/user-attachments/assets/0bf9fb9b-efe2-48ad-bf5d-c40c61afbdca)

**Comment by jprusik** [comment]
Yeah, the issue was closed when the linked PR was merged. I've reopened this issue since we're still looking at it.

**Comment by HaroldStruwig** [comment]
Any way for an app to interact with Bitwarden and programmatically disable the AutoFill feature?

**Comment by lissyx** [comment]
For the sake of referencing and avoiding others troubles in investigation, this reproduces also on DI.FM

**Comment by utdream** [comment]
Need to add what appears to be a "me too" to this. Having the bitwarden browser plugin active is causing the following console error:

bootstrap-legacy-autofill-overlay.js:6247 Uncaught TypeError: Cannot read properties of undefined (reading 'domQueryService')
    at checkPageContainsShadowDom (bootstrap-legacy-autofill-overlay.js:6247:14)
    at bootstrap-legacy-autofill-overlay.js:869:53

Noticed it while developing a vue/vite application. Started happening after the bitwarden browser plugin UI was updated. Errors go away when I disable just the bitwarden plugin, so that's my current solution while dev'ing this app. Thought you might want to know! Thank you! Bitwarden is awesome.

**Comment by djsmith85** [comment]
@utdream This issue you are describing is related to https://github.com/bitwarden/clients/issues/13308. Please also check out my last https://github.com/bitwarden/clients/issues/13308#issuecomment-2650118965 on the issue.

**Comment by utdream** [comment]
@djsmith85 Got it. Please accept my sincere apologies for not digging deeper and finding that thread earlier. Thank you!

**Comment by lissyx** [comment]
> For the sake of referencing and avoiding others troubles in investigation, this reproduces also on DI.FM

I am still hitting this and while autofill was disabled, I can see a few check boxes ticked for some of the features of autofill. I decided to just add `https://www.di.fm/` to the list of blocked domains and it seems I dont reproduce the issue anymore.

**Comment by lissyx** [comment]
This is still a problem, I am now noticing super slow github PR review due to this.

**Comment by jprusik** [comment]
There's a fair bit of overlap with the reports here and those we've addressed in other threads. Performance is still an ongoing effort, but we've made a fair bit of headway.

In the interest of consolidating our attentions, I'm closing this thread and would ask that you take a look at @audreyality 's work and comments over here: https://github.com/bitwarden/clients/issues/20172#issuecomment-4810472158
