### ISSUE TITLE
Ubuntu 24.04 Snap version fails to start with "Failed to initialize Wayland platform" error

### ISSUE THREAD

**Issue by untitled9074** [bitwarden/clients#12119]
### Steps To Reproduce

1. Install Ubuntu 24.04.1 LTS on a machine with NVIDIA GeForce RTX™ 2070 SUPER GPU. Probably other NVIDIA GPUs will be able to help in reproducing the bug as well
2. Launch GNOME Wayland session with `ELECTRON_OZONE_PLATFORM_HINT=wayland` and `QT_QPA_PLATFORM=wayland` env vars (last one probably has nothing to do with Bitwarden)
3. Install Bitwarden Snap packaged app
4. Remove `user_dir*` files as suggested in https://github.com/bitwarden/clients/issues/2629#issuecomment-1118960442 to stop Security Center from bugging you about access to various `~/$HOME` folders 
5. run `/snap/bin/bitwarden %U` or click the desktop icon and read the `journalctl -b | grep bitwarden` output 

### Expected Result

Bitwarden app launched and functional.

### Actual Result

```
$ /snap/bin/bitwarden %U
MESA-LOADER: failed to open nouveau (search paths /snap/bitwarden/126/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
failed to load driver: nouveau
MESA-LOADER: failed to open kms_swrast (search paths /snap/bitwarden/126/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast (search paths /snap/bitwarden/126/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
failed to load swrast driver
10:00:47.759 › State version: 68
10:00:47.763 › Migrator MinVersionMigrator (to version 3) should migrate: false - up
10:00:47.763 › Migrator RemoveEverBeenUnlockedMigrator (to version 4) should migrate: false - up
10:00:47.763 › Migrator AddKeyTypeToOrgKeysMigrator (to version 5) should migrate: false - up
10:00:47.764 › Migrator RemoveLegacyEtmKeyMigrator (to version 6) should migrate: false - up
10:00:47.765 › Migrator MoveBiometricAutoPromptToAccount (to version 7) should migrate: false - up
10:00:47.765 › Migrator MoveStateVersionMigrator (to version 8) should migrate: false - up
10:00:47.765 › Migrator MoveBrowserSettingsToGlobal (to version 9) should migrate: false - up
10:00:47.765 › Migrator EverHadUserKeyMigrator (to version 10) should migrate: false - up
10:00:47.765 › Migrator OrganizationKeyMigrator (to version 11) should migrate: false - up
10:00:47.765 › Migrator MoveEnvironmentStateToProviders (to version 12) should migrate: false - up
10:00:47.765 › Migrator ProviderKeyMigrator (to version 13) should migrate: false - up
10:00:47.766 › Migrator MoveBiometricClientKeyHalfToStateProviders (to version 14) should migrate: false - up
10:00:47.766 › Migrator FolderMigrator (to version 15) should migrate: false - up
10:00:47.766 › Migrator LastSyncMigrator (to version 16) should migrate: false - up
10:00:47.766 › Migrator EnablePasskeysMigrator (to version 17) should migrate: false - up
10:00:47.766 › Migrator AutofillSettingsKeyMigrator (to version 18) should migrate: false - up
10:00:47.766 › Migrator RequirePasswordOnStartMigrator (to version 19) should migrate: false - up
10:00:47.766 › Migrator PrivateKeyMigrator (to version 20) should migrate: false - up
10:00:47.766 › Migrator CollectionMigrator (to version 21) should migrate: false - up
10:00:47.766 › Migrator CollapsedGroupingsMigrator (to version 22) should migrate: false - up
10:00:47.766 › Migrator MoveBiometricPromptsToStateProviders (to version 23) should migrate: false - up
10:00:47.766 › Migrator SmOnboardingTasksMigrator (to version 24) should migrate: false - up
10:00:47.767 › Migrator ClearClipboardDelayMigrator (to version 25) should migrate: false - up
10:00:47.767 › Migrator RevertLastSyncMigrator (to version 26) should migrate: false - up
10:00:47.767 › Migrator BadgeSettingsMigrator (to version 27) should migrate: false - up
10:00:47.767 › Migrator MoveBiometricUnlockToStateProviders (to version 28) should migrate: false - up
10:00:47.767 › Migrator UserNotificationSettingsKeyMigrator (to version 29) should migrate: false - up
10:00:47.767 › Migrator PolicyMigrator (to version 30) should migrate: false - up
10:00:47.767 › Migrator EnableContextMenuMigrator (to version 31) should migrate: false - up
10:00:47.767 › Migrator PreferredLanguageMigrator (to version 32) should migrate: false - up
10:00:47.767 › Migrator AppIdMigrator (to version 33) should migrate: false - up
10:00:47.767 › Migrator DomainSettingsMigrator (to version 34) should migrate: false - up
10:00:47.767 › Migrator MoveThemeToStateProviderMigrator (to version 35) should migrate: false - up
10:00:47.767 › Migrator VaultSettingsKeyMigrator (to version 36) should migrate: false - up
10:00:47.768 › Migrator AvatarColorMigrator (to version 37) should migrate: false - up
10:00:47.768 › Migrator TokenServiceStateProviderMigrator (to version 38) should migrate: false - up
10:00:47.768 › Migrator MoveBillingAccountProfileMigrator (to version 39) should migrate: false - up
10:00:47.768 › Migrator OrganizationMigrator (to version 40) should migrate: false - up
10:00:47.768 › Migrator EventCollectionMigrator (to version 41) should migrate: false - up
10:00:47.768 › Migrator EnableFaviconMigrator (to version 42) should migrate: false - up
10:00:47.768 › Migrator AutoConfirmFingerPrintsMigrator (to version 43) should migrate: false - up
10:00:47.768 › Migrator UserDecryptionOptionsMigrator (to version 44) should migrate: false - up
10:00:47.768 › Migrator MergeEnvironmentState (to version 45) should migrate: false - up
10:00:47.768 › Migrator DeleteBiometricPromptCancelledData (to version 46) should migrate: false - up
10:00:47.768 › Migrator MoveDesktopSettingsMigrator (to version 47) should migrate: false - up
10:00:47.768 › Migrator MoveDdgToStateProviderMigrator (to version 48) should migrate: false - up
10:00:47.769 › Migrator AccountServerConfigMigrator (to version 49) should migrate: false - up
10:00:47.769 › Migrator KeyConnectorMigrator (to version 50) should migrate: false - up
10:00:47.769 › Migrator RememberedEmailMigrator (to version 51) should migrate: false - up
10:00:47.769 › Migrator DeleteInstalledVersion (to version 52) should migrate: false - up
10:00:47.769 › Migrator DeviceTrustServiceStateProviderMigrator (to version 53) should migrate: false - up
10:00:47.769 › Migrator SendMigrator (to version 54) should migrate: false - up
10:00:47.769 › Migrator MoveMasterKeyStateToProviderMigrator (to version 55) should migrate: false - up
10:00:47.769 › Migrator AuthRequestMigrator (to version 56) should migrate: false - up
10:00:47.769 › Migrator CipherServiceMigrator (to version 57) should migrate: false - up
10:00:47.769 › Migrator RemoveRefreshTokenMigratedFlagMigrator (to version 58) should migrate: false - up
10:00:47.769 › Migrator KdfConfigMigrator (to version 59) should migrate: false - up
10:00:47.769 › Migrator KnownAccountsMigrator (to version 60) should migrate: false - up
10:00:47.770 › Migrator PinStateMigrator (to version 61) should migrate: false - up
10:00:47.770 › Migrator VaultTimeoutSettingsServiceStateProviderMigrator (to version 62) should migrate: false - up
10:00:47.770 › Migrator PasswordOptionsMigrator (to version 63) should migrate: false - up
10:00:47.770 › Migrator GeneratorHistoryMigrator (to version 64) should migrate: false - up
10:00:47.770 › Migrator ForwarderOptionsMigrator (to version 65) should migrate: false - up
10:00:47.770 › Migrator MoveFinalDesktopSettingsMigrator (to version 66) should migrate: false - up
10:00:47.770 › Migrator RemoveUnassignedItemsBannerDismissed (to version 67) should migrate: false - up
10:00:47.770 › Migrator MoveLastSyncDate (to version 68) should migrate: false - up
[11824:1124/100047.772752:ERROR:wayland_connection.cc(198)] Failed to connect to Wayland display: No such file or directory (2)
[11824:1124/100047.772787:ERROR:ozone_platform_wayland.cc(264)] Failed to initialize Wayland platform
[11824:1124/100047.772792:ERROR:env.cc(258)] The platform failed to initialize.  Exiting.
Segmentation fault (core dumped)
```

### Operating System

Linux

### Operating System Version

Ubuntu 24.04.1 LTS (Linux hws 6.8.0-49-generic #49-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov  4 02:06:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux)

### Installation method

Snap

### Build Version

2024.11.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by mtb-xt** [comment]
We're also affected by this

**Comment by ripper81** [comment]
I am also affected by this bug. I am on Kubuntu 24.10 right now. The app worked flawless beforehand. In the terminal i get the following error message:

A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unterminated string in JSON at position 94208 (line 2326 column 17)
    at JSON.parse (<anonymous>)
    at Conf._deserialize (/snap/bitwarden/133/resources/app.asar/main.js:10101:43)
    at get store (/snap/bitwarden/133/resources/app.asar/main.js:10312:43)
    at new Conf (/snap/bitwarden/133/resources/app.asar/main.js:10165:32)
    at new ElectronStore (/snap/bitwarden/133/resources/app.asar/main.js:15043:3)
    at new ElectronStorageService (/snap/bitwarden/133/resources/app.asar/main.js:88774:22)
    at new Main (/snap/bitwarden/133/resources/app.asar/main.js:89517:31)
    at 83243 (/snap/bitwarden/133/resources/app.asar/main.js:75147:18)
    at __webpack_require__ (/snap/bitwarden/133/resources/app.asar/main.js:92440:42)
    at /snap/bitwarden/133/resources/app.asar/main.js:92604:37

(bitwarden-app:7606): Gtk-WARNING **: 14:58:43.052: Theme parsing error: gtk.css:3536:25: 'font-feature-settings' is not a valid property name
Gtk-Message: 14:58:43.063: Failed to load module "colorreload-gtk-module"
Gtk-Message: 14:58:43.063: Failed to load module "window-decorations-gtk-module"
[7606:0127/145843.103681:ERROR:object_proxy.cc(576)] Failed to call method: org.kde.KWallet.isEnabled: object_path= /modules/kwalletd6: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.116" (uid=1000 pid=7606 comm="/snap/bitwarden/133/bitwarden-app --no-sandbox" label="snap.bitwarden.bitwarden (enforce)") interface="org.kde.KWallet" member="isEnabled" error name="(unset)" requested_reply="0" destination="org.kde.kwalletd6" (uid=1000 pid=2927 comm="/usr/bin/kwalletd6 --pam-login 13 14" label="unconfined")
[7606:0127/145843.103695:ERROR:kwallet_dbus.cc(117)] Error contacting kwalletd6 (isEnabled)
[7606:0127/145843.104077:ERROR:object_proxy.cc(576)] Failed to call method: org.kde.KLauncher.start_service_by_desktop_name: object_path= /KLauncher: org.freedesktop.DBus.Error.ServiceUnknown: The name org.kde.klauncher was not provided by any .service files
[7606:0127/145843.104088:ERROR:kwallet_dbus.cc(86)] Error contacting klauncher to start kwalletd6
[7606:0127/145843.104191:ERROR:object_proxy.cc(576)] Failed to call method: org.kde.KWallet.close: object_path= /modules/kwalletd6: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.116" (uid=1000 pid=7606 comm="/snap/bitwarden/133/bitwarden-app --no-sandbox" label="snap.bitwarden.bitwarden (enforce)") interface="org.kde.KWallet" member="close" error name="(unset)" requested_reply="0" destination="org.kde.kwalletd6" (uid=1000 pid=2927 comm="/usr/bin/kwalletd6 --pam-login 13 14" label="unconfined")
[7606:0127/145843.104200:ERROR:kwallet_dbus.cc(412)] Error contacting kwalletd6 (close)
libGL error: MESA-LOADER: failed to open radeonsi (search paths /snap/bitwarden/133/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast (search paths /snap/bitwarden/133/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: swrast
[7646:0127/145843.111791:ERROR:angle_platform_impl.cc(44)] Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[7646:0127/145843.111883:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[7646:0127/145843.111923:ERROR:gl_display.cc(767)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[7646:0127/145843.112683:ERROR:angle_platform_impl.cc(44)] Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[7646:0127/145843.112734:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[7646:0127/145843.112769:ERROR:gl_display.cc(767)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[7646:0127/145843.112801:ERROR:gl_display.cc(801)] Initialization of all EGL display types failed.
[7646:0127/145843.112837:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.

(bitwarden-app:7606): Gtk-WARNING **: 14:58:43.114: Theme parsing error: gtk.css:3536:25: 'font-feature-settings' is not a valid property name
[7646:0127/145843.115342:ERROR:angle_platform_impl.cc(44)] Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[7646:0127/145843.115404:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[7646:0127/145843.115443:ERROR:gl_display.cc(767)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[7646:0127/145843.116158:ERROR:angle_platform_impl.cc(44)] Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[7646:0127/145843.116213:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[7646:0127/145843.116247:ERROR:gl_display.cc(767)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[7646:0127/145843.116280:ERROR:gl_display.cc(801)] Initialization of all EGL display types failed.
[7646:0127/145843.116314:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[7646:0127/145843.117201:ERROR:viz_main_impl.cc(181)] Exiting GPU process due to errors during initialization
libGL error: MESA-LOADER: failed to open radeonsi (search paths /snap/bitwarden/133/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast (search paths /snap/bitwarden/133/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: swrast
[7707:0127/145843.172130:ERROR:angle_platform_impl.cc(44)] Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[7707:0127/145843.172201:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[7707:0127/145843.172239:ERROR:gl_display.cc(767)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[7707:0127/145843.172961:ERROR:angle_platform_impl.cc(44)] Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[7707:0127/145843.173006:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[7707:0127/145843.173041:ERROR:gl_display.cc(767)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[7707:0127/145843.173073:ERROR:gl_display.cc(801)] Initialization of all EGL display types failed.
[7707:0127/145843.173109:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[7707:0127/145843.175488:ERROR:angle_platform_impl.cc(44)] Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[7707:0127/145843.175540:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[7707:0127/145843.175574:ERROR:gl_display.cc(767)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[7707:0127/145843.176257:ERROR:angle_platform_impl.cc(44)] Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[7707:0127/145843.176297:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[7707:0127/145843.176330:ERROR:gl_display.cc(767)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[7707:0127/145843.176362:ERROR:gl_display.cc(801)] Initialization of all EGL display types failed.
[7707:0127/145843.176400:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[7707:0127/145843.177213:ERROR:viz_main_impl.cc(181)] Exiting GPU process due to errors during initialization
MESA-LOADER: failed to open radeonsi (search paths /snap/bitwarden/133/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
failed to load driver: radeonsi
MESA-LOADER: failed to open kms_swrast (search paths /snap/bitwarden/133/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast (search paths /snap/bitwarden/133/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
failed to load swrast driver

**Comment by georglauterbach** [comment]
A workaround: use Flatseal (<https://flathub.org/apps/com.github.tchx84.Flatseal>) and set `ELECTRON_OZONE_PLATFORM_HINT=x11` in the environment variable section. This forces Bitwarden to run under XWayland.

**Comment by ripper81** [comment]
> A workaround: use Flatseal (https://flathub.org/apps/com.github.tchx84.Flatseal) and set `ELECTRON_OZONE_PLATFORM_HINT=x11` in the environment variable section. This forces Bitwarden to run under XWayland.

This issue is not related to the Flatpak. The snap package is causing this issue.

**Comment by georglauterbach** [comment]
> > A workaround: use Flatseal (https://flathub.org/apps/com.github.tchx84.Flatseal) and set `ELECTRON_OZONE_PLATFORM_HINT=x11` in the environment variable section. This forces Bitwarden to run under XWayland.
> 
> This issue is not related to the Flatpak. The snap package is causing this issue.

The same issue happens with Flatpak, actually. The solution I proposed is only valid for Flatpak, of course. But for anyone coming from a search engine, this might help.

**Comment by dennisTGC** [comment]
me2:

```
Operating System: KDE neon 6.2
KDE Plasma Version: 6.3.0
KDE Frameworks Version: 6.10.0
Qt Version: 6.8.2
Kernel Version: 6.11.0-17-generic (64-bit)
Graphics Platform: Wayland
Processors: 24 × AMD Ryzen 9 5900 12-Core Processor
Memory: 31,3 GiB of RAM
Graphics Processor: NV174
Manufacturer: Alienware
Product Name: Alienware Aurora Ryzen Edition R14
System Version: 2.18.0
```

As we are paying customer I have also reported this to bitwarden tech support.

**Comment by atomcult** [comment]
For some reason the snap is looking for the wayland socket in `$XDG_RUNTIME_DIR`, rather than `$XDG_RUNTIME_DIR/../`. This is something that `desktop-init.sh` should be passing along in the command-chain. If I get some extra cycles, I'll try to look into this and open an MR.

For those looking for a workaround:
```sh
# Ensure the wayland interface is connected
snap connect bitwarden:wayland

export WAYLAND_DISPLAY="${XDG_RUNTIME_DIR:-"/run/user/$(id -u)"}/${WAYLAND_DISPLAY}"
bitwarden
```

**Comment by zR-JB** [comment]
> For those looking for a workaround:
> 
> ```bash
># Ensure the wayland interface is connected
> snap connect bitwarden:wayland
> 
> # Manually set the full path to the Wayland socket and launch
> export WAYLAND_DISPLAY="${XDG_RUNTIME_DIR:-"/run/user/$(id -u)"}/${WAYLAND_DISPLAY}"
> bitwarden```


can confirm, this fixed it!

**Comment by trmartin4** [comment]
Hello.  We would like to close this issue if there are no longer any users actively experiencing it.  Please let us know if this issue is still occurring, as we have not been able to reproduce it internally.

Thank you!

**Comment by mtb-xt** [comment]
> Hello. We would like to close this issue if there are no longer any users actively experiencing it. Please let us know if this issue is still occurring, as we have not been able to reproduce it internally.
> 
> Thank you!

Still happens for me.


https://gist.github.com/mtb-xt/aefe54f5044a5217f461b37d2d056002

❯ uname -a
Linux 9SP-PF5FCDBT.epd.9spokes.net 6.17.0-22-generic #22~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Mar 26 15:25:54 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

on ⛵ core-apse2-auto () ~/win-mdm on 󰠅 infra
❯ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.4 LTS (Noble Numbat)"

**Comment by pamperer562580892423** [comment]
> Still happens for me.
> 
> https://gist.github.com/mtb-xt/aefe54f5044a5217f461b37d2d056002

@mtb-xt  That doesn't seem to contain the "Failed to initialize Wayland platform" error.
