### ISSUE TITLE
Bitwarden instantly crashes, endeavour/arch

### ISSUE THREAD

**Issue by jonasdeluna** [bitwarden/clients#12111]
### Steps To Reproduce

1. Run bitwarden-desktop on endeavour
2. Crashes

### Expected Result

It opens

### Actual Result

It crashes

### Screenshots or Videos

❯ bitwarden-desktop
App threw an error during load
SyntaxError: Unterminated string in JSON at position 20480 (line 400 column 122)
    at JSON.parse (<anonymous>)
    at Conf._deserialize (/usr/lib/bitwarden/app.asar/main.js:10101:43)
    at get store (/usr/lib/bitwarden/app.asar/main.js:10312:43)
    at new Conf (/usr/lib/bitwarden/app.asar/main.js:10165:32)
    at new ElectronStore (/usr/lib/bitwarden/app.asar/main.js:14728:3)
    at new ElectronStorageService (/usr/lib/bitwarden/app.asar/main.js:86361:22)
    at new Main (/usr/lib/bitwarden/app.asar/main.js:87065:31)
    at 83243 (/usr/lib/bitwarden/app.asar/main.js:74825:18)
    at __webpack_require__ (/usr/lib/bitwarden/app.asar/main.js:89849:42)
    at /usr/lib/bitwarden/app.asar/main.js:89905:37
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unterminated string in JSON at position 20480 (line 400 column 122)
    at JSON.parse (<anonymous>)
    at Conf._deserialize (/usr/lib/bitwarden/app.asar/main.js:10101:43)
    at get store (/usr/lib/bitwarden/app.asar/main.js:10312:43)
    at new Conf (/usr/lib/bitwarden/app.asar/main.js:10165:32)
    at new ElectronStore (/usr/lib/bitwarden/app.asar/main.js:14728:3)
    at new ElectronStorageService (/usr/lib/bitwarden/app.asar/main.js:86361:22)
    at new Main (/usr/lib/bitwarden/app.asar/main.js:87065:31)
    at 83243 (/usr/lib/bitwarden/app.asar/main.js:74825:18)
    at __webpack_require__ (/usr/lib/bitwarden/app.asar/main.js:89849:42)
    at /usr/lib/bitwarden/app.asar/main.js:89905:37

### Additional Context

Version 2024.11.2-1
Plasma 6.2.3

### Operating System

Linux

### Operating System Version

6.11.9-arch1-1

### Installation method

Other

### Build Version

Cannot open the app

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @jonasdeluna,

Thank you for reporting this. I tested a fresh new installation on EndeavourOS (6.12.1-arch1-1) with Bitwarden 2024.11.2 which was installed via pacman, and the client launched as expected and I was able to log into an individual Bitwarden account. With that in mind, I'd recommend that you first proceed with a fresh new installation by uninstalling Bitwarden, rebooting, and installing it anew; you may need to clear some [leftover data](https://bitwarden.com/help/data-storage/#on-your-local-machine) depending on your setup.

If this behaviour persists, please feel free to create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track potential bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
