### ISSUE TITLE
Cannot unlock extension with biometric

### ISSUE THREAD

**Issue by Sclafus** [bitwarden/clients#12177]
### Steps To Reproduce

1. Login on the Bitwarden Desktop Application
2. Enable browser integration 
3. Leave the application running
4. Go to the Bitwarden Browser Extension on Brave
5. Enable the "Unlock with biometrics" option

### Expected Result

Being able to unlock the vault using biometrics

### Actual Result

Error in the extension

### Screenshots or Videos

Desktop app settings:
![image](https://github.com/user-attachments/assets/5ae945cf-5473-42ad-b617-3ed664f9c727)
Browser extension error:
![image](https://github.com/user-attachments/assets/87fed2d5-19ea-48d4-91e2-2e2991c78ee2)

### Additional Context

Not sure if relevant: I have setup biometric unlocking in the desktop app and it works as expected.

### Operating System

Linux

### Operating System Version

Arch Linux

### Web Browser

Brave

### Browser Version

1.73.91

### Build Version

2024.11.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Sclafus** [comment]
Apparently this happens on my work laptop as well (Windows 11 24H2)

**Comment by SergeantConfused** [comment]
Hi @Sclafus,

Thank you for this report. Could you please review the [desktop client's app.log](https://bitwarden.com/help/data-storage/#on-your-local-machine) file and let me know if there are any events related to that message in the extension on either Linux or Windows?

Also, could you please detail your Arch Linux setup, and how you installed the Bitwarden desktop client on it?

To be clear, in my testing, this is working as expected on Windows 11 Pro (23H2) and Brave.

Thank you in advance,

**Comment by felixfrank** [comment]
I have the same issue. Chromium is working, however Brave, which is based a Chrome browser, does not get detected.

**Comment by DestinyofYeet** [comment]
I have the same issue with firefox

**Comment by pamperer562580892423** [comment]
> I have the same issue with firefox

@DestinyofYeet ... on MacOS?

**Comment by DestinyofYeet** [comment]
> > I have the same issue with firefox
> 
> [@DestinyofYeet](https://github.com/DestinyofYeet) ... on MacOS?

Sorry, I am on regular Linux (x86-64, NixOS)

**Comment by pamperer562580892423** [comment]
> Sorry, I am on regular Linux (x86-64, NixOS)

@DestinyofYeet Okay, for one thing, check if your desktop app version/package does support biometrics for the extensions:

<img width="915" height="474" alt="Image" src="https://github.com/user-attachments/assets/1bee7b94-7972-4cd2-aad7-8b0b602e54e8" />

(--> https://bitwarden.com/help/desktop-app-feature-support/#linux)

The other thing I thought of before (and why I asked for MacOS): you could check if Firefox has the necessary file: https://github.com/bitwarden/clients/issues/18996 (that issue though was mostly an issue on MacOS as it seems - if that corresponding file is also missing on Linux for you, you might add that info to that issue as well)

**Comment by DestinyofYeet** [comment]
It looks like the polkit policy is being installed in the [installation process](https://github.com/NixOS/nixpkgs/blob/0726a0ecb6d4e08f6adced58726b95db924cef57/pkgs/by-name/bi/bitwarden-desktop/package.nix#L205). It may still be broken though.

And I have an entry in my native-messaging-hosts folder
```
~/.mozilla/native-messaging-hosts
✦ ❯ cat com.8bit.bitwarden.json
{
  "name": "com.8bit.bitwarden",
  "description": "Bitwarden desktop <-> browser bridge",
  "path": "/nix/store/m841pysp6vb7iz6w7qfm4y78z04189yb-bitwarden-desktop-2026.2.1/libexec/desktop_proxy",
  "type": "stdio",
  "allowed_extensions": [
    "{446900e4-71c2-419f-a6a7-df9c091e268b}"
  ]
}
```

I do get the following error when confirming the access on the desktop application:

```
15:49:45.549 › [Native Messaging IPC] Clearing connected apps
15:49:48.257 › [Native Messaging IPC] Browser integration fingerprint validation is disabled, untrusting all connected apps
15:49:48.257 › Native messaging server started at: /home/ole/.cache/com.bitwarden.desktop/s.bw
15:49:48.258 › Chrome not found, skipping.
15:49:48.258 › Microsoft Edge not found, skipping.
15:50:10.144 › Native messaging client 1 has connected
15:50:10.472 › [Native Messaging IPC] Setting up secure channel
15:50:16.644 › [Native Messaging IPC] Fingerprint verified.
15:50:16.657 › [Main Biometrics IPC Listener] unlockForUser failed Error: Biometric authentication failed
    at OsBiometricsServiceLinux.<anonymous> (/nix/store/m841pysp6vb7iz6w7qfm4y78z04189yb-bitwarden-desktop-2026.2.1/opt/Bitwarden/resources/app.asar/main.js:48061:23)
    at Generator.next (<anonymous>)
    at fulfilled (/nix/store/m841pysp6vb7iz6w7qfm4y78z04189yb-bitwarden-desktop-2026.2.1/opt/Bitwarden/resources/app.asar/main.js:47978:58)
```

The main cause could be ofc, that my laptop doesn't have a direct biometric support (fingerprint sensor or such), I hoped that I could use something else and test around once I get the feature working.

**Comment by pamperer562580892423** [comment]
@DestinyofYeet One thing I think I can add: you must make sure that biometric unlock works for the desktop app (!) before it can work for any of the browser extensions. - Please also have a look into the Help Sites: https://bitwarden.com/help/biometrics/
