### ISSUE TITLE
npm run electron shows no window on debian bookworm

### ISSUE THREAD

**Issue by Haui1112** [bitwarden/clients#12184]
### Steps To Reproduce

1. go to https://contributing.bitwarden.com/getting-started/clients/desktop/ and follow instructions
2. install dependencies (build-essential, libsecret-1-dev, libglib2.0-dev, rust)
3. clone repo
4. npm run electron 
5. see error

### Expected Result

Window opens and app runs

### Actual Result

No window opens, console shows error:  

```
Error: Cannot find module '@bitwarden/desktop-napi-linux-x64-musl'
```
similar to #3544 

I have tried cross compilation, even changing the branch to the last desktop release, with the same result. I have rebuilt the module about 20 times with different approaches, used force-clean and other methods in case there is a problem with build artifacts.

### Screenshots or Videos

Complete error message:
```
[Main] webpack 5.96.1 compiled successfully in 16683 ms
[Rend] [BABEL] Note: The code generator has deoptimised the styling of /home/haui/Development/bitwarden/clients/node_modules/@angular/core/fesm2022/core.mjs as it exceeds the max of 500KB.
[Elec] Debugger listening on ws://127.0.0.1:5858/4a203fca-7596-4330-9009-fc8e50f0adb7
[Elec] For help, see: https://nodejs.org/en/docs/inspector
[Elec] App threw an error during load
[Elec] Error: Cannot find module '@bitwarden/desktop-napi-linux-x64-musl'
[Elec] Require stack:
[Elec] - /home/haui/Development/bitwarden/clients/apps/desktop/desktop_native/napi/index.js
[Elec] - /home/haui/Development/bitwarden/clients/apps/desktop/build/main.js
[Elec]     at Module._resolveFilename (node:internal/modules/cjs/loader:1232:15)
[Elec]     at s._resolveFilename (node:electron/js2c/browser_init:2:124039)
[Elec]     at Module._load (node:internal/modules/cjs/loader:1058:27)
[Elec]     at c._load (node:electron/js2c/node_init:2:17025)
[Elec]     at Module.require (node:internal/modules/cjs/loader:1318:19)
[Elec]     at require (node:internal/modules/helpers:179:18)
[Elec]     at Object.<anonymous> (/home/haui/Development/bitwarden/clients/apps/desktop/desktop_native/napi/index.js:160:29)
[Elec]     at Module._compile (node:internal/modules/cjs/loader:1484:14)
[Elec]     at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
[Elec]     at Module.load (node:internal/modules/cjs/loader:1295:32)
[Elec] A JavaScript error occurred in the main process
[Elec] Uncaught Exception:
[Elec] Error: Cannot find module '@bitwarden/desktop-napi-linux-x64-musl'
[Elec] Require stack:
[Elec] - /home/haui/Development/bitwarden/clients/apps/desktop/desktop_native/napi/index.js
[Elec] - /home/haui/Development/bitwarden/clients/apps/desktop/build/main.js
[Elec]     at Module._resolveFilename (node:internal/modules/cjs/loader:1232:15)
[Elec]     at s._resolveFilename (node:electron/js2c/browser_init:2:124039)
[Elec]     at Module._load (node:internal/modules/cjs/loader:1058:27)
[Elec]     at c._load (node:electron/js2c/node_init:2:17025)
[Elec]     at Module.require (node:internal/modules/cjs/loader:1318:19)
[Elec]     at require (node:internal/modules/helpers:179:18)
[Elec]     at Object.<anonymous> (/home/haui/Development/bitwarden/clients/apps/desktop/desktop_native/napi/index.js:160:29)
[Elec]     at Module._compile (node:internal/modules/cjs/loader:1484:14)
[Elec]     at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
[Elec]     at Module.load (node:internal/modules/cjs/loader:1295:32)
```

### Operating System

Linux

### Operating System Version

Bookworm (12)

### Installation method

Other

### Build Version

desktop-v2024.11.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Haui1112** [comment]
Yo! I didnt know you were actually part of bitwarden inc. I have been using your vaultwarden for a long time and am spreading the word wherever I can about both projects. Fanboy moment. Thanks for your service! 

On the issue: thank you. I will update as soon as I can access my build machine.

**Comment by dani-garcia** [comment]
Hey @Haui1112! 

Did you get any chance to test the build with the commands in https://github.com/bitwarden/clients/issues/12184#issuecomment-2514907261?
