### ISSUE TITLE
Unable to start Bitwarden on ArchLinux (6.12.4-arch1-1)

### ISSUE THREAD

**Issue by Doubble29x** [bitwarden/clients#12332]
### Steps To Reproduce

Start bitwarden-desktop

### Expected Result

Gui popping up

### Actual Result

App doesn't start at all and throws an **error log** in terminal.

### Additional Context

```
App threw an error during load
SyntaxError: Unterminated string in JSON at position 45056 (line 1119 column 48)
    at JSON.parse (<anonymous>)
    at Conf._deserialize (/usr/lib/bitwarden/app.asar/main.js:10101:43)
    at get store (/usr/lib/bitwarden/app.asar/main.js:10312:43)
    at new Conf (/usr/lib/bitwarden/app.asar/main.js:10165:32)
    at new ElectronStore (/usr/lib/bitwarden/app.asar/main.js:14728:3)
    at new ElectronStorageService (/usr/lib/bitwarden/app.asar/main.js:86361:22)
    at new Main (/usr/lib/bitwarden/app.asar/main.js:87065:31)
    at 83243 (/usr/lib/bitwarden/app.asar/main.js:74825:18)
    at __webpack_require__ (/usr/lib/bitwarden/app.asar/main.js:89849:42)
    at /usr/lib/bitwarden/app.asar/main.js:89905:37
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unterminated string in JSON at position 45056 (line 1119 column 48)
    at JSON.parse (<anonymous>)
    at Conf._deserialize (/usr/lib/bitwarden/app.asar/main.js:10101:43)
    at get store (/usr/lib/bitwarden/app.asar/main.js:10312:43)
    at new Conf (/usr/lib/bitwarden/app.asar/main.js:10165:32)
    at new ElectronStore (/usr/lib/bitwarden/app.asar/main.js:14728:3)
    at new ElectronStorageService (/usr/lib/bitwarden/app.asar/main.js:86361:22)
    at new Main (/usr/lib/bitwarden/app.asar/main.js:87065:31)
    at 83243 (/usr/lib/bitwarden/app.asar/main.js:74825:18)
    at __webpack_require__ (/usr/lib/bitwarden/app.asar/main.js:89849:42)
    at /usr/lib/bitwarden/app.asar/main.js:89905:37
src/gbm_drv_common.c:131: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000
```

### Operating System

Linux

### Operating System Version

6.12.4-arch1-1

### Installation method

Other

### Build Version

2024.11.2-1 in Pacman software repository

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

This issue has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by eandersons** [comment]
For me the Bitwarden desktop client stopped working in the last week (or maybe a little bit earlier).

```
╰─λ bitwarden-desktop
App threw an error during load
SyntaxError: Unterminated string in JSON at position 28672 (line 489 column 62)
at JSON.parse (<anonymous>)
at Conf._deserialize (/usr/lib/bitwarden/app.asar/main.js:10101:43)
at get store (/usr/lib/bitwarden/app.asar/main.js:10312:43)
at new Conf (/usr/lib/bitwarden/app.asar/main.js:10165:32)
at new ElectronStore (/usr/lib/bitwarden/app.asar/main.js:15043:3)
at new ElectronStorageService (/usr/lib/bitwarden/app.asar/main.js:87311:22)
at new Main (/usr/lib/bitwarden/app.asar/main.js:88021:31)
at 83243 (/usr/lib/bitwarden/app.asar/main.js:75140:18)
at __webpack_require__ (/usr/lib/bitwarden/app.asar/main.js:90823:42)
at /usr/lib/bitwarden/app.asar/main.js:90987:37
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unterminated string in JSON at position 28672 (line 489 column 62)
at JSON.parse (<anonymous>)
at Conf._deserialize (/usr/lib/bitwarden/app.asar/main.js:10101:43)
at get store (/usr/lib/bitwarden/app.asar/main.js:10312:43)
at new Conf (/usr/lib/bitwarden/app.asar/main.js:10165:32)
at new ElectronStore (/usr/lib/bitwarden/app.asar/main.js:15043:3)
at new ElectronStorageService (/usr/lib/bitwarden/app.asar/main.js:87311:22)
at new Main (/usr/lib/bitwarden/app.asar/main.js:88021:31)
at 83243 (/usr/lib/bitwarden/app.asar/main.js:75140:18)
at __webpack_require__ (/usr/lib/bitwarden/app.asar/main.js:90823:42)
at /usr/lib/bitwarden/app.asar/main.js:90987:37
Gtk-Message: 10:07:05.566: Failed to load module "colorreload-gtk-module"
Gtk-Message: 10:07:05.566: Failed to load module "window-decorations-gtk-module"
MESA-LOADER: failed to open nvidia-drm: /usr/lib/gbm/nvidia-drm_gbm.so: cannot open shared object file: No such file or directory (search paths /usr/lib/gbm, suffix _gbm)
```

Operating system: Arch Linux
Desktop environment: KDE Plasma with Wayland
Bitwarden version: 2025.1.3-1

**Comment by Extauren** [comment]
Same error with 2025.2.1-1 with bitwarden-desktop with paman and bitwarden-bin with AUR on ArchLinux and Hyprland as desktop environment
Kernel version : 6.13.7-arch1-1

bitwarden-desktop with pacman
```
App threw an error during load
SyntaxError: Unterminated string in JSON at position 4096 (line 123 column 18)
    at JSON.parse (<anonymous>)
    at Conf._deserialize (/usr/lib/bitwarden/app.asar/main.js:10101:43)
    at get store (/usr/lib/bitwarden/app.asar/main.js:10312:43)
    at new Conf (/usr/lib/bitwarden/app.asar/main.js:10165:32)
    at new ElectronStore (/usr/lib/bitwarden/app.asar/main.js:15062:3)
    at new ElectronStorageService (/usr/lib/bitwarden/app.asar/main.js:87170:22)
    at new Main (/usr/lib/bitwarden/app.asar/main.js:87869:31)
    at 83243 (/usr/lib/bitwarden/app.asar/main.js:71880:18)
    at __webpack_require__ (/usr/lib/bitwarden/app.asar/main.js:90673:42)
    at /usr/lib/bitwarden/app.asar/main.js:90837:37
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unterminated string in JSON at position 4096 (line 123 column 18)
    at JSON.parse (<anonymous>)
    at Conf._deserialize (/usr/lib/bitwarden/app.asar/main.js:10101:43)
    at get store (/usr/lib/bitwarden/app.asar/main.js:10312:43)
    at new Conf (/usr/lib/bitwarden/app.asar/main.js:10165:32)
    at new ElectronStore (/usr/lib/bitwarden/app.asar/main.js:15062:3)
    at new ElectronStorageService (/usr/lib/bitwarden/app.asar/main.js:87170:22)
    at new Main (/usr/lib/bitwarden/app.asar/main.js:87869:31)
    at 83243 (/usr/lib/bitwarden/app.asar/main.js:71880:18)
    at __webpack_require__ (/usr/lib/bitwarden/app.asar/main.js:90673:42)
    at /usr/lib/bitwarden/app.asar/main.js:90837:37
```

bitwarden-bin with AUR

```
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unterminated string in JSON at position 4096 (line 123 column 18)
    at JSON.parse (<anonymous>)
    at Conf._deserialize (/opt/Bitwarden/resources/app.asar/main.js:10101:43)
    at get store (/opt/Bitwarden/resources/app.asar/main.js:10312:43)
    at new Conf (/opt/Bitwarden/resources/app.asar/main.js:10165:32)
    at new ElectronStore (/opt/Bitwarden/resources/app.asar/main.js:15062:3)
    at new ElectronStorageService (/opt/Bitwarden/resources/app.asar/main.js:89119:22)
    at new Main (/opt/Bitwarden/resources/app.asar/main.js:89851:31)
    at 83243 (/opt/Bitwarden/resources/app.asar/main.js:71887:18)
    at __webpack_require__ (/opt/Bitwarden/resources/app.asar/main.js:92786:42)
    at /opt/Bitwarden/resources/app.asar/main.js:92950:37
```

**Comment by lluisaliano** [comment]
To solve the issue, just delete Bitwarden's config folder located at ~/.config/Bitwarden/.
The problem seems to be caused by a corrupted config file but I don't know why that happened.

**Comment by trmartin4** [comment]
This appears to have the same root cause as https://github.com/bitwarden/clients/issues/11030, so we will be closing this to consolidate our efforts on that one.  If you disagree with that association, please feel free to re-open.

**Comment by nh2** [comment]
> same root cause as [#11030](https://github.com/bitwarden/clients/issues/11030), so we will be closing this to consolidate our efforts on that one

@trmartin4 That one was auto-closed by a bot.

Of course the problem is still there today, because time doesn't fix bugs.

Can you re-open that one or should I file a third issue on the same topic?
