### ISSUE TITLE
Bitwarden FIDO2 dialog don't show when it's in an iframe, sameOriginWithAncestors error.

### ISSUE THREAD

**Issue by tmikaeld** [bitwarden/clients#12590]
### Steps To Reproduce

1. Go to any fido2 that's in an iframe
2. Add a key
3. Check terminal

### Expected Result

Bitwarden dialog should show, asking for passkey

### Actual Result

```
Error: Invalid 'sameOriginWithAncestors' value
    at Messenger.<anonymous> (fido2-page-script.js:294:35)
    at Generator.next (<anonymous>)
    at fulfilled (fido2-page-script.js:230:58)
```

### Operating System

macOS

### Operating System Version

15.1.1

### Web Browser

Chrome, Brave

### Browser Version

1.73.97

### Build Version

Version: 2024.12.3 SDK: 'main (edee180)'

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by ptrne** [comment]
As a temporary workaround: Try showing the Sidebar (View -> Sidebar -> Bitwarden) and performing actions there.

**Comment by ptrne** [comment]
I also encountered this issue recently when adding an account to the browser extension.

*Steps to reproduce*
* Install extension
* Add 2FA-enabled account
* After having entered the master password, the 2FA "window" opens. It only shows a gray windows without any contents.

*System*
* Linux 6.6.62
* Firefox 133.0.3
* Bitwarden Extension 2024.12.3
* GNOME 46

*Workaround*
Try using the Sidebar (View -> Sidebar -> Bitwarden) and performing actions there.

**Comment by tmikaeld** [comment]
A workaround is not enough though, since this breaks FIDO2 completely where it's being used in an iframe.

**Comment by antonlydell** [comment]
I have encountered the same issue and previously opened this ticket [Unknown errorCode "Invalid 'sameOriginWithAncestors' value" when signed in to Bitwarden browser extension #62](https://github.com/bitwarden/passwordless-client-js/issues/62) in the [passwordless-client-js repo](https://github.com/bitwarden/passwordless-client-js)

The issue still persists and the described workaround above "Try using the Sidebar (View -> Sidebar -> Bitwarden) and performing actions there." does not work here.

System:
- Linux 6.8.0
- Firefox 133.0.3
- Bitwarden Browser Extension : 2024.12.3

**Comment by tmikaeld** [comment]
Is there a way to disable FIDO2 hijacking on the site itself? 

Because right now it's not possible for users to exclude Bitwarden since it doesn't even open the dialog - they have to disable the whole extension, which is not an option.

**Comment by antonlydell** [comment]
Update 2025-01-03 :

It works to sign in with a passkey from the Browser extension when the sign in workflow is triggered from within an iframe. However, it does not work to register a new passkey and save it to Bitwarden through the Browser extension when the register workflow is triggered from within an iframe.

1.  Navigate to https://passwordless.streamlit.app and register a new passkey using the Bitwarden mobile app. This should work fine.

2.  Navigate to https://passwordless.streamlit.app in your desktop browser and sign in with the newly created passkey using Bitwarden Browser extension. This should work ok.
 
3. On the home page of https://passwordless.streamlit.app use the register form to register another passkey while the Bitwarden Browser extension is unlocked. The following error should now be raised : 

`Error creating passkey for user "test"! error : {'from': 'client', 'errorCode': 'unknown', 'title': "Invalid 'sameOriginWithAncestors' value"}`

**Comment by tmikaeld** [comment]
In our case, the register and login works since it's outside of an iframe, but the adding of additional keys is inside the iframe and becomes blocked by sameOriginWithAncestors.

**Comment by antonlydell** [comment]
> In our case, the register and login works since it's outside of an iframe, but the adding of additional keys is inside (and initiated from within) the iframe and becomes blocked by sameOriginWithAncestors.

Ok, then we have to sources yielding the same error.

**Comment by kytta** [comment]
I have encountered this issue when evaluating [Pocket ID](https://github.com/stonith404/pocket-id):

1. Go to the repo
2. Click on "Demo" and start demo
3. Under "Passkeys", click "Add Passkey"
4. The error appears

I've noticed that Streamlit Passwordless does not have `publickey-credentials-create` in its `iframe[allow]`. Pocket ID does, but it does not seem to help in this case. The Sidebar workaround does not help, and I didn't have time to test whether using existing Passkeys would work.

I am using Bitwarden Extension v2024.12.3 (SDK main (edee180)) on Firefox 134.0 on macOS Sonoma 14.7.2 (23H311)

**Comment by pluja** [comment]
I am facing the same errors @kytta described. 

When testing out [Pocket ID](https://github.com/stonith404/pocket-id), I see the error `Invalid 'sameOriginWithAncestors'`. 

Same with Streamlit Passwordless: `Error creating passkey for user (example)! error : {'from': 'client', 'errorCode': 'unknown', 'title': "Invalid 'sameOriginWithAncestors' value"}`

**Comment by SergeantConfused** [comment]
Hello everyone,

Thank you all for your input. I would like to update that this matter was captured internally and flagged to the Engineering department; please feel free to post additional information, such as screenshots or a screen video recordings, if you wish.

@tmikaeld, with regard to:

> Is there a way to disable FIDO2 hijacking on the site itself?
> 
> Because right now it's not possible for users to exclude the site in Bitwarden since it doesn't even open the dialog - they have to disable the whole extension, which is not an option.

You can add a URL to the browser extension's [Excluded domains](https://bitwarden.com/help/exclude-domains/) list; in my testing at (https://passwordless.streamlit.app/), that allowed the operating system (Windows) to intercept the request and offer to use Windows Hello or a physical key, even whilst the Bitwarden browser extension was active and unlocked.

Thank you all again,

**Comment by antonlydell** [comment]
@SergeantConfused : Great to finally receive some feedback on this issue! Even though the fix might not be ready yet the community always appreciate feedback on issues. Do you know when this might be fixed?

**Comment by tmikaeld** [comment]
@SergeantConfused This doesn't fix the issue that users do now know that it doesn't work, I'm asking for blocking it in the site header or html itself, so that bitwarden does not even ask for confirm/deny using it.

**Comment by seanm-fathomhq** [comment]
It's been 12 months since the last comment on this issue and the problem persists, is there any movement on this yet?

**Comment by shubham399** [comment]
> As a temporary workaround for Firefox): Try showing the Sidebar (View -> Sidebar -> Bitwarden) and performing actions there.
> 
> Edit: Does only work with Firefox ofc.
Tried this and not working on Zen browser

**Comment by danielcarlan** [comment]
Still no fix? At least to be able to bypass bitwarden from the hosting site itself, not manually by the unsuspecting user.
Please solve this issue, as for now we have to disable fido2 completely, just because of this nasty bug.
