### ISSUE TITLE
App not starting on Wayland with gnome 40

### ISSUE THREAD

**Issue by WAPEETY** [bitwarden/clients#2604]
## Describe the Bug

I can´t start the app on my laptop, when I start it just display a white window until gnome says "Bitwarden is not responding"

## Steps To Reproduce

1. Install fedora 34 with wayland and gnome 40
2. Install Bitwarden from Flatpak (FlatHub)

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/38016769/122110417-cb4b9100-ce1e-11eb-8720-ba2d5679c2c2.png)

## Environment

- Operating system: GNU/Linux - Fedora 34 with Gnome 40 on wayland
- Installation method: Downloaded from Flatpak (FlatHub) 
- Build Version: 1.26.5 (saw from gnome software since the program doesn't start)
## StackTrace

EDIT: Actually this stacktrace has apparently nothing to do with the problem, on the same computer using X server instead of wayland the application works fine

```[wapeety@thinkpad bin]$ ./com.bitwarden.desktop
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/Bitwarden/bitwarden --type=zygote
(node:2) DeprecationWarning: file property is deprecated and will be removed in v5.
Gtk-Message: 21:33:48.099: Failed to load module "canberra-gtk-module"
Gtk-Message: 21:33:48.099: Failed to load module "pk-gtk-module"
Gtk-Message: 21:33:48.099: Failed to load module "canberra-gtk-module"
Gtk-Message: 21:33:48.100: Failed to load module "pk-gtk-module"
libGL error: MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
(node:2) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
(node:2) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'setContextMenu' of undefined
    at tray_main_TrayMain.updateContextMenu (/app/Bitwarden/resources/app.asar/main.js:19568:23)
    at messaging_main_MessagingMain.updateTrayMenu (/app/Bitwarden/resources/app.asar/main.js:19052:28)
    at messaging_main_MessagingMain.onMessage (/app/Bitwarden/resources/app.asar/main.js:18993:22)
    at messaging_main_MessagingMain.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:18984:154)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:18962:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/app/Bitwarden/resources/app.asar/main.js:18958:12)
    at IpcMainImpl.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:18984:82)
    at IpcMainImpl.emit (events.js:315:20)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by kureta** [comment]
Running it like this works `flatpak run com.bitwarden.desktop --use-gl=egl` I don't know why :)

**Comment by 66schoollane** [comment]
yes indeed, with opening up terminal & pasting in either as above post or in text below works, But: how do you add this to the icon on my stock Fedora launch window, below is a workaround not a solution to the problem.
flatpak run com.bitwarden.desktop --use-gl=egl
flatpak run com.bitwarden.desktop --use-gl=wayland
flatpak run com.bitwarden.desktop --use-gl=desktop

**Comment by septatrix** [comment]
> But: how do you add this to the icon on my stock Fedora launch window, below is a workaround not a solution to the problem.

Not quite sure about that icon on the taskbar but in general you can add starting options similar to all other non-flatpak application (just with a different path) by copying the desktop file from `/var/lib/flatpak/exports/share/applications/<foobar>.desktop` to `~/.local/share/applications/<foobar>.desktop` and adding the flags to `Exec=`. This potentially requires logging out and back in.

**Comment by YamiYukiSenpai** [comment]
Is it still broken in Wayland?

Not launching on Plasma Wayland

**Comment by fuchs-fabian** [comment]
It is currently broken on Fedora 41 with Wayland. It only works on Xorg or like this on Wayland:

```shell
flatpak run com.bitwarden.desktop --use-gl=wayland
```

```shell
flatpak run com.bitwarden.desktop --use-gl=desktop
```

If I want to start it normally...

```shell
flatpak run com.bitwarden.desktop
```

it does not start and the following is displayed:

```plain
[2 zypak-helper] /app/Bitwarden/bitwarden is not an ELF file
[2 zypak-helper] (it appears to be a shell script?)
[2 zypak-helper] WARNING: supplied target /app/Bitwarden/bitwarden does not look like a valid Chromium binary!
[2 zypak-helper] Zypak needs to be called directly on the executable *binary*, not any wrappers.
[2 preload-host-spawn-strategy] Warning: waitpid override ignores groups
[2 preload-host-spawn-strategy] Warning: waitpid override ignores groups
[2 preload-host-spawn-strategy] Warning: waitpid override ignores groups
[2 preload-host-spawn-strategy] Warning: waitpid override ignores groups
[2 preload-host-spawn-strategy] Warning: waitpid override ignores groups
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
16:34:06.935 › State version: 68
16:34:06.937 › Migrator MinVersionMigrator (to version 3) should migrate: false - up
16:34:06.937 › Migrator RemoveEverBeenUnlockedMigrator (to version 4) should migrate: false - up
16:34:06.937 › Migrator AddKeyTypeToOrgKeysMigrator (to version 5) should migrate: false - up
16:34:06.938 › Migrator RemoveLegacyEtmKeyMigrator (to version 6) should migrate: false - up
16:34:06.938 › Migrator MoveBiometricAutoPromptToAccount (to version 7) should migrate: false - up
16:34:06.938 › Migrator MoveStateVersionMigrator (to version 8) should migrate: false - up
16:34:06.938 › Migrator MoveBrowserSettingsToGlobal (to version 9) should migrate: false - up
16:34:06.939 › Migrator EverHadUserKeyMigrator (to version 10) should migrate: false - up
16:34:06.939 › Migrator OrganizationKeyMigrator (to version 11) should migrate: false - up
16:34:06.939 › Migrator MoveEnvironmentStateToProviders (to version 12) should migrate: false - up
16:34:06.939 › Migrator ProviderKeyMigrator (to version 13) should migrate: false - up
16:34:06.939 › Migrator MoveBiometricClientKeyHalfToStateProviders (to version 14) should migrate: false - up
16:34:06.939 › Migrator FolderMigrator (to version 15) should migrate: false - up
16:34:06.939 › Migrator LastSyncMigrator (to version 16) should migrate: false - up
16:34:06.939 › Migrator EnablePasskeysMigrator (to version 17) should migrate: false - up
16:34:06.939 › Migrator AutofillSettingsKeyMigrator (to version 18) should migrate: false - up
16:34:06.939 › Migrator RequirePasswordOnStartMigrator (to version 19) should migrate: false - up
16:34:06.939 › Migrator PrivateKeyMigrator (to version 20) should migrate: false - up
16:34:06.939 › Migrator CollectionMigrator (to version 21) should migrate: false - up
16:34:06.939 › Migrator CollapsedGroupingsMigrator (to version 22) should migrate: false - up
16:34:06.939 › Migrator MoveBiometricPromptsToStateProviders (to version 23) should migrate: false - up
16:34:06.939 › Migrator SmOnboardingTasksMigrator (to version 24) should migrate: false - up
16:34:06.939 › Migrator ClearClipboardDelayMigrator (to version 25) should migrate: false - up
16:34:06.939 › Migrator RevertLastSyncMigrator (to version 26) should migrate: false - up
16:34:06.939 › Migrator BadgeSettingsMigrator (to version 27) should migrate: false - up
16:34:06.940 › Migrator MoveBiometricUnlockToStateProviders (to version 28) should migrate: false - up
16:34:06.940 › Migrator UserNotificationSettingsKeyMigrator (to version 29) should migrate: false - up
16:34:06.940 › Migrator PolicyMigrator (to version 30) should migrate: false - up
16:34:06.940 › Migrator EnableContextMenuMigrator (to version 31) should migrate: false - up
16:34:06.940 › Migrator PreferredLanguageMigrator (to version 32) should migrate: false - up
16:34:06.940 › Migrator AppIdMigrator (to version 33) should migrate: false - up
16:34:06.940 › Migrator DomainSettingsMigrator (to version 34) should migrate: false - up
16:34:06.940 › Migrator MoveThemeToStateProviderMigrator (to version 35) should migrate: false - up
16:34:06.940 › Migrator VaultSettingsKeyMigrator (to version 36) should migrate: false - up
16:34:06.940 › Migrator AvatarColorMigrator (to version 37) should migrate: false - up
16:34:06.940 › Migrator TokenServiceStateProviderMigrator (to version 38) should migrate: false - up
16:34:06.940 › Migrator MoveBillingAccountProfileMigrator (to version 39) should migrate: false - up
16:34:06.940 › Migrator OrganizationMigrator (to version 40) should migrate: false - up
16:34:06.940 › Migrator EventCollectionMigrator (to version 41) should migrate: false - up
16:34:06.940 › Migrator EnableFaviconMigrator (to version 42) should migrate: false - up
16:34:06.940 › Migrator AutoConfirmFingerPrintsMigrator (to version 43) should migrate: false - up
16:34:06.940 › Migrator UserDecryptionOptionsMigrator (to version 44) should migrate: false - up
16:34:06.940 › Migrator MergeEnvironmentState (to version 45) should migrate: false - up
16:34:06.940 › Migrator DeleteBiometricPromptCancelledData (to version 46) should migrate: false - up
16:34:06.940 › Migrator MoveDesktopSettingsMigrator (to version 47) should migrate: false - up
16:34:06.940 › Migrator MoveDdgToStateProviderMigrator (to version 48) should migrate: false - up
16:34:06.940 › Migrator AccountServerConfigMigrator (to version 49) should migrate: false - up
16:34:06.940 › Migrator KeyConnectorMigrator (to version 50) should migrate: false - up
16:34:06.940 › Migrator RememberedEmailMigrator (to version 51) should migrate: false - up
16:34:06.940 › Migrator DeleteInstalledVersion (to version 52) should migrate: false - up
16:34:06.941 › Migrator DeviceTrustServiceStateProviderMigrator (to version 53) should migrate: false - up
16:34:06.941 › Migrator SendMigrator (to version 54) should migrate: false - up
16:34:06.941 › Migrator MoveMasterKeyStateToProviderMigrator (to version 55) should migrate: false - up
16:34:06.941 › Migrator AuthRequestMigrator (to version 56) should migrate: false - up
16:34:06.941 › Migrator CipherServiceMigrator (to version 57) should migrate: false - up
16:34:06.941 › Migrator RemoveRefreshTokenMigratedFlagMigrator (to version 58) should migrate: false - up
16:34:06.941 › Migrator KdfConfigMigrator (to version 59) should migrate: false - up
16:34:06.941 › Migrator KnownAccountsMigrator (to version 60) should migrate: false - up
16:34:06.941 › Migrator PinStateMigrator (to version 61) should migrate: false - up
16:34:06.941 › Migrator VaultTimeoutSettingsServiceStateProviderMigrator (to version 62) should migrate: false - up
16:34:06.941 › Migrator PasswordOptionsMigrator (to version 63) should migrate: false - up
16:34:06.941 › Migrator GeneratorHistoryMigrator (to version 64) should migrate: false - up
16:34:06.941 › Migrator ForwarderOptionsMigrator (to version 65) should migrate: false - up
16:34:06.941 › Migrator MoveFinalDesktopSettingsMigrator (to version 66) should migrate: false - up
16:34:06.941 › Migrator RemoveUnassignedItemsBannerDismissed (to version 67) should migrate: false - up
16:34:06.941 › Migrator MoveLastSyncDate (to version 68) should migrate: false - up
16:34:07.034 › Coredumps are disabled in renderer process
LaunchProcess: failed to execvp:
xdg-settings
[13:1103/163407.123570:ERROR:wayland_event_watcher.cc(43)] libwayland: [destroyed object]: error 7: failed to import supplied dmabufs: Could not bind the given EGLImage to a CoglTexture2D

/app/Bitwarden/bitwarden: line 11:    13 Trace/breakpoint trap   (core dumped) $APP_PATH/bitwarden-app "$@"
[2 preload-host-spawn-strategy] Warning: waitpid override ignores groups
```

**Comment by iMonZ** [comment]
Same issue

**Comment by infinite-powered** [comment]
Same issue still with Fedora 44 Under Plasma 6.6.4. When disabling `--socket=x11` and `--share=ipc` with flatpak overrides the app just crashes at launch. Even the `--socket=fallback-x11` does nothing. Its been five years and wayland support is still lacking. For a password manager, you'd imagine wanting a window system where other programs could not look at its contents but here we are. As a long-time paying customer, this situation is unfortunate.
