### ISSUE TITLE
Fonts rendering as square boxes

### ISSUE THREAD

**Issue by thatnerdjosh** [bitwarden/clients#2628]
Not sure if this is a GTK issue of some sort but I am getting this issue in the file browser and the about screen... see the attached screenshot

![2019-12-30-060408_1920x1080_scrot](https://user-images.githubusercontent.com/5251847/71563933-b106e180-2aca-11ea-80b2-5211f513a7d8.png)

**Comment by im007** [comment]
Still an issue on Fedora 37, workaround above did not work.

**Comment by thatLeaflet** [comment]
> @cnmicha not to my knowledge. `electron-builder` doesn't support specifying a core version.

Based on the first bullet point of [this page](https://www.electron.build/configuration/snap.html), it seems to be possible to change the core version. But I could be mistaken, I've never used election builder.

**Comment by im007** [comment]
I ended up switching to the AppImage version -- that works fine.

**Comment by kaincenteno** [comment]
Have only seen it when trying to delete a secret on the confirmation window

![Screenshot from 2023-04-05 22-51-28](https://user-images.githubusercontent.com/26943220/230294126-aab3a02c-558f-4350-85fb-0b58dbce7ddf.png)

**Comment by bluppfisk** [comment]
If you've been messing around with removing font caches to no avail.. you may want to try the following (at least on Ubuntu). Go to settings / region & language / manage installed languages / pick a language / Apply System-Wide. I think my set-up was incomplete or mixed due to my installing an Chinese IME.

Rationale: due to some settings being set to Chinese, it was trying to pick a Chinese version of an installed font that either didn't exist or didn't provide the required glyphs.

**Comment by OnlyTuxUser** [comment]
> Does it work if you install `noto-fonts`

THX
I had the same problem.
Installing noto-serif-fonts solve the problem.

**Comment by klondikemarlen** [comment]
I tried install the noto fonts, but to no avail. Installed via https://installati.one/install-fonts-noto-ubuntu-20-04/

**Comment by el95149** [comment]
> Opening a terminal, executing `cd /var/lib/snapd/snap/bitwarden/current` and then `./bitwarden` works for me.
> 
> Here is a patched desktop entry file, place it at `/home/$USER/.local/share/applications/bitwarden_bitwarden.desktop`:
> ..........
>

On KUbuntu 23.04 this worked by setting the work path property, in the desktop entry, to:
```
Path=/snap/bitwarden/current
```

Thank you very much!!!

**Comment by AdamVe** [comment]
I have the same issue and nothing from this thread works for me :( I tried installing all `fonts-noto` or running from command line - still missing fonts in dialog. AppImage does not have this issue.

My installation:
```
Name       Version   Rev  Tracking       Publisher   Notes
bitwarden  2024.1.0  103  latest/stable  bitwarden✓  -
```
System: 
Ubuntu 23.10


<details>
<summary>Running from terminal shows font related warnings:</summary>

```
bitwarden --trace-warnings

(bitwarden:71453): Gtk-WARNING **: 10:24:18.487: Theme parsing error: gtk.css:1422:23: 'font-feature-settings' is not a valid property name

(bitwarden:71453): Gtk-WARNING **: 10:24:18.489: Theme parsing error: gtk.css:3308:25: 'font-feature-settings' is not a valid property name

(bitwarden:71453): Gtk-WARNING **: 10:24:18.490: Theme parsing error: gtk.css:3770:23: 'font-feature-settings' is not a valid property name
(node:71453) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'init')
    at BiometricsService.<anonymous> (/snap/bitwarden/103/resources/app.asar/main.js:49684:55)
    at Generator.next (<anonymous>)
    at /snap/bitwarden/103/resources/app.asar/main.js:49650:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/snap/bitwarden/103/resources/app.asar/main.js:49646:12)
    at BiometricsService.init (/snap/bitwarden/103/resources/app.asar/main.js:49683:16)
    at Main.<anonymous> (/snap/bitwarden/103/resources/app.asar/main.js:55950:46)
    at Generator.next (<anonymous>)
    at fulfilled (/snap/bitwarden/103/resources/app.asar/main.js:55838:58)
    at emitUnhandledRejectionWarning (node:internal/process/promises:200:15)
    at processPromiseRejections (node:internal/process/promises:296:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
(node:71453) TypeError: Cannot read properties of undefined (reading 'init')
    at BiometricsService.<anonymous> (/snap/bitwarden/103/resources/app.asar/main.js:49684:55)
    at Generator.next (<anonymous>)
    at /snap/bitwarden/103/resources/app.asar/main.js:49650:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/snap/bitwarden/103/resources/app.asar/main.js:49646:12)
    at BiometricsService.init (/snap/bitwarden/103/resources/app.asar/main.js:49683:16)
    at Main.<anonymous> (/snap/bitwarden/103/resources/app.asar/main.js:55950:46)
    at Generator.next (<anonymous>)
    at fulfilled (/snap/bitwarden/103/resources/app.asar/main.js:55838:58)

(bitwarden:71453): Gtk-WARNING **: 10:24:18.664: Theme parsing error: gtk.css:1422:23: 'font-feature-settings' is not a valid property name

(bitwarden:71453): Gtk-WARNING **: 10:24:18.667: Theme parsing error: gtk.css:3308:25: 'font-feature-settings' is not a valid property name

(bitwarden:71453): Gtk-WARNING **: 10:24:18.668: Theme parsing error: gtk.css:3770:23: 'font-feature-settings' is not a valid property name

```
</details>

**Comment by flosoft** [comment]
Any update on this? This still seems to be broken on (K)Ubuntu 24.04 LTS.

**Comment by klondikemarlen** [comment]
Seems to be working for me again on Ubuntu 24.04.1 LTS, with latests updates. I'm not sure when it got fixed though, since I don't use the desktop app very often, and I also re-installed my OS recently.

**Comment by timrichardson** [comment]
I have this problem in ubuntu 24.04, when trying to attach a file to an entry

**Comment by s1shed** [comment]
> I have this problem in ubuntu 24.04, when trying to attach a file to an entry

I see this in Debian Sid as well, plus the squares in the about window.

**Comment by timrichardson** [comment]
Just an update:  The most recent snap I tried (last week) had font rendering problems in the About dialog, but not in general. It shows there are still some font problems.

When using the AppImage, I have no problems.
There are a few similar comments here. 

If you font rendering problems with the snap, try the AppImage. 
Note: even in 24.10, I continue to successfully use this helper for AppImages: https://www.omgubuntu.co.uk/2022/10/appimagelauncher-install-on-ubuntu
