### ISSUE TITLE
Can't open Bitwarden desktop client after system update. Segmentation fault.

### ISSUE THREAD

**Issue by Gochkin** [bitwarden/clients#2678]
### Steps To Reproduce

Just performed system update on my Manjaro machine. Bitwarden crashes with errors and segmentation fault.

### Expected Result

Should be launched as before the update.

### Actual Result

The application crashes.

### Additional Context

Output from command line:

```
 ~ bitwarden-desktop
(node:4388) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `electron --trace-deprecation ...` to show where the warning was created)
[4388:0511/121335.706482:ERROR:object_proxy.cc(642)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[4388:0511/121335.706529:ERROR:select_file_dialog_impl_portal.cc(243)] Failed to read portal version property
[4388:0511/121335.719954:ERROR:cursor_loader.cc(114)] Failed to load a platform cursor of type kNull
[4422:0100/000000.740131:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is egl, ANGLE is
[1]    4388 segmentation fault (core dumped)  bitwarden-desktop
[4422:0100/000000.130626:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.

```

Happy to add any aditional information if needed.

### Operating System

Linux

### Operating System Version

Kernel: 5.17.6-1-MANJARO  Distro: Manjaro Linux

### Installation method

Other

### Build Version

1.33.0

**Comment by sv-atoslav** [comment]
I have similar problem
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy
# snap list | head -n 2
Name                       Version                     Rev    Tracking         Publisher     Notes
bitwarden                  1.33.0                      66     latest/stable    bitwarden✓    -
$ bitwarden
(node:7873) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ElectronStore.Conf._deserialize (/snap/bitwarden/66/resources/app.asar/main.js:6753:43)
    at ElectronStore.get store [as store] (/snap/bitwarden/66/resources/app.asar/main.js:6964:43)
    at new Conf (/snap/bitwarden/66/resources/app.asar/main.js:6817:32)
    at new ElectronStore (/snap/bitwarden/66/resources/app.asar/main.js:16409:3)
    at new ElectronStorageService (/snap/bitwarden/66/resources/app.asar/main.js:52793:22)
    at new Main (/snap/bitwarden/66/resources/app.asar/main.js:55479:31)
    at Object.78417 (/snap/bitwarden/66/resources/app.asar/main.js:50228:18)
    at __webpack_require__ (/snap/bitwarden/66/resources/app.asar/main.js:57323:42)
    at /snap/bitwarden/66/resources/app.asar/main.js:57379:37
(bitwarden:7873): Gtk-WARNING **: 11:56:30.505: Theme parsing error: gtk.css:1413:23: 'font-feature-settings' is not a valid property name
(bitwarden:7873): Gtk-WARNING **: 11:56:30.510: Theme parsing error: gtk.css:3286:25: 'font-feature-settings' is not a valid property name
(bitwarden:7873): Gtk-WARNING **: 11:56:30.511: Theme parsing error: gtk.css:3748:23: 'font-feature-settings' is not a valid property name
/usr/share/libdrm/amdgpu.ids: No such file or directory
[7951:0523/115630.680970:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
$ bitwarden  --trace-deprecation
(node:8983) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ElectronStore.Conf._deserialize (/snap/bitwarden/66/resources/app.asar/main.js:6753:43)
    at ElectronStore.get store [as store] (/snap/bitwarden/66/resources/app.asar/main.js:6964:43)
    at new Conf (/snap/bitwarden/66/resources/app.asar/main.js:6817:32)
    at new ElectronStore (/snap/bitwarden/66/resources/app.asar/main.js:16409:3)
    at new ElectronStorageService (/snap/bitwarden/66/resources/app.asar/main.js:52793:22)
    at new Main (/snap/bitwarden/66/resources/app.asar/main.js:55479:31)
    at Object.78417 (/snap/bitwarden/66/resources/app.asar/main.js:50228:18)
    at __webpack_require__ (/snap/bitwarden/66/resources/app.asar/main.js:57323:42)
    at /snap/bitwarden/66/resources/app.asar/main.js:57379:37
(bitwarden:8983): Gtk-WARNING **: 12:01:03.331: Theme parsing error: gtk.css:1413:23: 'font-feature-settings' is not a valid property name
(bitwarden:8983): Gtk-WARNING **: 12:01:03.336: Theme parsing error: gtk.css:3286:25: 'font-feature-settings' is not a valid property name
(bitwarden:8983): Gtk-WARNING **: 12:01:03.337: Theme parsing error: gtk.css:3748:23: 'font-feature-settings' is not a valid property name
/usr/share/libdrm/amdgpu.ids: No such file or directory
[9060:0523/120103.505337:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
```
Screenshot:
![image](https://user-images.githubusercontent.com/28783346/169788883-39be5809-ac35-4997-80f1-653fda2c911a.png)

**Comment by sv-atoslav** [comment]
> I have similar problem
In my case, reinstall app help for me.
```
sudo bash
snap remove bitwarden
snap install bitwarden
```

**Comment by Gochkin** [comment]
@sv-atoslav 
> In my case, reinstall app help for me.

Didn't help in my case. The same issue remains after reinstall.

**Comment by Gochkin** [comment]
Here is the output from command line with `--trace-deprecation`

```
$> electron16 /bin/bitwarden-desktop --trace-deprecation


App threw an error during load
/usr/bin/bitwarden-desktop:2
export ELECTRON_IS_DEV=0
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1038:15)
    at Module._compile (node:internal/modules/cjs/loader:1072:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at loadApplicationPackage (/usr/lib/electron16/resources/default_app.asar/main.js:110:16)
    at Object.<anonymous> (/usr/lib/electron16/resources/default_app.asar/main.js:222:9)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
A JavaScript error occurred in the main process
Uncaught Exception:
/usr/bin/bitwarden-desktop:2
export ELECTRON_IS_DEV=0
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1038:15)
    at Module._compile (node:internal/modules/cjs/loader:1072:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at loadApplicationPackage (/usr/lib/electron16/resources/default_app.asar/main.js:110:16)
    at Object.<anonymous> (/usr/lib/electron16/resources/default_app.asar/main.js:222:9)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
[7956:0526/091421.984008:ERROR:object_proxy.cc(642)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[7956:0526/091421.984147:ERROR:select_file_dialog_impl_portal.cc(243)] Failed to read portal version property
[7990:0526/091422.088151:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is egl, ANGLE is
[7990:0526/091422.106364:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
```

**Comment by Gochkin** [comment]
Ok, I have been probing and researching this problem a little bit lately. First of all I have discoverd that both `electron` and `bitwareden-desktop` binaries are actually just scripts, so the way I was trying to investigate the problem was wrong. So now I have discovered that the problem occur only when Bitwarden is launched with `electron16` with ozone platform enabled and platform set to wayland:
```
$> ELECTRON_IS_DEV=0 /usr/lib/electron16/electron --enable-features=UseOzonePlatform --ozone-platform=wayland /usr/lib/bitwarden/app.asar

(node:79253) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `electron --trace-deprecation ...` to show where the warning was created)
[79253:0619/124244.567199:ERROR:object_proxy.cc(642)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[79253:0619/124244.567245:ERROR:select_file_dialog_impl_portal.cc(243)] Failed to read portal version property
[79253:0619/124244.587098:ERROR:cursor_loader.cc(114)] Failed to load a platform cursor of type kNull
[79287:0100/000000.602794:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is egl, ANGLE is
[1]    79253 trace trap (core dumped)  ELECTRON_IS_DEV=0 /usr/lib/electron16/electron  --ozone-platform=wayland
[79287:0100/000000.999708:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
```

But running without any specified flags to electron or specifying x11 platform eleminates the issue.

```
$> ELECTRON_IS_DEV=0 /usr/lib/electron16/electron --enable-features=UseOzonePlatform --ozone-platform=x11 /usr/lib/bitwarden/app.asar

(node:79411) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `electron --trace-deprecation ...` to show where the warning was created)
[79411:0619/124719.242420:ERROR:object_proxy.cc(642)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[79411:0619/124719.242457:ERROR:select_file_dialog_impl_portal.cc(243)] Failed to read portal version property
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[79440:0619/124719.323741:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
Server path not specified, so defaulting to ipc.config.socketRoot + ipc.config.appspace + ipc.config.id /tmp/app.bitwarden
starting server on  /tmp/app.bitwarden
starting TLS server false
starting server as Unix || Windows Socket
```

But because bitwarden under x11 results in blurry or bad text, I would prefer to run it under Wayland.
I have tried to launch bitwarden with wayland enabled under electron17 and electron18 without any noticable problems (for now). So this is what I'm going to do for now, until the issue is resolved or until bitwarden is upgraded to electron17 or higher.

```
ELECTRON_IS_DEV=0 /usr/lib/electron17/electron --enable-features=UseOzonePlatform --ozone-platform=wayland /usr/lib/bitwarden/app.asar
```
