### ISSUE TITLE
Concurrent attachment downloads trigger exceptions, which terminate `bw` with success exit code `0`

### ISSUE THREAD

**Issue by Alexander-Shukaev** [bitwarden/clients#2731]
## Describe the Bug

Concurrent attachment downloads trigger exceptions, which terminate `bw` with success exit code `0`.

## Steps To Reproduce

1.  Try to concurrently download multiple attachments, e.g.

    ```
    bw --session "${BW_SESSION}" get --itemid ... --output ... attachment ... && echo success || echo failure
    ```
2.  Wait for exception to occur (maybe try several times as this is sporadic).

## Expected Result

1.  No exception and robust successful handling at the very most.
2.  Proper non-zero failure exit code signalling the error and no half-downloaded attachment files or any other side-effects/leftovers at the very least.

## Actual Result

```
(node:1201755) UnhandledPromiseRejectionWarning: FetchError: request to https://bitwardenxx5keu3w.blob.core.windows.net/attachments-v2/.../...?sv=2019-02-02&sr=b&sig=...&se=2022-01-07T20%3A56%3A21Z&sp=r failed, reason: connect ETIMEDOUT 52.239.153.36:443
    at ClientRequest.<anonymous> (/snapshot/cli-1.20.0/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:376:20)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:376:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `bw --trace-warnings ...` to show where the warning was created)
(node:1201755) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1201755) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
success
```

## Environment

- Operating system: Linux
- Shell: `bash`
- Build Version (run `bw --version`): 1.20.0

**Comment by closebot-bw** [comment]
⚠️ **Stale Issue Notice**

This issue has been automatically marked as stale due to inactivity. It will be closed in **2 weeks** (October 15, 2025) if no further activity occurs.

If this issue is still relevant and you would like to keep it open, please:
- Comment on this issue to show continued interest
- Provide any additional information or updates
- Confirm that the issue still exists in the latest version

Thank you for your contribution to this project! 🙏

**Comment by closebot-bw** [comment]
🔒 **Issue Closed Due to Inactivity**

This issue has been automatically closed due to lack of activity for an extended period. We periodically review and close inactive issues to help maintain our issue tracker and focus on current priorities.

**If this issue is still relevant:**
- Please create a new issue with updated information
- Include steps to reproduce the problem if it's a bug report
- Mention if this issue still occurs in the latest version

Thank you for your contribution to this project. Your feedback helps us improve! 🙏
