### ISSUE TITLE
`bw update` does not handle DNS resolution failure gracefully

### ISSUE THREAD

**Issue by ggiesen** [bitwarden/clients#2738]
## Describe the Bug

When running `bw update --response` but DNS resolution is broken, unhandled exceptions are spewed on the console:

```
$ bw update --response
(node:3125580) UnhandledPromiseRejectionWarning: FetchError: request to https://api.github.com/repos/bitwarden/cli/releases/latest failed, reason: getaddrinfo ENOTFOUND api.github.com api.github.com:443
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/@bitwarden/cli/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:3125580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3125580) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

instead of sending a json failure response

## Steps To Reproduce

1. Break DNS resolution by commenting out nameservers in /etc/resolv.conf
2. Run `bw update --response`

## Expected Result

A proper JSON response with some sort of failure message. Something like:

`{"success":false,"data":{"noColor":true,"object":"message","title":"Unable to check for updates.","message":"Unable to resolve api.github.com"}}`

## Actual Result
```
$ bw update --response
(node:3125580) UnhandledPromiseRejectionWarning: FetchError: request to https://api.github.com/repos/bitwarden/cli/releases/latest failed, reason: getaddrinfo ENOTFOUND api.github.com api.github.com:443
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/@bitwarden/cli/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:3125580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3125580) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Environment

- Operating system: CentOS 8.2.2004
- Shell: bash
- Build Version (run `bw --version`): 1.16.0

**Comment by closebot-bw** [comment]
⚠️ **Stale Issue Notice**

This issue has been automatically marked as stale due to inactivity. It will be closed in **2 weeks** (October 15, 2025) if no further activity occurs.

If this issue is still relevant and you would like to keep it open, please:
- Comment on this issue to show continued interest
- Provide any additional information or updates
- Confirm that the issue still exists in the latest version

Thank you for your contribution to this project! 🙏

**Comment by closebot-bw** [comment]
🔒 **Issue Closed Due to Inactivity**

This issue has been automatically closed due to lack of activity for an extended period. We periodically review and close inactive issues to help maintain our issue tracker and focus on current priorities.

**If this issue is still relevant:**
- Please create a new issue with updated information
- Include steps to reproduce the problem if it's a bug report
- Mention if this issue still occurs in the latest version

Thank you for your contribution to this project. Your feedback helps us improve! 🙏
