### ISSUE TITLE
vault.bitwarden.com won't load

### ISSUE THREAD

**Issue by JakeLane** [bitwarden/clients#2781]
### Steps To Reproduce

1. Go to 'https://vault.bitwarden.com/'
2. Observe loading page

### Expected Result

Page to load

### Actual Result

Loading forever with the following error
```
core.umd.jss:6836 ERROR SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at a.get (htmlStorage.service.tss:26:24)
    at o.get (stateMigration.service.tss:496:32)
    at o.<anonymous> (stateMigration.service.tss:207:33)
    at Generator.next (<anonymous>)
    at a (main.a4620985f58c51d420bd.js:1:983576)
    at t.invoke (zone.jss:400:30)
    at Object.onInvoke (core.umd.jss:29384:37)
    at t.invoke (zone.jss:399:56)
    at e.run (zone.jss:160:47)
Lo @ core.umd.jss:6836
zone.jss:1102 Unhandled Promise rejection: Unexpected token o in JSON at position 1 ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at a.get (htmlStorage.service.tss:26:24)
    at o.get (stateMigration.service.tss:496:32)
    at o.<anonymous> (stateMigration.service.tss:207:33)
    at Generator.next (<anonymous>)
    at a (main.a4620985f58c51d420bd.js:1:983576)
    at t.invoke (zone.jss:400:30)
    at Object.onInvoke (core.umd.jss:29384:37)
    at t.invoke (zone.jss:399:56)
    at e.run (zone.jss:160:47) SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at a.get (https://vault.bitwarden.com/app/main.a4620985f58c51d420bd.js:1:2873213)
    at o.get (https://vault.bitwarden.com/app/main.a4620985f58c51d420bd.js:1:997323)
    at o.<anonymous> (https://vault.bitwarden.com/app/main.a4620985f58c51d420bd.js:1:988869)
    at Generator.next (<anonymous>)
    at a (https://vault.bitwarden.com/app/main.a4620985f58c51d420bd.js:1:983576)
    at t.invoke (https://vault.bitwarden.com/app/polyfills.d92dcdb0a986e964fec8.js:2:218067)
    at Object.onInvoke (https://vault.bitwarden.com/app/vendor.77b46fff69ec9c91f4e5.js:2:577908)
    at t.invoke (https://vault.bitwarden.com/app/polyfills.d92dcdb0a986e964fec8.js:2:218007)
    at e.run (https://vault.bitwarden.com/app/polyfills.d92dcdb0a986e964fec8.js:2:213163)
```

### Additional Context

Problem appears to be that the result was not a JSON object (something like `none` instead) so the JSON parse will never succeed.

### Operating System

macOS

### Web Browser

Chrome

### Build Version

Not shown

**Comment by atjbramley** [comment]
Hi @JakeLane ,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration, or perhaps our site was down at the time.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
