### ISSUE TITLE
`bw --version` should ignore config file

### ISSUE THREAD

**Issue by mmahmoudian** [bitwarden/clients#3667]
### Steps To Reproduce

1. remove existing config `rm -rf ~/.config/Bitwarden CLI`
2. `bw --version`
3. observe the result

### Expected Result

I expect to see the version regardless of me having the config folder or not. This is because `--version` should be agnostic to any config, and it should not waste time on checking/creating filers and folder, nor it should clutter users's folders when it is unnecessary.

### Actual Result

```console
❯  ./bw --version
Could not find dir, "/home/mehrad/.config/Bitwarden CLI"; creating it instead.
Could not find data file, "/home/mehrad/.config/Bitwarden CLI/data.json"; creating it instead.
2022.9.0
```

### Screenshots or Videos

-- not applicable --

### Additional Context

In other words, all `--version` should do is to return the version number. it literally not do anything else other than returning that string. Any process extra is totally unnecessary, plus it would make the scripting way more challenging as `bw` does file and folder manipulation behind the scene without asking the user's consent/approval. 

I literally just downloaded the binary for the first time ever and the first thing I did was to check the version through `bw --version` and to my surprise I got the messages that I posted above. Of course, I'm writing my own script to update the `bw` automatically and I want to keep one older version as a fallback, so the creation of files and folder just for checking the version seems weird.

P.s: thanks for the software, I have enjoyed the GUI and browser extension, and so far they have proven to be reliable and stable. Cheers! 🍻 

### Operating System

Linux

### Operating System Version

Manjaro Linux 22.0.0

### Shell

Zsh

### Build Version

2022.9.0

**Comment by mmahmoudian** [comment]
@tangowithfoxtrot I don't understand why this is closed. Is it transfered to forum? Am I expected to create it there? I in general hate such blunt bot actions, and this doesn't make any sense to me. It is your software and you are entitled to do whatever you see fit, but this bot explanation is not constructive.

**Comment by tangowithfoxtrot** [comment]
Apologies, @mmahmoudian.

Closing the thread was intentional, but I could have offered an explanation.

I have confirmed that this behavior _is_ reproducible on my end, but after running this by some other members of the team, we think this would be better handled as a feature request. Please submit this to our [Community Forum](https://community.bitwarden.com/c/feature-requests) so that we can handle this accordingly.

**Comment by mmahmoudian** [comment]
> we think this would be better handled as a feature request

Is anyone who thinks that printing out version number is config-dependent? If that's so, would you care to elaborate for the sake of transparency with the community?

I for one can not comprehend how to pitch a bug report to sound like a feature request.

**Comment by marcw** [comment]
I can confirm this should be reopened as it prevents investigation in case of a bug. 

In that case, I can't get the version number of `bw` while I have this bug...

```
❯ bw --version
Could not find dir, "/home/foobar/.config/Bitwarden CLI"; creating it instead.
Could not find dir, "/home/foobar/.config/Bitwarden CLI"; creating it instead.
node:fs:1349
  handleErrorFromBinding(ctx);
  ^

Error: EEXIST: file already exists, mkdir '/home/foobar/.config/Bitwarden CLI'
    at Object.mkdirSync (node:fs:1349:3)
    at Object.mkdirSync (pkg/prelude/bootstrap.js:1642:33)
    at /snapshot/clients/apps/cli/build/bw.js:31168:45
    at Array.reduce (<anonymous>)
    at Function.mkdirpSync (/snapshot/clients/apps/cli/build/bw.js:31165:60)
    at LowdbStorageService.<anonymous> (/snapshot/clients/apps/cli/build/bw.js:36676:31)
    at Generator.next (<anonymous>)
    at /snapshot/clients/apps/cli/build/bw.js:36640:71
    at new Promise (<anonymous>)
    at /snapshot/clients/apps/cli/build/bw.js:36636:12 {
  errno: -17,
  syscall: 'mkdir',
  code: 'EEXIST',
  path: '/home/foobar/.config/Bitwarden CLI'
}
```

**Comment by closebot-bw** [comment]
⚠️ **Stale Issue Notice**

This issue has been automatically marked as stale due to inactivity. It will be closed in **2 weeks** (October 15, 2025) if no further activity occurs.

If this issue is still relevant and you would like to keep it open, please:
- Comment on this issue to show continued interest
- Provide any additional information or updates
- Confirm that the issue still exists in the latest version

Thank you for your contribution to this project! 🙏

**Comment by mmahmoudian** [comment]
Not stale. Also please get rid of these nonsense bots. It is not that hard to write a counter bot to always comment something when the issue is marked as stale. Stale bots are unrespectful, and I'm a paid customer of Bitwarden!
