### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'get')

### ISSUE THREAD

**Issue by desdic** [bitwarden/clients#4174]
### Steps To Reproduce

```sh
# bw list items
/usr/lib/node_modules/@bitwarden/cli/build/bw.js:4800
            const decCiphers = (yield Promise.all(Object.entries(grouped).map(([orgId, groupedCiphers]) => { var _a; return this.encryptService.decryptItems(groupedCiphers, (_a = orgKeys.get(orgId)) !== null && _a !== void 0 ? _a : userKey); })))
                                                                                                                                                                                           ^

TypeError: Cannot read properties of null (reading 'get')
    at /usr/lib/node_modules/@bitwarden/cli/build/bw.js:4800:188
    at Array.map (<anonymous>)
    at CipherService.<anonymous> (/usr/lib/node_modules/@bitwarden/cli/build/bw.js:4800:75)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/@bitwarden/cli/build/bw.js:4510:58)
```

### Expected Result

a list of items

### Actual Result

```sh
/usr/lib/node_modules/@bitwarden/cli/build/bw.js:4800
            const decCiphers = (yield Promise.all(Object.entries(grouped).map(([orgId, groupedCiphers]) => { var _a; return this.encryptService.decryptItems(groupedCiphers, (_a = orgKeys.get(orgId)) !== null && _a !== void 0 ? _a : userKey); })))
                                                                                                                                                                                           ^

TypeError: Cannot read properties of null (reading 'get')
    at /usr/lib/node_modules/@bitwarden/cli/build/bw.js:4800:188
    at Array.map (<anonymous>)
    at CipherService.<anonymous> (/usr/lib/node_modules/@bitwarden/cli/build/bw.js:4800:75)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/@bitwarden/cli/build/bw.js:4510:58)
```

### Additional Context

bitwarden-cli 2022.11.0-1

### Operating System

Linux

### Operating System Version

arch

### Shell

Zsh

### Build Version

2022.11.0-1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Topic was also opened on our [Community Forums](https://community.bitwarden.com/t/bw-cli-can-no-longer-list/46707/2) and a sync/logout-login cylcle resolved the issue.

Closing this now.
