### ISSUE TITLE
Bitwarden not launching

### ISSUE THREAD

**Issue by fseneque** [bitwarden/clients#4321]
### Steps To Reproduce

I have installed bitwarden client from snap on Ubuntu 22.04. It was working fine and then one day it stopped launching.

Here is the log found in the syslog :+1: 

````
Dec 26 20:54:34 latitude-7490 bitwarden_bitwarden.desktop[4326]: (node:4326) DeprecationWarning: file property is deprecated and will be removed in v5.
Dec 26 20:54:34 latitude-7490 bitwarden_bitwarden.desktop[4326]: (Use `bitwarden --trace-deprecation ...` to show where the warning was created)
Dec 26 20:54:34 latitude-7490 bitwarden_bitwarden.desktop[4326]: #033[1m#033[47m#033[31mA JavaScript error occurred in the main process
Dec 26 20:54:34 latitude-7490 bitwarden_bitwarden.desktop[4326]: #033[30mUncaught Exception:
Dec 26 20:54:34 latitude-7490 bitwarden_bitwarden.desktop[4326]: SyntaxError: Unexpected end of JSON input
Dec 26 20:54:34 latitude-7490 bitwarden_bitwarden.desktop[4326]:     at JSON.parse (<anonymous>)
Dec 26 20:54:34 latitude-7490 bitwarden_bitwarden.desktop[4326]:     at Conf._deserialize (/snap/bitwarden/80/resources/app.asar/main.js:6643:43)
Dec 26 20:54:34 latitude-7490 bitwarden_bitwarden.desktop[4326]:     at get store [as store] (/snap/bitwarden/80/resources/app.asar/main.js:6854:43)
Dec 26 20:54:34 latitude-7490 bitwarden_bitwarden.desktop[4326]:     at new Conf (/snap/bitwarden/80/resources/app.asar/main.js:6707:32)
Dec 26 20:54:34 latitude-7490 bitwarden_bitwarden.desktop[4326]:     at new ElectronStore (/snap/bitwarden/80/resources/app.asar/main.js:10432:3)
Dec 26 20:54:34 latitude-7490 bitwarden_bitwarden.desktop[4326]:     at new ElectronStorageService (/snap/bitwarden/80/resources/app.asar/main.js:49542:22)
Dec 26 20:54:34 latitude-7490 bitwarden_bitwarden.desktop[4326]:     at new Main (/snap/bitwarden/80/resources/app.asar/main.js:52372:31)
Dec 26 20:54:34 latitude-7490 bitwarden_bitwarden.desktop[4326]:     at 99726 (/snap/bitwarden/80/resources/app.asar/main.js:43754:18)
Dec 26 20:54:34 latitude-7490 bitwarden_bitwarden.desktop[4326]:     at __webpack_require__ (/snap/bitwarden/80/resources/app.asar/main.js:54772:42)
Dec 26 20:54:34 latitude-7490 bitwarden_bitwarden.desktop[4326]:     at /snap/bitwarden/80/resources/app.asar/main.js:54828:37#033[0m
Dec 26 20:54:34 latitude-7490 bitwarden[4326]: Theme parsing error: gtk.css:1413:23: 'font-feature-settings' is not a valid property name
Dec 26 20:54:34 latitude-7490 bitwarden[4326]: Theme parsing error: gtk.css:3286:25: 'font-feature-settings' is not a valid property name
Dec 26 20:54:34 latitude-7490 bitwarden[4326]: Theme parsing error: gtk.css:3748:23: 'font-feature-settings' is not a valid property name
````

### Expected Result

To launch

### Actual Result

Not Launching

### Operating System

Linux

### Operating System Version

Ubuntu 22.04 LTS

### Installation method

Snap

### Build Version

2022.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi @fseneque 

Is seems like the program is failing to parse a config file. Would you mind trying to purge the package (https://askubuntu.com/questions/1130791/how-to-uninstall-a-package-installed-from-snapcraft), install it again, and let us know how it goes?

**Comment by fseneque** [comment]
Hi!

Yes it worked! Thanks I don't know how this happened...
