### ISSUE TITLE
MacOs desktop app fails to fetch - ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by kulho** [bitwarden/clients#4724]
### Steps To Reproduce

I am using a self-hosted server with nginx proxy manager - for ssl and pihole - for local domain name. When I use App Store on mac to download the app I get an error. When I use [standard installer](https://vault.bitwarden.com/download/?app=desktop&platform=macos&variant=dmg) from https://bitwarden.com/download/ it works correctly.

I would use the standard installer, but it tells me I need to install the app via App Store to use biometrics on my extension...

### Expected Result

For the app downloaded via appstore to work properly, or the standard installer to support biometrics for extensions.

### Actual Result

On the App Store app I get these:
Failed to load resource: net::ERR_NAME_NOT_RESOLVED
TypeError: Failed to fetch
    at zone.js:1586:40
    at O.i.<computed> (zone.js:1022:28)
    at useClass.nativeFetch (api.service.ts:1810:12)
    at useClass.<anonymous> (api.service.ts:1806:17)
    at Generator.next (<anonymous>)
    at r (main.js:1:667226)
    at e.invoke (zone.js:409:30)
    at Object.onInvoke (ng_zone.ts:418:29)
    at e.invoke (zone.js:408:56)
    at t.run (zone.js:169:47)
Received API exception: TypeError: Failed to fetch

### Screenshots or Videos

<img width="548" alt="Screenshot 2023-02-10 at 23 41 52" src="https://user-images.githubusercontent.com/38033987/218214614-ee60bf90-92aa-43e7-95a5-f90e9dd50ed7.png">

### Additional Context

From pihole logs, it appears as if the App Store version is somehow bypassing the pihole local DNS and trying to query google DNS for my local domain name. The other app installed via the standard installer does not do this and works properly (unless I want to enable biometrics for my extension).

### Operating System

macOS

### Operating System Version

13.1 (22C65)

### Installation method

Direct Download (from bitwarden.com), Mac App Store

### Build Version

Version 2023.1.1 Shell 21.3.1 Renderer 106.0.5249.181 Node 16.16.0 Architecture arm64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @kulho,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thank you.

**Comment by kulho** [comment]
Hello @SergeantConfused 

I will gladly assist with any logs/info necessary. Though, at this point, I am not sure what should I provide.

Thanks.

**Comment by closebot-bw** [comment]
⚠️ **Stale Issue Notice**

This issue has been automatically marked as stale due to inactivity. It will be closed in **2 weeks** (October 15, 2025) if no further activity occurs.

If this issue is still relevant and you would like to keep it open, please:
- Comment on this issue to show continued interest
- Provide any additional information or updates
- Confirm that the issue still exists in the latest version

Thank you for your contribution to this project! 🙏

**Comment by closebot-bw** [comment]
🔒 **Issue Closed Due to Inactivity**

This issue has been automatically closed due to lack of activity for an extended period. We periodically review and close inactive issues to help maintain our issue tracker and focus on current priorities.

**If this issue is still relevant:**
- Please create a new issue with updated information
- Include steps to reproduce the problem if it's a bug report
- Mention if this issue still occurs in the latest version

Thank you for your contribution to this project. Your feedback helps us improve! 🙏
