### ISSUE TITLE
Console output on Linux Debian sid

### ISSUE THREAD

**Issue by jidanni** [bitwarden/clients#4873]
### Steps To Reproduce

$ bitwarden

Click on the vault icon in the lower left corner.

### Expected Result

The console should be silent.

### Actual Result

```
$ bitwarden 
(node:22339) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
[22339:0226/162114.532555:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.login1.Manager.Inhibit: object_path= /org/freedesktop/login1: org.freedesktop.DBus.Error.AccessDenied: Permission denied
(node:22339) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setContextMenu')
    at TrayMain.updateContextMenu (/opt/Bitwarden/resources/app.asar/main.js:51319:23)
    at MessagingMain.updateTrayMenu (/opt/Bitwarden/resources/app.asar/main.js:50820:28)
    at MessagingMain.onMessage (/opt/Bitwarden/resources/app.asar/main.js:50746:22)
    at MessagingMain.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:50737:151)
    at Generator.next (<anonymous>)
    at /opt/Bitwarden/resources/app.asar/main.js:50716:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/opt/Bitwarden/resources/app.asar/main.js:50712:12)
    at IpcMainImpl.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:50737:79)
    at IpcMainImpl.emit (node:events:527:28)
(node:22339) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```
And upon exit:
```
$ 16:36:09.144 › TypeError: Object has been destroyed
    at WindowMain.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:51701:36)
    at Generator.next (<anonymous>)
    at /opt/Bitwarden/resources/app.asar/main.js:51508:71
    at new Promise (<anonymous>)
    at window_main_awaiter (/opt/Bitwarden/resources/app.asar/main.js:51504:12)
    at WindowMain.updateWindowState (/opt/Bitwarden/resources/app.asar/main.js:51696:16)
    at WindowMain.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:51649:28)
    at Generator.next (<anonymous>)
    at /opt/Bitwarden/resources/app.asar/main.js:51508:71
    at new Promise (<anonymous>)
```

### Additional Context

Sure, the Desktop app runs fine, but someday you might want to fix what is causing all those messages.

### Operating System

Linux

### Operating System Version

Debian sid

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2023.2.0 Shell 21.3.1 Renderer 106.0.5249.181 Node 16.16.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jidanni** [comment]
No AppImage. All I know is I used
`dpkg -i Bitwarden-2023.2.0-amd64.deb` back when I installed it,
and `reportbug --template bitwarden` says
```
Kernel: Linux 6.1.0-5-amd64 (SMP w/2 CPU threads; PREEMPT)
Locale: LANG=zh_TW.UTF-8, LC_CTYPE=zh_TW.UTF-8 (charmap=UTF-8), LANGUAGE=en_US:en
Shell: /bin/sh linked to /usr/bin/dash
Init: systemd (via /run/systemd/system)

Versions of packages bitwarden depends on:
ii  libnotify4     0.8.1-1
ii  libnss3        2:3.87.1-1
ii  libsecret-1-0  0.20.5-3
ii  libxss1        1:1.2.3-1
ii  libxtst6       2:1.2.3-1.1

Versions of packages bitwarden recommends:
pn  libappindicator3-1  <none>

bitwarden suggests no packages.
```

**Comment by atjbramley** [comment]
Hi @jidanni ,

Thank you for your report! 

I was able to reproduce this issue, and have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!
