### ISSUE TITLE
wrong type number for item.securenote

### ISSUE THREAD

**Issue by cjvirtucio87** [bitwarden/clients#5145]
### Steps To Reproduce

Run the following command:

```console
bw get template 'item.securenote'
```

### Expected Result

Prints a JSON object with type set to [SecureNote's type](https://github.com/bitwarden/clients/blob/7f34abfeadb9620e85c72324f6862c76b88af249/libs/common/src/vault/enums/cipher-type.ts#L3):

```json
{
  "type": 2
}
```

### Actual Result

Prints a JSON object with what [appears to be SecureNote's type](https://github.com/bitwarden/clients/blob/7f34abfeadb9620e85c72324f6862c76b88af249/libs/common/src/enums/secureNoteType.ts#L2), but isn't what the CLI's `create item` subcommand expects:

```json
{
  "type": 0
}
```

resulting in the an error when I attempt to use that:

```
cjvirtucio@LAPTOP-7SS66536:~/git/bitwarden/clients$ cat /tmp/foo.json
{
  "type": 0,
  "name": "my note",
  "notes": "some note",
  "favorite": false,
  "secureNote": "a secret"
}
cjvirtucio@LAPTOP-7SS66536:~/git/bitwarden/clients$ base64 -w 0 < /tmp/foo.json | bw create item
/snapshot/clients/apps/cli/build/bw.js:29973
                    throw new Error("Unknown cipher type.");
                          ^

Error: Unknown cipher type.
    at CipherService.<anonymous> (/snapshot/clients/apps/cli/build/bw.js:29973:27)
    at Generator.next (<anonymous>)
    at /snapshot/clients/apps/cli/build/bw.js:28912:71
    at new Promise (<anonymous>)
    at /snapshot/clients/apps/cli/build/bw.js:28908:12
    at CipherService.encryptCipherData (/snapshot/clients/apps/cli/build/bw.js:29911:16)
    at CipherService.<anonymous> (/snapshot/clients/apps/cli/build/bw.js:29053:22)
    at Generator.next (<anonymous>)
    at /snapshot/clients/apps/cli/build/bw.js:28912:71
    at new Promise (<anonymous>)
cjvirtucio@LAPTOP-7SS66536:~/git/bitwarden/clients$
```

### Operating System

Linux

### Operating System Version

Ubuntu 22.04

### Shell

Bash

### Build Version

2023.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cjvirtucio87** [comment]
interestingly, when I try to retrieve my note, I only get an object with `"type": 0` in it, and not my note:

```
cjvirtucio@LAPTOP-7SS66536:~/git/bitwarden/clients$ cat /tmp/foo.json
{
  "object": "item",
  "organizationId": null,
  "folderId": "<omitted>",
  "type": 2,
  "reprompt": 0,
  "name": "test",
  "notes": "test",
  "favorite": false,
  "secureNote": "test"
}
cjvirtucio@LAPTOP-7SS66536:~/git/bitwarden/clients$ base64 -w 0 < /tmp/foo.json | bw create item &>/dev/null
cjvirtucio@LAPTOP-7SS66536:~/git/bitwarden/clients$ bw get item 'test' | jq '.'
{
  "object": "item",
  "id": "<omitted>",
  "organizationId": null,
  "folderId": "<omitted>",
  "type": 2,
  "reprompt": 0,
  "name": "test",
  "notes": "test",
  "favorite": false,
  "secureNote": {
    "type": 0
  },
  "revisionDate": "2023-04-02T11:14:11.813Z",
  "creationDate": "2023-04-02T11:14:11.813Z",
  "deletedDate": null
}
cjvirtucio@LAPTOP-7SS66536:~/git/bitwarden/clients$
```
