### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: (intermediate value).flat is not a function

### ISSUE THREAD

**Issue by Tailslide** [bitwarden/clients#5509]
### Steps To Reproduce

1. Install bitwarden 2023.4.0 on windows 11 WSL2 ubuntu LTS 20.04.6
2. Put BW_CLIENTID, BW_CLIENTSECRET, BW_PASSWORD as environment variable
3. Run the following lines:

```bash
 SESSION_KEY=$(bw unlock --passwordenv BW_PASSWORD --raw)
 bw list items --session $SESSION_KEY
```

### Expected Result

A list of items.

### Actual Result

```
(node:13420) UnhandledPromiseRejectionWarning: TypeError: (intermediate value).flat is not a function
    at CipherService.<anonymous> (/usr/local/lib/node_modules/@bitwarden/cli/build/bw.js:24155:18)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/@bitwarden/cli/build/bw.js:23871:58)
(node:13420) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13420) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Additional Context

Might be unrelated but weirdly it works if I list folders but I just get one item in the list "No Folder" and not the folder that I added.

### Operating System

Linux

### Operating System Version

ubuntu LTS 20.04.6

### Shell

Bash

### Build Version

2023.4.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Tailslide** [comment]
Seems fixed in 2024.1
