### ISSUE TITLE
bitwarden white screen linux opensuse unusable

### ISSUE THREAD

**Issue by shalom938** [bitwarden/clients#5761]
### Steps To Reproduce

this is how bitwarden starts since latest update, unusable.
opensuse tumbleweed.

![image](https://github.com/bitwarden/clients/assets/170266/18122f12-f257-4d7f-90e6-a02110d2465a)

### Expected Result

bitwarden should start ok

### Actual Result

white screen

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/170266/11c9abe1-082f-4da4-af35-84111d17998c)

### Operating System

Linux

### Operating System Version

opensuse

### Web Browser

Brave, Vivaldi

### Build Version

latest

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by shalom938** [comment]
its not possible to close and nothing helps.
what do you guys think i should do?

**Comment by cbbit** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration or corruption of your installation; please try performing a clean reinstall and then try again.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by shalom938** [comment]
It still happens sometimes, it was ok for some weeks but today again when i try to open bitwarden. when it happens the windows is not responding and can't be closed, i see all these processes and need to kill them

shalom@shin-opensuse:~$> ps -ef|grep bitwarden
shalom    2207   399  0 11:55 pts/13   00:00:00 grep --color=auto bitwarden
shalom   32633  3360  0 11:54 ?        00:00:00 bwrap --args 40 bitwarden
shalom   32643 32633  0 11:54 ?        00:00:00 bwrap --args 40 bitwarden
shalom   32644 32643  1 11:54 ?        00:00:01 /app/Bitwarden/bitwarden
shalom   32655 32644  0 11:54 ?        00:00:00 /app/Bitwarden/bitwarden --type=zygote --no-zygote-sandbox
shalom   32660  4171  0 11:54 ?        00:00:00 bwrap --args 41 /app/bin/zypak-helper child - /app/Bitwarden/bitwarden --type=zygote
shalom   32669 32643  0 11:54 ?        00:00:00 bwrap --args 41 /app/bin/zypak-helper child - /app/Bitwarden/bitwarden --type=zygote
shalom   32670 32669  0 11:54 ?        00:00:00 /app/Bitwarden/bitwarden --type=zygote
shalom   32711 32655  0 11:54 ?        00:00:00 /app/Bitwarden/bitwarden --type=gpu-process --enable-crash-reporter=c6919053-54f1-41df-8598-a544f0a6de53,no_channel --user-data-dir=/home/shalom/.var/app/com.bitwarden.desktop/config/Bitwarden --gpu-preferences=WAAAAAAAAAAgAAAIAAAAAAAAAAAAAAAAAABgAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAABAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAIAAAAAAAAAA== --shared-files --field-trial-handle=0,i,5176978529045338349,5522494377088232209,131072 --disable-features=SpareRendererForSitePerProcess
shalom   32717 32644  0 11:54 ?        00:00:00 /app/Bitwarden/bitwarden --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=none --enable-crash-reporter=c6919053-54f1-41df-8598-a544f0a6de53,no_channel --user-data-dir=/home/shalom/.var/app/com.bitwarden.desktop/config/Bitwarden --shared-files=v8_context_snapshot_data:100 --field-trial-handle=0,i,5176978529045338349,5522494377088232209,131072 --disable-features=SpareRendererForSitePerProcess
shalom   32726 32644  1 11:54 ?        00:00:01 /app/Bitwarden/bitwarden --type=renderer --enable-crash-reporter=c6919053-54f1-41df-8598-a544f0a6de53,no_channel --user-data-dir=/home/shalom/.var/app/com.bitwarden.desktop/config/Bitwarden --app-path=/app/Bitwarden/resources/app.asar --no-sandbox --no-zygote --first-renderer-process --lang=en-US --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=4 --time-ticks-at-unix-epoch=-1690306953569984 --launch-time-ticks=54693867204 --shared-files=v8_context_snapshot_data:100 --field-trial-handle=0,i,5176978529045338349,5522494377088232209,131072 --disable-features=SpareRendererForSitePerProcess

**Comment by Findarato** [comment]
Tossing my hat in having the same problem.  I try to login and nothing happens but white screen I am attaching all of the logs I get from running bitwarden directly.

```bash
bitwarden 
(node:115495) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
(node:115495) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'init')
    at BiometricsService.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:47194:55)
    at Generator.next (<anonymous>)
    at /opt/Bitwarden/resources/app.asar/main.js:47160:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/opt/Bitwarden/resources/app.asar/main.js:47156:12)
    at BiometricsService.init (/opt/Bitwarden/resources/app.asar/main.js:47193:16)
    at Main.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:53805:46)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/Bitwarden/resources/app.asar/main.js:53702:58)
(node:115495) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
(node:115495) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading 'null')
    at new Menubar (/opt/Bitwarden/resources/app.asar/main.js:45540:131)
    at MenuMain.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:45594:56)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/Bitwarden/resources/app.asar/main.js:45564:58)
(node:115495) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
```

**Comment by AnhQuanTrl** [comment]
I am having the same problem with @Findarato. Same error log as well.

**Comment by closebot-bw** [comment]
⚠️ **Stale Issue Notice**

This issue has been automatically marked as stale due to inactivity. It will be closed in **2 weeks** (October 15, 2025) if no further activity occurs.

If this issue is still relevant and you would like to keep it open, please:
- Comment on this issue to show continued interest
- Provide any additional information or updates
- Confirm that the issue still exists in the latest version

Thank you for your contribution to this project! 🙏

**Comment by closebot-bw** [comment]
🔒 **Issue Closed Due to Inactivity**

This issue has been automatically closed due to lack of activity for an extended period. We periodically review and close inactive issues to help maintain our issue tracker and focus on current priorities.

**If this issue is still relevant:**
- Please create a new issue with updated information
- Include steps to reproduce the problem if it's a bug report
- Mention if this issue still occurs in the latest version

Thank you for your contribution to this project. Your feedback helps us improve! 🙏
