### ISSUE TITLE
npm package cli 2023.7.0 broken on linux arm64

### ISSUE THREAD

**Issue by jheidecker** [bitwarden/clients#5840]
### Steps To Reproduce

Tested on fresh Ubuntu 22.04 ARM64

Working as expected for previous version:
```
# sudo npm i -g @bitwarden/cli@2023.5.0
# bw
Usage: bw [options] [command]...
```

Not working for 2023.7.0
```
# sudo npm i -g @bitwarden/cli (2023.7.0)
# bw
usr/local/lib/node_modules/@bitwarden/cli/node_modules/jsdom/lib/api.js:140
          referrer: req.getHeader("referer") ?? undefined
                                              ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /usr/local/lib/node_modules/@bitwarden/cli/build/bw.js:97:40
    at /usr/local/lib/node_modules/@bitwarden/cli/build/bw.js:41427:3
    at Object.<anonymous> (/usr/local/lib/node_modules/@bitwarden/cli/build/bw.js:41429:12)
```

### Expected Result

Working

### Actual Result

Not working

### Additional Context

Building from source seems to function as expected.

### Operating System

Linux

### Operating System Version

Ubuntu 22.04

### Shell

Bash

### Build Version

2023.7.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Hinton** [comment]
Hi @jheidecker,

What version of node.js are you using? The nullish coalescing operator (`??` syntax) should be supported in node 14+, https://node.green/#ES2020-features--nullish-coalescing-operator-----. Anything lower than node 16 are end of life https://github.com/nodejs/release#release-schedule

**Comment by atjbramley** [comment]
Hi @jheidecker ,

I attempted to reproduce your issue and was unable to do so.  Specifically, I:

- installed npm v20 via apt-get on ubuntu 22.04 ARM
- installed bitwarden via npm
- ran bitwarden without difficulty

 I think your error could have its origin in a misconfiguration or corruption of your environment.  @Hinton's comment above may also be of help!

**Comment by jheidecker** [comment]
I s

> Hi @jheidecker ,
> 
> I attempted to reproduce your issue and was unable to do so. Specifically, I:
> 
> * installed npm v20 via apt-get on ubuntu 22.04 ARM
> * installed bitwarden via npm
> * ran bitwarden without difficulty
> 
> I think your error could have its origin in a misconfiguration or corruption of your environment. @Hinton's comment above may also be of help!

looks like it is an npm version issue. How are you installing npm though? I am installing 22.04 ARM64 fresh, then `apt update` then `apt install npm` and here's what I end up with:

```
~$ nodejs --version
v12.22.9
~$ npm --version
8.5.1
```
With this, I get the same broken install.

I did manage a working installation, but **had to update node and npm outside of apt:**

```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```
```
~$ node --version
v18.16.1
~$ npm --version
9.5.1
```
then...
```
# sudo npm i -g @bitwarden/cli
# bw
Usage: bw [options] [command]...
```

I guess the issue is resolved, it's just not obvious in the documentation how users can resolve this if they follow the documentation. In this case, there's not native executable (ARM64,) I cannot use chocolaty (linux) and there is no snap:

```
error: snap "bw" is not available on stable for this architecture (arm64) but
       exists on other architectures (amd64).
```

Installing via npm **appears** to work but users end up with a broken install. Maybe documentation update?

**Comment by atjbramley** [comment]
Hi @jheidecker, 

I installed npm according to their documentation, using the install scripts provided:

https://nodejs.org/en/download/package-manager#debian-and-ubuntu-based-linux-distributions

We use GitHub issues as a place to track bugs and other development related issues, so the issue here will now be closed. 

If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content, and we will be happy to re-open this issue if necessary.
