### ISSUE TITLE
"Failed to fetch" while connecting into self-hosted bitwarden server on Desktop app

### ISSUE THREAD

**Issue by AlexioShow** [bitwarden/clients#5900]
### Steps To Reproduce

1. Open the Desktop app
2. Select region as "self-hosted"
3. Enter your self-host link
4. Enter your username
5. Click on 'Login with master password'
6. Unexcepted error : "Failed to fetch" appears and can't connect to server.

### Expected Result

Can connect into my self-hosted bitwarden server, like the bowser extension.

### Actual Result

Log file keeps looping this  :
```
[2023-07-26 15:26:22.096] [error] TypeError: Failed to fetch
    at file:///C:/Users/algi1/AppData/Local/Programs/Bitwarden/resources/app.asar/app/vendor.js:2:804717
    at i.<computed> (file:///C:/Users/algi1/AppData/Local/Programs/Bitwarden/resources/app.asar/app/vendor.js:2:798641)
    at useClass.nativeFetch (file:///C:/Users/algi1/AppData/Local/Programs/Bitwarden/resources/app.asar/app/main.js:1:498237)
    at useClass.<anonymous> (file:///C:/Users/algi1/AppData/Local/Programs/Bitwarden/resources/app.asar/app/main.js:1:498197)
    at Generator.next (<anonymous>)
    at r (file:///C:/Users/algi1/AppData/Local/Programs/Bitwarden/resources/app.asar/app/main.js:1:346260)
    at c.invoke (file:///C:/Users/algi1/AppData/Local/Programs/Bitwarden/resources/app.asar/app/vendor.js:2:791744)
    at Object.onInvoke (file:///C:/Users/algi1/AppData/Local/Programs/Bitwarden/resources/app.asar/app/vendor.js:2:2169654)
    at c.invoke (file:///C:/Users/algi1/AppData/Local/Programs/Bitwarden/resources/app.asar/app/vendor.js:2:791684)
    at o.run (file:///C:/Users/algi1/AppData/Local/Programs/Bitwarden/resources/app.asar/app/vendor.js:2:787122)
[2023-07-26 15:26:22.099] [error] Received API exception: TypeError: Failed to fetch
```

### Screenshots or Videos

![2023-07-26_15h43_44](https://github.com/bitwarden/clients/assets/103590506/aa55f734-e1b3-44cb-aa1f-2f1860138219)
![2023-07-26_15h45_24](https://github.com/bitwarden/clients/assets/103590506/b4316e17-cfdc-456f-8f05-7829440321b3)

### Operating System

Windows

### Operating System Version

21H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.7.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by AlexioShow** [comment]
Updated to 2023.7.1 this morning -> problem is still present.

**Comment by Adedamola-Aina** [comment]
Hi AlexioShow, 

Thank you for checking up on this. 

Are you receiving the 'failed to fetch' error on all client devices (e.g. extensions, browser connections, mobile extensions etc)?

If you are only receiving this error on one particular client, then we'd want to look at that client in more detail as it could be a misconfiguration.
​
Can you tell me a little more about your instance? What OS is it running on? Did you just configure it?

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

**Comment by LearningAsIGo71** [comment]
I was having the same problem on the Windows desktop app after Bitwarden updated to version 2023.7.1 

Turned out it was my firewall (TinyWall) blocking it. I whitelisted it and no more problems. 

I don't recall having problems like this with previous Bitwarden updates, but perhaps Bitwarden is now using a different port to connect to the Internet?
