### ISSUE TITLE
Unhandled server error when cloning organization card into personal vault

### ISSUE THREAD

**Issue by dallenbaldwin** [bitwarden/clients#6119]
### Steps To Reproduce

1. Create a card 
2. Assign it to an organization and collection
3. Attempt to clone the card, setting the owner to yourself
4. Save

### Expected Result

The cloned card should show up in my personal vault so I can do what I want with it. 

From what I understand, this is the only way to "move" items from organizations back into personal vaults without manually creating them in the personal vault and removing them from the organization. If there is a better/intended way... I'm more than happy to hear about it.

### Actual Result

An error toast shows up in the top left corner of the page. The card is not cloned to my personal vault.

![image](https://github.com/bitwarden/clients/assets/14098845/c86112cd-30c5-4495-b5d6-123ac580401a)

The response in the network tab/console isn't helpful either

### Additional Context

1. This card has custom fields
2. I'm on the free tier
3. I only have one collection in the organization

### Operating System

Windows

### Web Browser

Chrome

### Build Version

2023.8.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by arnoudius** [comment]
I can reproduce this too

**Comment by dallenbaldwin** [comment]
Ha. I need to amend part of my initial post... the toast shows up in the top _right_ corner of the page... directions are hard sometimes I guess 😅

**Comment by SergeantConfused** [comment]
Hi @dallenbaldwin 

Thank you for your report; I am able to reproduce this, and I have flagged it to our engineering team. As a temporary workaround, you can create a new personal vault item and copy and paste the information/credentials to it from the organizational vault item.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thank you again,

**Comment by gordon-vart** [comment]
same issue! Please fix soon. Highly frustrating.

**Comment by johnsons-se** [comment]
Same here but not just for cards, for any item

**Comment by michaelkvance** [comment]
+1 as this is pretty annoying given how difficult it is already to manage folders vs collections matrixed across personal vaults and organizations.

**Comment by IsItSnowingInSpace** [comment]
+1 -- just switched over from LastPass and signed up for the families plan only to find I need to do separate imports for my wife's logins (900+ creds in total, maybe 300 are hers).

**Comment by peter9teufel** [comment]
same here, getting the same error when trying to duplicate entries from my organization to my own vault having the Owner Role for the organization. Updated Bitwarden to the latest official version on 2023-09-11

**Comment by peter9teufel** [comment]
Corresponding error from api logfile in bwdata/logs/api/Api

`[Error] Value cannot be null. (Parameter 'OrganizationId')
System.ArgumentNullException: Value cannot be null. (Parameter 'OrganizationId')
   at Bit.Api.Vault.Models.Request.CipherRequestModel.ToOrganizationCipher() in /home/runner/work/server/server/src/Api/Vault/Models/Request/CipherRequestModel.cs:line 130
   at Bit.Api.Vault.Controllers.CiphersController.PostAdmin(CipherCreateRequestModel model) in /home/runner/work/server/server/src/Api/Vault/Controllers/CiphersController.cs:line 156
   at lambda_method339(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2023-09-19 10:01:51.079 +00:00 [Error] Value cannot be null. (Parameter 'OrganizationId')
System.ArgumentNullException: Value cannot be null. (Parameter 'OrganizationId')
   at Bit.Api.Vault.Models.Request.CipherRequestModel.ToOrganizationCipher() in /home/runner/work/server/server/src/Api/Vault/Models/Request/CipherRequestModel.cs:line 130
   at Bit.Api.Vault.Controllers.CiphersController.PostAdmin(CipherCreateRequestModel model) in /home/runner/work/server/server/src/Api/Vault/Controllers/CiphersController.cs:line 156
   at lambda_method339(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
`

Thx and regards,
Peter

**Comment by SergeantConfused** [comment]
Hello everyone,

This matter was addressed in version 2023.9 and I will now proceed and close this report. If you are still encountering this behaviour, please feel free to get in touch with us (https://bitwarden.com/help/) so we'd have a look and troubleshoot this together.

All the best,
