### ISSUE TITLE
[Windows Client] Search does not work

### ISSUE THREAD

**Issue by slize-it** [bitwarden/clients#6307]
### Steps To Reproduce

Search in the Windows Desktop Client for specific words like "SSH".

### Expected Result

Only results with the word "SSH" will be displayed.

### Actual Result

All vault items are displayed.

### Additional Context

`error_handler.ts:45 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading '_index')
TypeError: Cannot read properties of undefined (reading '_index')
    at T.Index.query (lunr.js:2048:33)
    at Oc.<anonymous> (search.service.ts:154:29)
    at Generator.next (<anonymous>)
    at main.js:1:376448
    at new N (zone.js:1432:21)
    at Cc (main.js:1:376193)
    at Oc.searchCiphers (main.js:1:378338)
    at Yw.<anonymous> (vault-items.component.ts:97:45)
    at Generator.next (<anonymous>)
    at r (main.js:1:1023229)
    at C (zone.js:1214:31)
    at zone.js:1121:17
    at zone.js:1137:33
    at a (main.js:1:1023294)
    at c.invoke (zone.js:375:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at c.invoke (zone.js:374:52)
    at o.run (zone.js:134:43)
    at zone.js:1278:36
    at c.invokeTask (zone.js:409:31)
handleError @ error_handler.ts:45
next @ application_ref.ts:472
e.next @ Subscriber.ts:161
n._next @ Subscriber.ts:119
n.next @ Subscriber.ts:75
(anonymous) @ Subject.ts:68
t.errorContext @ errorContext.ts:29
t.next @ Subject.ts:61
emit @ event_emitter.ts:114
(anonymous) @ ng_zone.ts:450
invoke @ zone.js:375
run @ zone.js:134
runOutsideAngular @ ng_zone.ts:249
onHandleError @ ng_zone.ts:450
handleError @ zone.js:379
runGuarded @ zone.js:147
n.microtaskDrainDone @ zone.js:1075
v @ zone.js:595
invokeTask @ zone.js:494
r.useG.invoke @ zone.js:479
n.args.<computed> @ zone.js:2388
setTimeout (async)
o @ zone.js:2390
scheduleTask @ zone.js:396
onScheduleTask @ zone.js:286
scheduleTask @ zone.js:389
scheduleTask @ zone.js:221
scheduleMacroTask @ zone.js:244
p @ zone.js:686
(anonymous) @ zone.js:2432
i.<computed> @ zone.js:976
(anonymous) @ vault-items.component.ts:67
(anonymous) @ main.js:1
N @ zone.js:1432
_w @ main.js:1
search @ main.js:1
(anonymous) @ vault-items.component.ts:26
e.next @ Subscriber.ts:161
n._next @ Subscriber.ts:119
n.next @ Subscriber.ts:75
(anonymous) @ Subject.ts:68
t.errorContext @ errorContext.ts:29
t.next @ Subject.ts:61
t.next @ BehaviorSubject.ts:37
setSearchText @ search-bar.service.ts:33
(anonymous) @ search.component.ts:27
e.next @ Subscriber.ts:161
n._next @ Subscriber.ts:119
n.next @ Subscriber.ts:75
(anonymous) @ Subject.ts:68
t.errorContext @ errorContext.ts:29
t.next @ Subject.ts:61
emit @ event_emitter.ts:114
updateValueAndValidity @ abstract_model.ts:1058
setValue @ form_control.ts:464
we @ shared.ts:261
(anonymous) @ shared.ts:246
_handleInput @ default_value_accessor.ts:111
(anonymous) @ default_value_accessor.ts:86
Lc @ listener.ts:224
i @ listener.ts:261
(anonymous) @ dom_renderer.ts:76
invokeTask @ zone.js:409
onInvokeTask @ ng_zone.ts:408
invokeTask @ zone.js:408
runTask @ zone.js:178
invokeTask @ zone.js:490
v @ zone.js:1664
k @ zone.js:1695
w @ zone.js:1728`

### Operating System

Windows

### Operating System Version

10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.8.4

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there,

Will you first try to fully reinstall your Bitwarden desktop client?

**Comment by slize-it** [comment]
I have already done that and the problem persists on multiple systems. I use 2 notebooks and a desktop. All have the same problem.

**Comment by Krychaz** [comment]
Hello there, 

Running 2023.8.4 I was not able to replicate this behaviour. Searching for key word and pressing enter resulted in all items with said key word to appear. 

However seeing as there is a clear error within your client. I will leave this issue open for our engineering team to investigate

**Comment by slize-it** [comment]
I think the error is caused by an item in my vault. Depending on the search filter, the crash message may or may not appear. I have over 500 items in my vault and can't tell which one is causing the error.

It also seems that "File -> Sync Vault" fixes the problem until I lock the vault.

**Comment by closebot-bw** [comment]
⚠️ **Stale Issue Notice**

This issue has been automatically marked as stale due to inactivity. It will be closed in **2 weeks** (October 15, 2025) if no further activity occurs.

If this issue is still relevant and you would like to keep it open, please:
- Comment on this issue to show continued interest
- Provide any additional information or updates
- Confirm that the issue still exists in the latest version

Thank you for your contribution to this project! 🙏

**Comment by closebot-bw** [comment]
🔒 **Issue Closed Due to Inactivity**

This issue has been automatically closed due to lack of activity for an extended period. We periodically review and close inactive issues to help maintain our issue tracker and focus on current priorities.

**If this issue is still relevant:**
- Please create a new issue with updated information
- Include steps to reproduce the problem if it's a bug report
- Mention if this issue still occurs in the latest version

Thank you for your contribution to this project. Your feedback helps us improve! 🙏
