### ISSUE TITLE
Bitwarden Unhandled Promise Rejection

### ISSUE THREAD

**Issue by tyqualters** [bitwarden/clients#6316]
### Steps To Reproduce

Open Bitwarden Desktop (Flatpak)

### Expected Result

Login screen displays

### Actual Result

Login screen flashes, then gets stuck in a loading screen without user interaction

### Additional Context

Log from terminal:
```
❯ flatpak run com.bitwarden.desktop      
(node:2) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
Gtk-Message: 16:36:24.281: Failed to load module "canberra-gtk-module"
(node:2) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'init')
    at BiometricsService.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:47195:55)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:47161:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/app/Bitwarden/resources/app.asar/main.js:47157:12)
    at BiometricsService.init (/app/Bitwarden/resources/app.asar/main.js:47194:16)
    at Main.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:53060:46)
    at Generator.next (<anonymous>)
    at fulfilled (/app/Bitwarden/resources/app.asar/main.js:52957:58)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
16:36:24.801 › Error: No password found
16:36:24.802 › Error: No password found
16:36:24.808 › Error: No password found
16:36:24.813 › TypeError: Cannot read properties of undefined (reading 'osSupportsBiometric')
    at BiometricsService.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:47200:55)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:47161:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/app/Bitwarden/resources/app.asar/main.js:47157:12)
    at BiometricsService.osSupportsBiometric (/app/Bitwarden/resources/app.asar/main.js:47199:16)
    at BiometricsService.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:47210:58)
    at Generator.next (<anonymous>)
    at fulfilled (/app/Bitwarden/resources/app.asar/main.js:47158:58)
16:36:24.813 › TypeError: Cannot read properties of undefined (reading 'osSupportsBiometric')
    at BiometricsService.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:47200:55)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:47161:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/app/Bitwarden/resources/app.asar/main.js:47157:12)
    at BiometricsService.osSupportsBiometric (/app/Bitwarden/resources/app.asar/main.js:47199:16)
    at DesktopCredentialStorageListener.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:47384:59)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:47312:71
    at new Promise (<anonymous>)
(node:2) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading 'null')
    at new Menubar (/app/Bitwarden/resources/app.asar/main.js:45541:131)
    at MenuMain.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:45595:56)
    at Generator.next (<anonymous>)
    at fulfilled (/app/Bitwarden/resources/app.asar/main.js:45565:58)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
16:36:25.490 › Error: No password found
(node:2) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading 'null')
    at new Menubar (/app/Bitwarden/resources/app.asar/main.js:45541:131)
    at MenuMain.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:45595:56)
    at Generator.next (<anonymous>)
    at fulfilled (/app/Bitwarden/resources/app.asar/main.js:45565:58)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
16:36:27.764 › Error: No password found
16:36:27.849 › TypeError: Object has been destroyed
    at WindowMain.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:46721:36)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:46495:71
    at new Promise (<anonymous>)
    at window_main_awaiter (/app/Bitwarden/resources/app.asar/main.js:46491:12)
    at WindowMain.updateWindowState (/app/Bitwarden/resources/app.asar/main.js:46716:16)
    at WindowMain.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:46650:28)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:46495:71
    at new Promise (<anonymous>)
```

### Operating System

Linux

### Operating System Version

6.5.2-arch1-1

### Installation method

Other

### Build Version

Version 2023.8.4 Shell 24.8.3 Renderer 112.0.5615.204 Node 18.14.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by flusher998** [comment]
I met the same issue with flatpak and appimage versions, both gave same type of error (but with empty, not logged in case did not show "no password found") 

`flatpak run com.bitwarden.desktop
(node:2) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
Gtk-Message: 15:47:44.879: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:47:44.883: Failed to load module "canberra-gtk-module"
(node:2) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'init')
    at BiometricsService.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:47194:55)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:47160:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/app/Bitwarden/resources/app.asar/main.js:47156:12)
    at BiometricsService.init (/app/Bitwarden/resources/app.asar/main.js:47193:16)
    at Main.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:53804:46)
    at Generator.next (<anonymous>)
    at fulfilled (/app/Bitwarden/resources/app.asar/main.js:53701:58)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
15:47:46.045 › Error: No password found
15:47:46.067 › Error: No password found
15:47:46.120 › Error: No password found
15:47:46.122 › Error: No password found
15:47:46.123 › Error: No password found
15:47:46.144 › Error: No password found
15:47:46.167 › TypeError: Cannot read properties of undefined (reading 'osSupportsBiometric')
    at BiometricsService.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:47199:55)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:47160:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/app/Bitwarden/resources/app.asar/main.js:47156:12)
    at BiometricsService.osSupportsBiometric (/app/Bitwarden/resources/app.asar/main.js:47198:16)
    at BiometricsService.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:47209:58)
    at Generator.next (<anonymous>)
    at fulfilled (/app/Bitwarden/resources/app.asar/main.js:47157:58)
15:47:46.168 › TypeError: Cannot read properties of undefined (reading 'osSupportsBiometric')
    at BiometricsService.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:47199:55)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:47160:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/app/Bitwarden/resources/app.asar/main.js:47156:12)
    at BiometricsService.osSupportsBiometric (/app/Bitwarden/resources/app.asar/main.js:47198:16)
    at DesktopCredentialStorageListener.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:47383:59)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:47311:71
    at new Promise (<anonymous>)
15:47:46.209 › Error: No password found
15:47:46.475 › Error: No password found
15:47:47.129 › Error: No password found
15:47:47.143 › Error: No password found
(node:2) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setContextMenu')
    at TrayMain.updateContextMenu (/app/Bitwarden/resources/app.asar/main.js:46304:23)
    at MessagingMain.updateTrayMenu (/app/Bitwarden/resources/app.asar/main.js:45804:28)
    at MessagingMain.onMessage (/app/Bitwarden/resources/app.asar/main.js:45730:22)
    at MessagingMain.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:45721:151)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:45700:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/app/Bitwarden/resources/app.asar/main.js:45696:12)
    at IpcMainImpl.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:45721:79)
    at IpcMainImpl.emit (node:events:513:28)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
15:47:47.237 › Error: No password found
15:47:47.370 › Error: No password found
15:47:47.469 › Error: No password found
15:47:47.489 › Error: No password found
15:47:47.571 › Error: No password found
15:47:47.571 › Error: No password found
15:47:47.671 › Error: No password found
15:47:47.715 › Error: No password found
(node:2) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setContextMenu')
    at TrayMain.updateContextMenu (/app/Bitwarden/resources/app.asar/main.js:46304:23)
    at MessagingMain.updateTrayMenu (/app/Bitwarden/resources/app.asar/main.js:45804:28)
    at MessagingMain.onMessage (/app/Bitwarden/resources/app.asar/main.js:45730:22)
    at MessagingMain.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:45721:151)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:45700:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/app/Bitwarden/resources/app.asar/main.js:45696:12)
    at IpcMainImpl.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:45721:79)
    at IpcMainImpl.emit (node:events:513:28)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
15:47:47.730 › Error: No password found
15:47:47.730 › Error: No password found
15:47:47.907 › Error: No password found
15:47:49.069 › Error: No password found
15:47:56.058 › Error: No password found
`


and appimage version 

`./Bitwarden-2023.9.0-x86_64.AppImage 
(node:21218) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
(node:21218) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'init')
    at BiometricsService.<anonymous> (/tmp/.mount_Bitwar32BNUm/resources/app.asar/main.js:47194:55)
    at Generator.next (<anonymous>)
    at /tmp/.mount_Bitwar32BNUm/resources/app.asar/main.js:47160:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/tmp/.mount_Bitwar32BNUm/resources/app.asar/main.js:47156:12)
    at BiometricsService.init (/tmp/.mount_Bitwar32BNUm/resources/app.asar/main.js:47193:16)
    at Main.<anonymous> (/tmp/.mount_Bitwar32BNUm/resources/app.asar/main.js:53804:46)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_Bitwar32BNUm/resources/app.asar/main.js:53701:58)
(node:21218) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:21218) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading 'null')
    at new Menubar (/tmp/.mount_Bitwar32BNUm/resources/app.asar/main.js:45540:131)
    at MenuMain.<anonymous> (/tmp/.mount_Bitwar32BNUm/resources/app.asar/main.js:45594:56)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_Bitwar32BNUm/resources/app.asar/main.js:45564:58)
(node:21218) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
16:23:41.880 › Checking for update
16:23:42.723 › Update for version 2023.9.0 is not available (latest version: 2023.9.0, downgrade is disallowed).
[21254:0928/162412.229495:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[21254:0928/162412.232869:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[21254:0928/162412.234139:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
^C16:24:57.906 › TypeError: Object has been destroyed
    at WindowMain.<anonymous> (/tmp/.mount_Bitwar32BNUm/resources/app.asar/main.js:46720:36)
    at Generator.next (<anonymous>)
    at /tmp/.mount_Bitwar32BNUm/resources/app.asar/main.js:46494:71
    at new Promise (<anonymous>)
    at window_main_awaiter (/tmp/.mount_Bitwar32BNUm/resources/app.asar/main.js:46490:12)
    at WindowMain.updateWindowState (/tmp/.mount_Bitwar32BNUm/resources/app.asar/main.js:46715:16)
    at WindowMain.<anonymous> (/tmp/.mount_Bitwar32BNUm/resources/app.asar/main.js:46649:28)
    at Generator.next (<anonymous>)
    at /tmp/.mount_Bitwar32BNUm/resources/app.asar/main.js:46494:71
    at new Promise (<anonymous>)
`

I am on fedora silverblue with gnome 44.4 on wayland

![image](https://github.com/bitwarden/clients/assets/63703842/a23fc653-fd1b-4233-84cd-86d2fe3df563)

**Comment by sky96111** [comment]
same problem with  v2023.9.1 on fedora 38 (both rpm, flatpak and appimage)
````
(node:53941) DeprecationWarning: file property is deprecated and will be removed in v5.
    at new ElectronLogService (/opt/Bitwarden/resources/app.asar/main.js:47508:50)
    at new Main (/opt/Bitwarden/resources/app.asar/main.js:53757:27)
    at 64164 (/opt/Bitwarden/resources/app.asar/main.js:44265:18)
    at __webpack_require__ (/opt/Bitwarden/resources/app.asar/main.js:58131:42)
    at /opt/Bitwarden/resources/app.asar/main.js:58187:37
    at Object.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:58189:12)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1296:10)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:937:12)
(node:53941) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'init')
    at BiometricsService.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:47194:55)
    at Generator.next (<anonymous>)
    at /opt/Bitwarden/resources/app.asar/main.js:47160:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/opt/Bitwarden/resources/app.asar/main.js:47156:12)
    at BiometricsService.init (/opt/Bitwarden/resources/app.asar/main.js:47193:16)
    at Main.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:53804:46)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/Bitwarden/resources/app.asar/main.js:53701:58)
(Use `bitwarden --trace-warnings ...` to show where the warning was created)
(node:53941) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:53941) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading 'null')
    at new Menubar (/opt/Bitwarden/resources/app.asar/main.js:45540:131)
    at MenuMain.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:45594:56)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/Bitwarden/resources/app.asar/main.js:45564:58)
(node:53941) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
[53976:1005/210621.970988:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
21:06:23.663 › TypeError: Object has been destroyed
    at WindowMain.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:46720:36)
    at Generator.next (<anonymous>)
    at /opt/Bitwarden/resources/app.asar/main.js:46494:71
    at new Promise (<anonymous>)
    at window_main_awaiter (/opt/Bitwarden/resources/app.asar/main.js:46490:12)
    at WindowMain.updateWindowState (/opt/Bitwarden/resources/app.asar/main.js:46715:16)
    at WindowMain.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:46649:28)
    at Generator.next (<anonymous>)
    at /opt/Bitwarden/resources/app.asar/main.js:46494:71
    at new Promise (<anonymous>)
````

**Comment by Greenderella** [comment]
Hi there!

We appreciate you letting us know of this issue, but I just wanted to remind everybody that Bitwarden doesn't make or support the Flatpak client, it is community supported. I suggest everybody to try with a supported client, either AppImage (ideal) or Snap.

We use GitHub issues as a place to track bugs and other development related issues. If after trying with these clients the issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

This issue will now be closed.

Thanks!
