### ISSUE TITLE
Linux snap not launching. Fails with SyntaxError

### ISSUE THREAD

**Issue by berkes** [bitwarden/clients#6554]
### Steps To Reproduce

1. Kill all bitwarden processes and deamons
2.a Start bitwarden using the desktop icon
2.b Start bitwarden on the CLI with the command "bitwarden"

### Expected Result

Bitwarden should be running.

### Actual Result

Bitwarden doesn't run.

On the CLI an error is presented:

$ bitwarden
 
(node:407571) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Expected property name or '}' in JSON at position 16384
    at JSON.parse (<anonymous>)
    at Conf._deserialize (/snap/bitwarden/96/resources/app.asar/main.js:7833:43)
    at get store [as store] (/snap/bitwarden/96/resources/app.asar/main.js:8044:43)
    at new Conf (/snap/bitwarden/96/resources/app.asar/main.js:7897:32)
    at new ElectronStore (/snap/bitwarden/96/resources/app.asar/main.js:11630:3)
    at new ElectronStorageService (/snap/bitwarden/96/resources/app.asar/main.js:53316:22)
    at new Main (/snap/bitwarden/96/resources/app.asar/main.js:53763:31)
    at 64164 (/snap/bitwarden/96/resources/app.asar/main.js:44265:18)
    at __webpack_require__ (/snap/bitwarden/96/resources/app.asar/main.js:58131:42)
    at /snap/bitwarden/96/resources/app.asar/main.js:58187:37

(bitwarden:407571): Gtk-WARNING **: 17:05:46.811: Theme parsing error: gtk.css:1413:23: 'font-feature-settings' is not a valid property name

(bitwarden:407571): Gtk-WARNING **: 17:05:46.813: Theme parsing error: gtk.css:3286:25: 'font-feature-settings' is not a valid property name

(bitwarden:407571): Gtk-WARNING **: 17:05:46.813: Theme parsing error: gtk.css:3748:23: 'font-feature-settings' is not a valid property name
Driver does not support the 0x46a6 PCI ID.
libGL error: failed to create dri screen
libGL error: failed to load driver: iris
[407660:1011/170546.881962:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
Driver does not support the 0x46a6 PCI ID.

### Additional Context

```
snap info bitwarden
name:      bitwarden
summary:   Bitwarden
publisher: 8bit Solutions LLC (bitwarden✓)
store-url: https://snapcraft.io/bitwarden
contact:   https://bitwarden.com
license:   unset
description: |
  A secure and free password manager for all of your devices.
commands:
  - bitwarden
snap-id:      Nvk8FZTYrAYFKXN74w5LtOrnOhE38fU8
tracking:     latest/stable
refresh-date: today at 16:29 CEST
channels:
  latest/stable:    2023.9.1 2023-09-29 (96) 89MB -
  latest/candidate: ↑                             
  latest/beta:      ↑                             
  latest/edge:      ↑                             
installed:          2023.9.1            (96) 89MB -
```

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.3 LTS x86_64

### Installation method

Snap

### Build Version

2023.9.1 2023-09-29 (96)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by berkes** [comment]
To confirm:

`snap remove bitwarden && snap install bitwarden` makes the problem indeed dissapear. 

Also to confirm: I did ensure there was no bitwarden running when attempting to start one. 
Snap did have an autoupdate. I presume this broke somehow. Thanks for the time.
