### ISSUE TITLE
App contents are not showing 

### ISSUE THREAD

**Issue by navaneethnpk** [bitwarden/clients#6732]
### Steps To Reproduce

1. Go to applications
2. Click on the BItwarden app.

### Expected Result

It should show the login page, Asking for credentials.

### Actual Result

A blank login page is shown with only curser visible.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/38340722/261494b2-a791-41b6-92a9-95ebf7707ea6)

![image](https://github.com/bitwarden/clients/assets/38340722/115df969-84d5-42a6-b52c-fbddad628fb6)

### Additional Context

App Info:
            Version 2023.9.3
            Shell 25.9.1
            Renderer 114.0.5735.289
            Node 18.15.0
            Architecture x64
Installation method: Flatpak

### Operating System

Linux

### Operating System Version

Fedora 38 (Workstation Edition)

### Installation method

Other

### Build Version

Version 2023.9.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by GlenKPeterson** [comment]
Same thing on Ubuntu 22.04 in Flatpak this AM:
![Screenshot from 2023-10-30 08-05-15](https://github.com/bitwarden/clients/assets/2416031/3297e5d3-e0f9-4417-9486-cdefc5088e01)

**Comment by GlenKPeterson** [comment]
Since it's just the two of us so far and we're both using Flatpak, I opened an issue there: https://github.com/flathub/com.bitwarden.desktop/issues/165

My guess is that the client and server both needed to be updated but the Flatpak is out of date.

**Comment by GlenKPeterson** [comment]
Huh.  The version in flatpak looks like 2023.9.3 and the version available on Bitwarden.com is the same.

**Comment by GlenKPeterson** [comment]
I downloaded the .Appimage from the Bitwarden site and it worked perfectly.  The debugging output from the command line was very different.

.Appimage (works):
```
$ ./Bitwarden-2023.9.3-x86_64.AppImage 
(node:5248) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
MESA-INTEL: warning: Haswell Vulkan support is incomplete
(node:5248) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'init')
    at BiometricsService.<anonymous> (/tmp/.mount_BitwarKawVY9/resources/app.asar/main.js:47194:55)
    at Generator.next (<anonymous>)
    at /tmp/.mount_BitwarKawVY9/resources/app.asar/main.js:47160:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/tmp/.mount_BitwarKawVY9/resources/app.asar/main.js:47156:12)
    at BiometricsService.init (/tmp/.mount_BitwarKawVY9/resources/app.asar/main.js:47193:16)
    at Main.<anonymous> (/tmp/.mount_BitwarKawVY9/resources/app.asar/main.js:53805:46)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_BitwarKawVY9/resources/app.asar/main.js:53702:58)
(node:5248) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
(node:5248) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading 'null')
    at new Menubar (/tmp/.mount_BitwarKawVY9/resources/app.asar/main.js:45540:131)
    at MenuMain.<anonymous> (/tmp/.mount_BitwarKawVY9/resources/app.asar/main.js:45594:56)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_BitwarKawVY9/resources/app.asar/main.js:45564:58)
(node:5248) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
08:35:34.916 › Checking for update
08:35:34.931 › Generated new staging user ID: 14140caf-92aa-54c5-908e-4d0246b80c66
08:35:35.678 › Update for version 2023.9.3 is not available (latest version: 2023.9.3, downgrade is disallowed).
```

Flatpak (broken):
```
$ flatpak run com.bitwarden.desktop 
(node:2) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
Gtk-Message: 08:38:50.607: Failed to load module "canberra-gtk-module"
Gtk-Message: 08:38:50.608: Failed to load module "canberra-gtk-module"
libva error: /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/iHD_drv_video.so init failed
(node:2) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'init')
    at BiometricsService.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:47194:55)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:47160:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/app/Bitwarden/resources/app.asar/main.js:47156:12)
    at BiometricsService.init (/app/Bitwarden/resources/app.asar/main.js:47193:16)
    at Main.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:53805:46)
    at Generator.next (<anonymous>)
    at fulfilled (/app/Bitwarden/resources/app.asar/main.js:53702:58)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[39:1030/083850.833496:ERROR:shared_context_state.cc(81)] Skia shader compilation error
------------------------
// Vertex SKSL
#extension GL_NV_shader_noperspective_interpolation: require
uniform float4 sk_RTAdjust;uniform float2 uAtlasSizeInv_S0;in float2 inPosition;in half4 inColor;in ushort2 inTextureCoords;noperspective out float2 vTextureCoords_S0;flat out float vTexIndex_S0;noperspective out half4 vinColor_S0;void main() {// Primitive Processor BitmapText
int texIdx = 0;float2 unormTexCoords = float2(inTextureCoords.x, inTextureCoords.y);vTextureCoords_S0 = unormTexCoords * uAtlasSizeInv_S0;vTexIndex_S0 = float(texIdx);vinColor_S0 = inColor;float2 _tmp_1_inPosition = inPosition;sk_Position = inPosition.xy01;}
// Fragment SKSL
#extension GL_NV_shader_noperspective_interpolation: require
uniform sampler2D uTextureSampler_0_S0;
noperspective in float2 vTextureCoords_S0;flat in float vTexIndex_S0;noperspective in half4 vinColor_S0;void main() {// Stage 0, BitmapText
half4 outputColor_S0;outputColor_S0 = vinColor_S0;half4 texColor;{ texColor = sample(uTextureSampler_0_S0, vTextureCoords_S0).rrrr; }half4 outputCoverage_S0 = texColor;{ // Xfer Processor: Porter Duff
sk_FragColor = outputColor_S0 * outputCoverage_S0;}}
// Vertex GLSL
#version 300 es

#extension GL_NV_shader_noperspective_interpolation : require
precision mediump float;
precision mediump sampler2D;
uniform highp vec4 sk_RTAdjust;
uniform highp vec2 uAtlasSizeInv_S0;
in highp vec2 inPosition;
in mediump vec4 inColor;
in mediump uvec2 inTextureCoords;
noperspective out highp vec2 vTextureCoords_S0;
flat out highp float vTexIndex_S0;
noperspective out mediump vec4 vinColor_S0;
void main() {
    highp int texIdx = 0;
    highp vec2 unormTexCoords = vec2(float(inTextureCoords.x), float(inTextureCoords.y));
    vTextureCoords_S0 = unormTexCoords * uAtlasSizeInv_S0;
    vTexIndex_S0 = float(texIdx);
    vinColor_S0 = inColor;
    gl_Position = vec4(inPosition, 0.0, 1.0);
    gl_Position = vec4(gl_Position.xy * sk_RTAdjust.xz + gl_Position.ww * sk_RTAdjust.yw, 0.0, gl_Position.w);
}

// Fragment GLSL
#version 300 es

#extension GL_NV_shader_noperspective_interpolation : require
precision mediump float;
precision mediump sampler2D;
out mediump vec4 sk_FragColor;
uniform sampler2D uTextureSampler_0_S0;
noperspective in highp vec2 vTextureCoords_S0;
flat in highp float vTexIndex_S0;
noperspective in mediump vec4 vinColor_S0;
void main() {
    mediump vec4 outputColor_S0;
    outputColor_S0 = vinColor_S0;
    mediump vec4 texColor;
    {
        texColor = texture(uTextureSampler_0_S0, vTextureCoords_S0, -0.5).xxxx;
    }
    mediump vec4 outputCoverage_S0 = texColor;
    {
        sk_FragColor = outputColor_S0 * outputCoverage_S0;
    }
}


Errors:
link failed but did not provide an info log
08:38:51.204 › Error: No password found
08:38:51.216 › Error: No password found
[39:1030/083851.245264:ERROR:shared_context_state.cc(81)] Skia shader compilation error
------------------------
// Vertex SKSL
#extension GL_NV_shader_noperspective_interpolation: require
uniform float4 sk_RTAdjust;in float2 position;in half4 color;flat out half4 vcolor_S0;void main() {// Primitive Processor QuadPerEdgeAAGeometryProcessor
vcolor_S0 = color;sk_Position = position.xy01;}
// Fragment SKSL
#extension GL_NV_shader_noperspective_interpolation: require
flat in half4 vcolor_S0;void main() {// Stage 0, QuadPerEdgeAAGeometryProcessor
half4 outputColor_S0;outputColor_S0 = vcolor_S0;const half4 outputCoverage_S0 = half4(1);{ // Xfer Processor: Porter Duff
sk_FragColor = outputColor_S0 * outputCoverage_S0;}}
// Vertex GLSL
#version 300 es

#extension GL_NV_shader_noperspective_interpolation : require
precision mediump float;
precision mediump sampler2D;
uniform highp vec4 sk_RTAdjust;
in highp vec2 position;
in mediump vec4 color;
flat out mediump vec4 vcolor_S0;
void main() {
    vcolor_S0 = color;
    gl_Position = vec4(position, 0.0, 1.0);
    gl_Position = vec4(gl_Position.xy * sk_RTAdjust.xz + gl_Position.ww * sk_RTAdjust.yw, 0.0, gl_Position.w);
}

// Fragment GLSL
#version 300 es

#extension GL_NV_shader_noperspective_interpolation : require
precision mediump float;
precision mediump sampler2D;
out mediump vec4 sk_FragColor;
flat in mediump vec4 vcolor_S0;
void main() {
    mediump vec4 outputColor_S0;
    outputColor_S0 = vcolor_S0;
    {
        sk_FragColor = outputColor_S0;
    }
}


Errors:
link failed but did not provide an info log
08:38:51.245 › Error: No password found
[39:1030/083851.245848:ERROR:shared_context_state.cc(81)] Skia shader compilation error
------------------------
// Vertex SKSL
...
```

**Comment by GlenKPeterson** [comment]
Workaround: I turned off GPU Acceleration in Flatseal and Bitwarden works:
![Screenshot from 2023-10-30 08-46-31](https://github.com/bitwarden/clients/assets/2416031/47981701-7186-40ae-aaac-ad1910a68fde)

If it matters, here's my video card info:
```
$ lspci
00:00.0 Host bridge: Intel Corporation 4th Gen Core Processor DRAM Controller (rev 06)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor PCI Express x16 Controller (rev 06)
00:01.1 PCI bridge: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor PCI Express x8 Controller (rev 06)
00:02.0 VGA compatible controller: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)
...
```
It's built into my CPU: `Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz`

**Comment by kparal** [comment]
I have the same problem on my Fedora 38, with the same Bitwarden version, also installed from Flathub. Disabling video acceleration using Flatseal as shown above works around the problem. I have a Radeon 580 GPU.

Terminal output when rendering is broken:
[bitwarden-output.txt](https://github.com/bitwarden/clients/files/13205856/bitwarden-output.txt)

**Comment by felix2380** [comment]
I have the same problem on Linux Mint 21.2 Cinnamon.
![signal-2023-10-30-094626](https://github.com/bitwarden/clients/assets/147976134/97be5189-9448-4863-8c5d-e628b7584841)

**Comment by zestygrass** [comment]
Experiencing the same issue as well, fixed it with removing the GPUCache folder as mentioned in the issue over at [element's flatpak issue tracker](https://github.com/flathub/im.riot.Riot/issues/411)

For Bitwarden, Run `rm -rf ~/.var/app/com.bitwarden.desktop/config/Bitwarden/Partitions/bitwarden/GPUCache`

**Comment by djsmith85** [comment]
Since the flatpak isn't distributed by Bitwarden the issue seems to be tracked over at https://github.com/flathub/com.bitwarden.desktop/issues/165.

Closing this since Bitwarden does not maintain the flatpack distribution.

**Comment by kparal** [comment]
This might be yet another manifestation of this issue:
https://discussion.fedoraproject.org/t/chromium-based-browsers-display-garbled-web-pages-after-mesa-is-updated/83438
https://bugs.chromium.org/p/chromium/issues/detail?id=1442633

I very much doubt this is Flatpak-specific. I hoped Bitwarden devs would try to workaround this issue, e.g. by disabling GPU acceleration in the underlying library (Electron, I assume). Common users will not be able to search for the workaround.
