### ISSUE TITLE
Windows App drawing rotating loader before login 

### ISSUE THREAD

**Issue by acirasa** [bitwarden/clients#6753]
### Steps To Reproduce

- Open app
- for few second I see password input box
- page loader appear and nothing happen

### Expected Result

- - Open app
-  insert password
- login accepted

### Actual Result

Loader appear after few second and I can't write password

### Screenshots or Videos

![Bitwarden_sVv9Vis9O5](https://github.com/bitwarden/clients/assets/22149597/c8d543f8-e3c6-40c4-9ee1-c926d3f5ef12)

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.10.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jleider** [comment]
I'm having a similar issue with the Mac app. I think I see a flash of the login prompt but the app immediately goes to this loading indicator. The browser plugin I have says there is an error and can not decrypt the passwords. I can still access passwords through the bitwarden website though.

**Comment by Canowyrms** [comment]
I'm experiencing this issue on one of my devices, too. Any time I start the app and open it up, all I get is the spinner in the center of the window. At time of writing, the Firefox extension on this device continues to work as expected.

Bitwarden's devtools console has some errors being logged:

```
error_handler.ts:45 
ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'keys')
TypeError: Cannot read properties of undefined (reading 'keys')
    at useClass.<anonymous> (state.service.ts:649:13)
    at Generator.next (<anonymous>)
    at o (main.js:1:272466)
    at c.invoke (zone.js:375:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at c.invoke (zone.js:374:52)
    at o.run (zone.js:134:43)
    at zone.js:1278:36
    at c.invokeTask (zone.js:409:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at C (zone.js:1214:31)
    at C (zone.js:1168:17)
    at zone.js:1281:17
    at c.invokeTask (zone.js:409:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at c.invokeTask (zone.js:408:60)
    at o.runTask (zone.js:178:47)
    at v (zone.js:588:35)
handleError @ error_handler.ts:45

identity.bitwarden.com/connect/token:1
Failed to load resource: the server responded with a status of 400 ()

identity.bitwarden.com/connect/token:1
Failed to load resource: the server responded with a status of 400 ()

2error_handler.ts:45
ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'profile')
TypeError: Cannot read properties of undefined (reading 'profile')
    at useClass.<anonymous> (state.service.ts:2068:13)
    at Generator.next (<anonymous>)
    at o (main.js:1:272466)
    at c.invoke (zone.js:375:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at c.invoke (zone.js:374:52)
    at o.run (zone.js:134:43)
    at zone.js:1278:36
    at c.invokeTask (zone.js:409:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at C (zone.js:1214:31)
    at zone.js:1121:17
    at zone.js:1137:33
    at a (main.js:1:1536972)
    at c.invoke (zone.js:375:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at c.invoke (zone.js:374:52)
    at o.run (zone.js:134:43)
    at zone.js:1278:36
    at c.invokeTask (zone.js:409:31)
handleError @ error_handler.ts:45

zone.js:2408 
18:20:10.617 › Unable to fetch ServerConfig: undefined
i.<computed> @ zone.js:2408

identity.bitwarden.com/connect/token:1
Failed to load resource: the server responded with a status of 400 ()

```

Bitwarden
Version 2023.10.0
Shell 25.9.1
Renderer 114.0.5735.289
Node 18.15.0
Architecture x64

Windows 10 22H2

---

On my main computer, the desktop app is working just fine. Maybe an update broke something?

Bitwarden
Version 2023.9.3
Shell 25.9.1
Renderer 114.0.5735.289
Node 18.15.0
Architecture x64

Windows 10 22H2

**Comment by eanyanwu** [comment]
Hello 👋🏽  I am experiencing a similar issue as well. This time on a linux machine.

I get a bunch of errors on the console (View -> Toggle Developper Tools)

```
Failed to load resource: the server responded with a status of 400 ()
```

```
ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'profile')
TypeError: Cannot read properties of undefined (reading 'profile')
    at useClass.<anonymous> (state.service.ts:2030:13)
    at Generator.next (<anonymous>)
    at r (main.js:1:265825)
    at c.invoke (zone.js:375:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at c.invoke (zone.js:374:52)
    at o.run (zone.js:134:43)
    at zone.js:1278:36
    at c.invokeTask (zone.js:409:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at C (zone.js:1214:31)
    at zone.js:1121:17
    at zone.js:1137:33
    at a (main.js:1:1279516)
    at c.invoke (zone.js:375:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at c.invoke (zone.js:374:52)
    at o.run (zone.js:134:43)
    at zone.js:1278:36
    at c.invokeTask (zone.js:409:31) 
```

```
Unable to fetch ServerConfig: undefined
```

Version info:
```
Version 2023.10.1
Shell 25.9.4
Renderer 114.0.5735.289
Node 18.15.0
Architecture x64
```

Let me know if there is additional information I can provide that would be helpful

**Comment by haguh3** [comment]
Hi, I'm experiencing the same issue on my windows client

Version 2023.10.1
Shell 25.9.1
Renderer 114.0.5735.289
Node 18.15.0
Architecture x64


devs console shows same errors as other users reported.

**Comment by eanyanwu** [comment]
Yea, same thing for me. It started working after i reinstalled my OS (for unrelated reasons)
So it smells like some bade application state lingering around.

Since i resolved it by basically blowing away my computer, I can't really say which files were causing problems :/

**Comment by TroyBW** [comment]
Hi there!

Thank you for your report. It seems similar to another issue that the team is tracking here: https://github.com/bitwarden/clients/issues/6878

To keep things tidy, I will close this ticket, and https://github.com/bitwarden/clients/issues/6878 will be the ticket we use to track the issue. If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!
