### ISSUE TITLE
Linux Version doesn't start (Snap, Mint)

### ISSUE THREAD

**Issue by christian179717** [bitwarden/clients#7040]
### Steps To Reproduce

Open Bitwarden normally

### Expected Result

The Window should open

### Actual Result

Bitwarden doesn't run, if I run in terminal `bitwarden` this output comes:
```
(node:3375) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Conf._deserialize (/snap/bitwarden/100/resources/app.asar/main.js:7833:43)
    at get store [as store] (/snap/bitwarden/100/resources/app.asar/main.js:8044:43)
    at new Conf (/snap/bitwarden/100/resources/app.asar/main.js:7897:32)
    at new ElectronStore (/snap/bitwarden/100/resources/app.asar/main.js:11630:3)
    at new ElectronStorageService (/snap/bitwarden/100/resources/app.asar/main.js:53557:22)
    at new Main (/snap/bitwarden/100/resources/app.asar/main.js:54006:31)
    at 64164 (/snap/bitwarden/100/resources/app.asar/main.js:44265:18)
    at __webpack_require__ (/snap/bitwarden/100/resources/app.asar/main.js:58381:42)
    at /snap/bitwarden/100/resources/app.asar/main.js:58437:37
Gtk-Message: 15:53:32.936: Failed to load module "xapp-gtk3-module"
```

### Operating System

Linux

### Operating System Version

Mint Vanessa 21.2

### Installation method

Snap

### Build Version

Can't check, cannot open

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by FlameSoulis** [comment]
Hmm... not sure with snaps, but on apt, I'm wondering if the xapp packages are actually installed.

Those would be ```gir1.2-xapp-1.0 libxapp1```, ```xapps-common```, and ```python3-xapp```. I am using Flatpak, so I don't have the ```xapp``` package itself installed.
