### ISSUE TITLE
ERR_INVALID_ARG_TYPE CLI 2023.12.0

### ISSUE THREAD

**Issue by eleaner** [bitwarden/clients#7153]
### Steps To Reproduce

1.  wget https://github.com/bitwarden/clients/releases/download/cli-v2023.12.0/bw-linux-2023.12.0.zip
2. unzip bw-linux-2023.12.0.zip
3. chmod +x bw
4. bw --help

### Expected Result

whatever help returns

### Actual Result

node:internal/validators:114
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:388:5)
    at validateString (node:internal/validators:114:11)
    at Object.join (node:path:1172:7)
    at new Main (/snapshot/clients/apps/cli/build/bw.js:44822:47)
    at /snapshot/clients/apps/cli/build/bw.js:44942:14
    at /snapshot/clients/apps/cli/build/bw.js:44945:3
    at Object.<anonymous> (/snapshot/clients/apps/cli/build/bw.js:44947:12)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.5.0
root@bitwarden-export:/tmp# ./bw --help
node:internal/validators:114
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:388:5)
    at validateString (node:internal/validators:114:11)
    at Object.join (node:path:1172:7)
    at new Main (/snapshot/clients/apps/cli/build/bw.js:44822:47)
    at /snapshot/clients/apps/cli/build/bw.js:44942:14
    at /snapshot/clients/apps/cli/build/bw.js:44945:3
    at Object.<anonymous> (/snapshot/clients/apps/cli/build/bw.js:44947:12)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32) {
  code: 'ERR_INVALID_ARG_TYPE'
}

### Screenshots or Videos

n/a

### Additional Context

run as root
run as container under proxmox

### Operating System

Linux

### Operating System Version

debian 12

### Shell

Bash

### Build Version

cannot run 

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @eleaner,

Thank you for reporting this. Could you please remove your CLI client and install or download a fresh copy anew? I ask because I was unable to reproduce this behaviour and the --help switch worked as expected.

If this behaviour persists, please create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub issues as a place to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
