### ISSUE TITLE
OSX desktop app UI blank

### ISSUE THREAD

**Issue by khturner** [bitwarden/clients#7544]
### Steps To Reproduce

1. Open OS X desktop app Version 2023.12.1 (16254) on a Macbook Pro (system info below) running OS X Sonoma (14.2.1)

Macbook Pro info:
```
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,4
  Processor Name:	Quad-Core Intel Core i5
  Processor Speed:	1.4 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Hyper-Threading Technology:	Enabled
  Memory:	8 GB
  System Firmware Version:	2020.61.1.0.0 (iBridge: 21.16.2057.0.0,0)
  OS Loader Version:	580~1053
  Activation Lock Status:	Disabled
```

### Expected Result

I expect to see the Bitwarden UI

### Actual Result

The UI is blank, except for the account switcher in the top right. No useful menu options are available.

### Screenshots or Videos

<img width="1438" alt="image" src="https://github.com/bitwarden/clients/assets/5489419/6b1cf3a3-7724-4a88-bd51-bebc301d0a26">

### Additional Context

The developer tools console shows two errors - this is the log:

```
console.js:77 18:16:59.666 › State version: 9
console.js:77 18:16:59.668 › Migrator vl (to version 2) should migrate: false - up
console.js:77 18:16:59.668 › Migrator il (to version 3) should migrate: false - up
console.js:77 18:16:59.669 › Migrator sl (to version 4) should migrate: false - up
console.js:77 18:16:59.669 › Migrator ol (to version 5) should migrate: false - up
console.js:77 18:16:59.669 › Migrator ll (to version 6) should migrate: false - up
console.js:77 18:16:59.669 › Migrator ul (to version 7) should migrate: false - up
console.js:77 18:16:59.669 › Migrator hl (to version 8) should migrate: false - up
console.js:77 18:16:59.669 › Migrator gl (to version 9) should migrate: false - up
error_handler.ts:45 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'keys')
TypeError: Cannot read properties of undefined (reading 'keys')
    at useClass.<anonymous> (state.service.ts:650:13)
    at Generator.next (<anonymous>)
    at o (main.js:1:286700)
    at c.invoke (zone.js:375:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at c.invoke (zone.js:374:52)
    at o.run (zone.js:134:43)
    at zone.js:1278:36
    at c.invokeTask (zone.js:409:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at C (zone.js:1214:31)
    at C (zone.js:1168:17)
    at zone.js:1281:17
    at c.invokeTask (zone.js:409:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at c.invokeTask (zone.js:408:60)
    at o.runTask (zone.js:178:47)
    at v (zone.js:588:35)
handleError @ error_handler.ts:45
error_handler.ts:45 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'keys')
TypeError: Cannot read properties of undefined (reading 'keys')
    at useClass.<anonymous> (state.service.ts:650:13)
    at Generator.next (<anonymous>)
    at o (main.js:1:286700)
    at c.invoke (zone.js:375:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at c.invoke (zone.js:374:52)
    at o.run (zone.js:134:43)
    at zone.js:1278:36
    at c.invokeTask (zone.js:409:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at C (zone.js:1214:31)
    at C (zone.js:1168:17)
    at zone.js:1281:17
    at c.invokeTask (zone.js:409:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at c.invokeTask (zone.js:408:60)
    at o.runTask (zone.js:178:47)
    at v (zone.js:588:35)
handleError @ error_handler.ts:45
```

### Operating System

macOS

### Operating System Version

14.2.1

### Installation method

Mac App Store

### Build Version

2023.12.1 (16254)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @khturner,

Thank you for your report. It seems similar to [this one](https://github.com/bitwarden/clients/issues/6691); Can you please let me know if the steps [here](https://github.com/bitwarden/clients/issues/6691#issuecomment-1826376325) or [here](https://github.com/bitwarden/clients/issues/6691#issuecomment-1865191209) assist you?


Thank you in advance,

**Comment by khturner** [comment]
Yep! That works! Thank you so much
