### ISSUE TITLE
Bitwarden taking a long time to start with several errors.

### ISSUE THREAD

**Issue by rickalex21** [bitwarden/clients#7548]
### Steps To Reproduce

Open the Linux app Image on Debian.

### Expected Result

For it to quickly start. 

### Actual Result

It takes a long time to start and throws several errors.

### Screenshots or Videos

I understand this may be a wallet issue but there are also other several errors on here.

```text
(node:9784) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'init')
    at BiometricsService.<anonymous> (/tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:49684:55)
    at Generator.next (<anonymous>)
    at /tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:49650:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:49646:12)
    at BiometricsService.init (/tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:49683:16)
    at Main.<anonymous> (/tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:55950:46)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:55838:58)
(Use `bitwarden --trace-warnings ...` to show where the warning was created)
(node:9784) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
11:13:15.727 › State version: 9
11:13:15.730 › Migrator Hc (to version 2) should migrate: false - up
11:13:15.730 › Migrator Nc (to version 3) should migrate: false - up
11:13:15.731 › Migrator Fc (to version 4) should migrate: false - up
11:13:15.732 › Migrator Rc (to version 5) should migrate: false - up
11:13:15.732 › Migrator Kc (to version 6) should migrate: false - up
11:13:15.732 › Migrator Jc (to version 7) should migrate: false - up
11:13:15.732 › Migrator zc (to version 8) should migrate: false - up
11:13:15.733 › Migrator Gc (to version 9) should migrate: false - up
11:13:19.982 › Checking for update
11:13:20.341 › Update for version 2024.1.0 is not available (latest version: 2024.1.0, downgrade is disallowed).
11:13:40.777 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
11:14:05.862 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
11:14:19.136 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Failed to activate service 'org.freedesktop.secrets': timed out (service_start_timeout=120000ms)
11:14:19.138 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Failed to activate service 'org.freedesktop.secrets': timed out (service_start_timeout=120000ms)
11:14:19.138 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Failed to activate service 'org.freedesktop.secrets': timed out (service_start_timeout=120000ms)
11:14:19.139 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Failed to activate service 'org.freedesktop.secrets': timed out (service_start_timeout=120000ms)
11:14:19.139 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Failed to activate service 'org.freedesktop.secrets': timed out (service_start_timeout=120000ms)
11:14:19.140 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Failed to activate service 'org.freedesktop.secrets': timed out (service_start_timeout=120000ms)
(node:9784) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setContextMenu')
    at TrayMain.updateContextMenu (/tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:47757:23)
    at MessagingMain.updateTrayMenu (/tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:47257:28)
    at MessagingMain.onMessage (/tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:47183:22)
    at MessagingMain.<anonymous> (/tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:47174:151)
    at Generator.next (<anonymous>)
    at /tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:47153:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:47149:12)
    at IpcMainImpl.<anonymous> (/tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:47174:79)
    at IpcMainImpl.emit (node:events:514:28)
(node:9784) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
[9817:0114/111419.190236:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
11:14:44.201 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
11:14:44.237 › TypeError: Cannot read properties of undefined (reading 'osSupportsBiometric')
    at BiometricsService.<anonymous> (/tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:49689:55)
    at Generator.next (<anonymous>)
    at /tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:49650:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:49646:12)
    at BiometricsService.osSupportsBiometric (/tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:49688:16)
    at BiometricsService.<anonymous> (/tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:49699:58)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:49647:58)
11:14:44.237 › TypeError: Cannot read properties of undefined (reading 'osSupportsBiometric')
    at BiometricsService.<anonymous> (/tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:49689:55)
    at Generator.next (<anonymous>)
    at /tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:49650:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:49646:12)
    at BiometricsService.osSupportsBiometric (/tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:49688:16)
    at DesktopCredentialStorageListener.<anonymous> (/tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:49898:59)
    at Generator.next (<anonymous>)
    at /tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:49826:71
    at new Promise (<anonymous>)
[9817:0114/111444.286427:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
11:14:44.293 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
11:14:50.899 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
11:15:00.899 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
[9817:0114/111507.547543:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
11:15:09.293 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
11:15:09.393 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
11:15:10.902 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
11:15:20.900 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
11:15:30.901 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
11:15:34.486 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
11:15:40.897 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
11:15:50.898 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
11:15:59.637 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
11:15:59.643 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
(node:9784) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setContextMenu')
    at TrayMain.updateContextMenu (/tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:47757:23)
    at MessagingMain.updateTrayMenu (/tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:47257:28)
    at MessagingMain.onMessage (/tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:47183:22)
    at MessagingMain.<anonymous> (/tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:47174:151)
    at Generator.next (<anonymous>)
    at /tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:47153:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:47149:12)
    at IpcMainImpl.<anonymous> (/tmp/.mount_bitwarA0rPOW/resources/app.asar/main.js:47174:79)
    at IpcMainImpl.emit (node:events:514:28)
(node:9784) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
11:16:00.897 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
11:16:10.899 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
11:16:19.180 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Failed to activate service 'org.freedesktop.secrets': timed out (service_start_timeout=120000ms)
11:16:19.180 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Failed to activate service 'org.freedesktop.secrets': timed out (service_start_timeout=120000ms)
11:16:19.181 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Failed to activate service 'org.freedesktop.secrets': timed out (service_start_timeout=120000ms)
11:16:19.181 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Failed to activate service 'org.freedesktop.secrets': timed out (service_start_timeout=120000ms)
^V11:16:50.904 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
11:17:00.896 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
11:17:10.893 › Error: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
```

### Operating System

Linux

### Operating System Version

Linux debian 6.6.9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.6.9-1 (2024-01-01) x86_64 GNU/Linux

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/).

The issue here will be closed.

**Comment by rickalex21** [comment]
I understand. I was hoping to get some pointers since I'm not a frontend developer. I'm a paying customer trying to troubleshoot an issue with your application. Thanks for your help though.

**Comment by NovaSilentium** [comment]
Hi there, 

Please could you reach out to us at Support@bitwarden.com so that we can assist further?

Thanks in advance!

**Comment by closebot-bw** [comment]
⚠️ **Stale Issue Notice**

This issue has been automatically marked as stale due to inactivity. It will be closed in **2 weeks** (October 15, 2025) if no further activity occurs.

If this issue is still relevant and you would like to keep it open, please:
- Comment on this issue to show continued interest
- Provide any additional information or updates
- Confirm that the issue still exists in the latest version

Thank you for your contribution to this project! 🙏

**Comment by closebot-bw** [comment]
🔒 **Issue Closed Due to Inactivity**

This issue has been automatically closed due to lack of activity for an extended period. We periodically review and close inactive issues to help maintain our issue tracker and focus on current priorities.

**If this issue is still relevant:**
- Please create a new issue with updated information
- Include steps to reproduce the problem if it's a bug report
- Mention if this issue still occurs in the latest version

Thank you for your contribution to this project. Your feedback helps us improve! 🙏
