### ISSUE TITLE
Failed to load resource: the server responded with a status of 400 ()

### ISSUE THREAD

**Issue by davidshq** [bitwarden/clients#8025]
### Steps To Reproduce

1. Open the desktop BitWarden app 2024.2.0.
2. The login screen flashes and then the screen reloads and reloads ad infinitum.

### Expected Result

The application opens and allows me to login.

### Actual Result

The login screen flashes and then the screen reloads and reloads ad infinitum.

Viewing the console in devtools I see:
```
08:16:35.912 › Migrator wu (to version 12) should migrate: false - up
Failed to load resource: the server responded with a status of 400 ()
ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'keys')
TypeError: Cannot read properties of undefined (reading 'keys')
    at useClass.<anonymous> (state.service.ts:629:13)
    at Generator.next (<anonymous>)
    at o (main.js:1:339986)
    at c.invoke (zone.js:375:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at c.invoke (zone.js:374:52)
    at o.run (zone.js:134:43)
    at zone.js:1278:36
    at c.invokeTask (zone.js:409:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at C (zone.js:1214:31)
    at zone.js:1121:17
    at zone.js:1137:33
    at a (main.js:10:230800)
    at c.invoke (zone.js:375:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at c.invoke (zone.js:374:52)
    at o.run (zone.js:134:43)
    at zone.js:1278:36
    at c.invokeTask (zone.js:409:31)
handleError @ error_handler.ts:45
console.js:77 08:16:41.975 › Unable to fetch ServerConfig: undefined
(anonymous) @ console.js:77
```

It then repeats the errors. Nothing ever loads.

I believe I had this issue on an Ubuntu box as well and I was able to get around it somehow, but I don't remember how.

### Additional Context

Version 2024.2.0
Shell 28.1.3
Renderer 120.0.6099.199
Node 18.18.2
Architecture x64

### Operating System

Windows

### Operating System Version

10.0.22621 Build 22621

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by davidshq** [comment]
If I remove and reinstall the app, it works. I think this is also how I resolved the issue on Ubuntu.

I suspect this has to do with 2FA. When I reinstall Bitwarden it brings me to the initial login screen and I'm able to walk through the process, including 2FA.

I believe I've only see this problem occurring sometimes since I enabled 2FA.

**Comment by Krychaz** [comment]
Hello there, 

I will close this for now seeing reinstallation has fixed the issue. If you encounter this issue again, please contact us via our support page directly.

**Comment by jsilve24** [comment]
I am also having this problem on arch linux. Tried uninstalling and reinstalling, still having the issue. Login takes forever (5 min) just to load and give me a password prompt. Then another few min after I enter password. Opening developer console after login gives the same error message.

**Comment by jsilve24** [comment]
Arch (my system is up to date with AUR or main package archives). Bitwarden was installed from AUR with `yay -Syu bitwarden`

Version 2024.2.0
Shell 27.3.3
Renderer 118.0.5993.159
Node 18.17.1
Architecture x64

**Comment by closebot-bw** [comment]
⚠️ **Stale Issue Notice**

This issue has been automatically marked as stale due to inactivity. It will be closed in **2 weeks** (October 15, 2025) if no further activity occurs.

If this issue is still relevant and you would like to keep it open, please:
- Comment on this issue to show continued interest
- Provide any additional information or updates
- Confirm that the issue still exists in the latest version

Thank you for your contribution to this project! 🙏

**Comment by jsilve24** [comment]
Still an issue

Sent From My Mobile Device
________________________________
