### ISSUE TITLE
version `GLIBC_2.33' not found 

### ISSUE THREAD

**Issue by simmstein** [bitwarden/clients#8257]
### Steps To Reproduce

- Upgrade AppImage or debian package.
- Run Bitwarden client
- An error occured and the app is not displayed

### Expected Result

- Upgrade AppImage or debian package.
- Run Bitwarden client
- The client works

### Actual Result

```
$ bitwarden.AppImage
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_bitwaru3pHmQ/resources/app.asar.unpacked/node_modules/@bitwarden/desktop-native/desktop_native.linux-x64-musl.node)
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)
    at Module._extensions..node (node:internal/modules/cjs/loader:1356:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2441)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/tmp/.mount_bitwaru3pHmQ/resources/app.asar/node_modules/@bitwarden/desktop-native/index.js:158:29)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
```

```
$ bitwarden
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/Bitwarden/resources/app.asar.unpacked/node_modules/@bitwarden/desktop-native/desktop_native.linux-x64-musl.node)
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)
    at Module._extensions..node (node:internal/modules/cjs/loader:1356:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2441)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/opt/Bitwarden/resources/app.asar/node_modules/@bitwarden/desktop-native/index.js:158:29)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
``` 

### Operating System

Linux

### Operating System Version

Debian 11 stable

### Installation method

Direct Download (from bitwarden.com), Other

### Build Version

https://github.com/bitwarden/clients/releases/tag/desktop-v2024.2.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by hal1961** [comment]
Dears, exactly the same error is happening on my desktop Linux Ubuntu 20.04 LTS

**Comment by hal1961** [comment]
I tried compiling glibc 2.33 following these steps:
sudo apt-get install gawk bison -y
wget -c https://ftp.gnu.org/gnu/glibc/glibc-2.33.tar.gz
tar -zxvf glibc-2.33.tar.gz && cd glibc-2.33
mkdir glibc-build && cd glibc-build
../configure --prefix=/opt/glibc-2.33
make
sudo make install

Then in the same folder I keep the AppImage I added a symlink:
ln -s /opt/glibc-2.33/lib/libc.so.6 libc.so.6
sudo chmod 777 libc.so.6

However the error changed to:
./Bitwarden-2024.2.1-x86_64.AppImage 
Segmentation fault (core dumped)

Regards

**Comment by hal1961** [comment]
Restoring Bitwarden-2024.2.0-x86_64.AppImage temporary solved the issue:

export ELECTRON_NO_UPDATER=1
./Bitwarden-2024.2.0-x86_64.AppImage

**Comment by sammbw** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by outofnowere** [comment]
@sammbw @trmartin4 still seeing the same issue today, after just downloading the linux client (and deleting config folder). 

Has the download been updated?
