### ISSUE TITLE
CLI fails to execute if /tmp mount is set to "noexec"

### ISSUE THREAD

**Issue by JuddTracy** [bitwarden/clients#8295]
### Steps To Reproduce

1. Add mount option noexec to the "/tmp" mount point
2. Run bw config server "https://<internal value"
3. Look at exception

### Expected Result

$ bw config server https://******.com
Could not find dir, "/home/XXXX/.config/Bitwarden CLI"; creating it instead.
Could not find data file, "/home/XXXX/.config/Bitwarden CLI/data.json"; creating it instead.
Saved setting `config`.

### Actual Result

$ bw config server https://******.com
pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error: /tmp/pkg/4bd3f4b31ee48f604a21d5f03bada979b98c4ff4ee1f1798114d34ac3ac586cf/argon2/lib/binding/napi-v3/argon2.node: failed to map segment from shared object
    at process.dlopen (pkg/prelude/bootstrap.js:2251:28)
    at Module._extensions..node (node:internal/modules/cjs/loader:1196:18)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/snapshot/clients/node_modules/argon2/argon2.js:9:25)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.5.0

### Additional Context

This server is locked down using the DISA STIG lockdown controls.  One of the controls is to set "/tmp" mount point to be "noexec".   This causes the exception to be made when the application tries to load the libraires.

If there is a way to control the location of the "/tmp/pkg" folder this would be sufficient to fix the issue.  I could not find a solution to change the directory.

NOTE: Since the directory is always "/tmp/pkg" this means that multiple users cannot use the cli at the same time on the same server.

### Operating System

Linux

### Operating System Version

RHEL 8.9

### Shell

Bash

### Build Version

2024.2.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by goetzk** [comment]
Just a quick note to confirm this behaviour on Debian 12 Bookworm, when /tmp is mounted with noexec.

**Comment by briandking** [comment]
I see the same behaviour, but you _can_ override the tmp dir location using the environment variable TMPDIR.
E.g.
```
$ mkdir tmp
$ export TMPDIR=./tmp
$ ./bw
Usage: bw [options] [command]

Options:
  --pretty                                    Format output. JSON is tabbed with two spaces.
  --raw                                       Return raw output instead of a descriptive message.
  ...
```

**Comment by juriaan** [comment]
Have the same issue here on Rocky 9.4 with noexec on /tmp.  With setting TMPDIR like @briandking suggest, it works

**Comment by closebot-bw** [comment]
⚠️ **Stale Issue Notice**

This issue has been automatically marked as stale due to inactivity. It will be closed in **2 weeks** (October 15, 2025) if no further activity occurs.

If this issue is still relevant and you would like to keep it open, please:
- Comment on this issue to show continued interest
- Provide any additional information or updates
- Confirm that the issue still exists in the latest version

Thank you for your contribution to this project! 🙏

**Comment by closebot-bw** [comment]
🔒 **Issue Closed Due to Inactivity**

This issue has been automatically closed due to lack of activity for an extended period. We periodically review and close inactive issues to help maintain our issue tracker and focus on current priorities.

**If this issue is still relevant:**
- Please create a new issue with updated information
- Include steps to reproduce the problem if it's a bug report
- Mention if this issue still occurs in the latest version

Thank you for your contribution to this project. Your feedback helps us improve! 🙏
