### ISSUE TITLE
Save password prompt not working, got JS errors

### ISSUE THREAD

**Issue by rkuzmin** [bitwarden/clients#8510]
### Steps To Reproduce

1. Go to any page
2. Click on login form
3. Nothing happens, got JS error in browser console

### Expected Result

Save password prompt appears

### Actual Result

Nothing happens, got JS error in Console

`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'vault')
    at notificationBar.js:356:82
    at Generator.next (<anonymous>)
    at fulfilled (notificationBar.js:260:58)`
The code:
`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'vault')
    at notificationBar.js:356:82
    at Generator.next (<anonymous>)
    at fulfilled (notificationBar.js:260:58)`

### Operating System

macOS

### Operating System Version

13.6.5 (22G621)

### Web Browser

Chrome

### Browser Version

123.0.6312.59

### Build Version

2024.2.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there,

Will you try uninstalling the application, removing any leftover data, powering off and on your device and re-installing? Does this issue still persist?

Guide to the leftover data: [https://bitwarden.com/help/data-storage/#on-your-local-machine](https://bitwarden.com/help/article/data-storage/#on-your-local-machine)

Let me know if that helps.

**Comment by rkuzmin** [comment]
Yes, I did and it doesn't helped. Moreover now I have broken Biometric login. App is opened.
<img width="758" alt="image" src="https://github.com/bitwarden/clients/assets/892987/d8773252-9296-469d-aa42-895a54c38e45">

**Comment by closebot-bw** [comment]
⚠️ **Stale Issue Notice**

This issue has been automatically marked as stale due to inactivity. It will be closed in **2 weeks** (October 15, 2025) if no further activity occurs.

If this issue is still relevant and you would like to keep it open, please:
- Comment on this issue to show continued interest
- Provide any additional information or updates
- Confirm that the issue still exists in the latest version

Thank you for your contribution to this project! 🙏

**Comment by closebot-bw** [comment]
🔒 **Issue Closed Due to Inactivity**

This issue has been automatically closed due to lack of activity for an extended period. We periodically review and close inactive issues to help maintain our issue tracker and focus on current priorities.

**If this issue is still relevant:**
- Please create a new issue with updated information
- Include steps to reproduce the problem if it's a bug report
- Mention if this issue still occurs in the latest version

Thank you for your contribution to this project. Your feedback helps us improve! 🙏
