### ISSUE TITLE
RESTful API sync and unlock function breaks after the server has been up "for a while"

### ISSUE THREAD

**Issue by eebette** [bitwarden/clients#9306]
### Steps To Reproduce

1. Run `bw serve`
2. Run `curl http://localhost:8087/unlock -d '{"password": "***"}' --header "Content-Type: application/json"` <----- This works
3. Run `curl http://localhost:8087/sync -d '{}' --header "Content-Type: application/json"` <----- This works
4. Run `curl http://localhost:8087/lock -d '{"password": "***"}' --header "Content-Type: application/json"` <----- This works
5. Wait some time (my loop runs every 3 hours and ALWAYS fails on the 2nd loop through)
6. Run `curl http://localhost:8087/unlock -d '{"password": "***"}' --header "Content-Type: application/json"` <----- This works
7. Run `curl http://localhost:8087/sync -d '{}' --header "Content-Type: application/json"` <----- This returns `Internal Server Error`
8. `curl http://localhost:8087/unlock -d '{"password": "***"}' --header "Content-Type: application/json"` <----- Suddenly, this now also returns `Internal Server Error`

### Expected Result

Expected sync command to return normal success value: 

```sh
{"success":true,"data":{"noColor":false,"object":"message","title":"Syncing complete.","message":null}}
```

And also not to break the unlock command. 

### Actual Result

Status code: 500 Internal Server Error

From `stderr` after running the sync command:

```
  TypeError: Cannot read properties of null (reading 'toString')
      at SyncCommand.<anonymous> (/snapshot/clients/apps/cli/build/bw.js:48171:62)
      at Generator.throw (<anonymous>)
      at rejected (/snapshot/clients/apps/cli/build/bw.js:48146:65)
```

From `stderr` after running the unlock command after the system-breaking sync command:

```
  TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
      at new NodeError (node:internal/errors:388:5)
      at Function.from (node:buffer:326:9)
      at NodeCryptoFunctionService.toNodeBuffer (/snapshot/clients/apps/cli/build/bw.js:41828:23)
      at NodeCryptoFunctionService.toNodeValue (/snapshot/clients/apps/cli/build/bw.js:41823:30)
      at NodeCryptoFunctionService.pbkdf2 (/snapshot/clients/apps/cli/build/bw.js:41608:31)
      at KeyGenerationService.<anonymous> (/snapshot/clients/apps/cli/build/bw.js:19662:56)
      at Generator.next (<anonymous>)
      at /snapshot/clients/apps/cli/build/bw.js:19622:71
      at new Promise (<anonymous>)
      at /snapshot/clients/apps/cli/build/bw.js:19618:12
```

### Additional Context

I've discovered that logging out and logging back in **does not** fix this issue. 

However, killing the `bw serve` process **successfully fixes** the issue. 

i.e.

```sh
kill -9 $(pgrep -f "bw serve")
```

### Operating System

Linux

### Operating System Version

Debian GNU/Linux trixie/sid

### Shell

Bash

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by mitrovda** [comment]
Same issue here, but on version 2024.4.0.

**Comment by Misterbabou** [comment]
Same issue  with version 2024.4.1 on Ubuntu 20.04.6 LTS using those commands on self host server.

- Connect using apikey
- `bw sync` (ok)
- wait for multiple hours
- `bw sync` : error
```
/snapshot/clients/apps/cli/build/bw.js:48171
                return Response.error("Syncing failed: " + e.toString());
                                                             ^

TypeError: Cannot read properties of null (reading 'toString')
    at SyncCommand.<anonymous> (/snapshot/clients/apps/cli/build/bw.js:48171:62)
    at Generator.throw (<anonymous>)
    at rejected (/snapshot/clients/apps/cli/build/bw.js:48146:65)

Node.js v18.5.0
```
- bw unlock --raw `You are not logged in.`
- in "~/.config/Bitwarden CLI/data.json"  
```
  "authenticatedAccounts": [],
```

It seems that the failed sync disconnect the user

**Comment by Vringe** [comment]
This also affects me for a while now. Is there any progress on this, @cbbit ?

**Comment by closebot-bw** [comment]
⚠️ **Stale Issue Notice**

This issue has been automatically marked as stale due to inactivity. It will be closed in **2 weeks** (October 15, 2025) if no further activity occurs.

If this issue is still relevant and you would like to keep it open, please:
- Comment on this issue to show continued interest
- Provide any additional information or updates
- Confirm that the issue still exists in the latest version

Thank you for your contribution to this project! 🙏

**Comment by eebette** [comment]
This issue is continuing to affect me and I don't think that it should be closed.
