### ISSUE TITLE
Syncing failed

### ISSUE THREAD

**Issue by mwisnicki** [bitwarden/clients#9341]
### Steps To Reproduce

1. Click `File` \ `Sync vault`

### Expected Result

Syncs.

### Actual Result

Says `syncing failed`:

<img width="371" alt="image" src="https://github.com/bitwarden/clients/assets/96032/747a11fc-7183-45a6-a078-b378c079eabf">

### Additional Context

It looks like desktop client hasn't synced in weeks yet never reported a problem which is a bug in its own right.

### Operating System

macOS

### Operating System Version

14.4.1

### Installation method

Mac App Store

### Build Version

2024.5.0 (24604)

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by andradewall** [comment]
Same here, using Bitwarden AppImage version...

**Comment by ten3systems** [comment]
Same in Ubuntu latest version after trying:

1. log out from bw app and browser ext
2. uninstall bw app from ubuntu store and reinstall (appimage ver I presume?)
3. changing timezone from EDT (NewYork) to EDT (Toronto) but i note they are both UTC-4

**Comment by LeyCod** [comment]
Same here using Bitwarden on Linux Ubuntu 22.04.4 LTS

**Comment by 45triX** [comment]
I'm having the same issue although I use self-hosted vaultwarden and using the bitwarden desktop client on windows 10. Its not a network issue as I can access my vault via the web, also the bitwarden android app syncs fine I'm not really sure what the issue is here.

**Comment by andradewall** [comment]
Just downloaded again the AppImage version and it works fine (login and sync) on my MX Linux 23.3

**Comment by FulopJozsi** [comment]
# Same here for snap and AppImage version. Reinstall not working.
Browser plugin works fine (syncs correctly) while desktop app cannot sync (logins properly, but fails to sync).

## I have an error:
if i run it from cli
```
13:12:50.355 › Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled.
Error occurred in handler for 'storageService': TypeError: Use `delete()` to clear values
    at ElectronStore.set (/tmp/.mount_BitwarInT960/resources/app.asar/main.js:9028:19)
    at ElectronStorageService.save (/tmp/.mount_BitwarInT960/resources/app.asar/main.js:93301:20)
    at /tmp/.mount_BitwarInT960/resources/app.asar/main.js:93280:33
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:78397)
    at WebContents.emit (node:events:514:28)
```

/tmp/.mount_BitwarInT960/resources/app.asar is a file if that matters.

**Comment by sixerstyle** [comment]
Hello, why no1 fix this error, last Version thats works is 2024.3.0

**Comment by MobillsInMobild** [comment]
I have to say that I had a very similar problem that plagued me for a really quite long time. 😶‍🌫️😶‍🌫️

However, after I **updated the version for my self-hosted server**, I no longer have problems with sync failures - and I did some experiments and found that the old client version was also able to sync successfully. 

So I'm inclined to think that the new version of the client is not as compatible with the old version of the server.

**Comment by mitoop** [comment]
Same here for macOS 14.5. The iOS APP works well. @sixerstyle  2024.3.0 works well in my computer 👍

**Comment by mitoop** [comment]
[Desktop v2024.7.1](https://github.com/bitwarden/clients/releases/tag/desktop-v2024.7.1) 2024.7.1 Works well

**Comment by saalmi098** [comment]
> [Desktop v2024.7.1](https://github.com/bitwarden/clients/releases/tag/desktop-v2024.7.1) 2024.7.1 Works well

v2024.7.1 fixed the issue for me as well
