### ISSUE TITLE
Uncaught Exception: SyntaxError: Expected double-quoted property name in JSON at position 155648 (line 4066 column 111)

### ISSUE THREAD

**Issue by janmyszkier** [bitwarden/clients#9492]
### Steps To Reproduce

1. Go to terminal
2. run bitwarden via cli:
```
$ bitwarden
```

### Expected Result

Bitwarden opens the application window

### Actual Result

```
$ bitwarden
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Expected double-quoted property name in JSON at position 155648 (line 4066 column 111)
    at JSON.parse (<anonymous>)
    at Conf._deserialize (/snap/bitwarden/110/resources/app.asar/main.js:8930:43)
    at get store [as store] (/snap/bitwarden/110/resources/app.asar/main.js:9141:43)
    at new Conf (/snap/bitwarden/110/resources/app.asar/main.js:8994:32)
    at new ElectronStore (/snap/bitwarden/110/resources/app.asar/main.js:13369:3)
    at new ElectronStorageService (/snap/bitwarden/110/resources/app.asar/main.js:92303:22)
    at new Main (/snap/bitwarden/110/resources/app.asar/main.js:92930:31)
    at 64164 (/snap/bitwarden/110/resources/app.asar/main.js:75981:18)
    at __webpack_require__ (/snap/bitwarden/110/resources/app.asar/main.js:96904:42)
    at /snap/bitwarden/110/resources/app.asar/main.js:96960:37

(bitwarden:17637): Gtk-WARNING **: 09:23:03.597: Theme parsing error: gtk.css:1422:23: 'font-feature-settings' is not a valid property name

(bitwarden:17637): Gtk-WARNING **: 09:23:03.599: Theme parsing error: gtk.css:3308:25: 'font-feature-settings' is not a valid property name

(bitwarden:17637): Gtk-WARNING **: 09:23:03.599: Theme parsing error: gtk.css:3770:23: 'font-feature-settings' is not a valid property name

(bitwarden:17637): Gtk-WARNING **: 09:23:03.663: Theme parsing error: gtk.css:1422:23: 'font-feature-settings' is not a valid property name

(bitwarden:17637): Gtk-WARNING **: 09:23:03.665: Theme parsing error: gtk.css:3308:25: 'font-feature-settings' is not a valid property name

(bitwarden:17637): Gtk-WARNING **: 09:23:03.665: Theme parsing error: gtk.css:3770:23: 'font-feature-settings' is not a valid property name
libGL error: MESA-LOADER: failed to open radeonsi (search paths /snap/bitwarden/110/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast (search paths /snap/bitwarden/110/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: swrast
[17738:0604/092303.698359:ERROR:angle_platform_impl.cc(44)] Display.cpp:1052 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1052 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[17738:0604/092303.698485:ERROR:gl_display.cc(515)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[17738:0604/092303.698527:ERROR:gl_display.cc(786)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[17738:0604/092303.699140:ERROR:angle_platform_impl.cc(44)] Display.cpp:1052 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1052 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[17738:0604/092303.699181:ERROR:gl_display.cc(515)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[17738:0604/092303.699220:ERROR:gl_display.cc(786)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[17738:0604/092303.699255:ERROR:gl_display.cc(820)] Initialization of all EGL display types failed.
[17738:0604/092303.699292:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[17738:0604/092303.702090:ERROR:angle_platform_impl.cc(44)] Display.cpp:1052 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1052 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[17738:0604/092303.702144:ERROR:gl_display.cc(515)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[17738:0604/092303.702180:ERROR:gl_display.cc(786)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[17738:0604/092303.702774:ERROR:angle_platform_impl.cc(44)] Display.cpp:1052 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1052 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[17738:0604/092303.702815:ERROR:gl_display.cc(515)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[17738:0604/092303.702848:ERROR:gl_display.cc(786)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[17738:0604/092303.702881:ERROR:gl_display.cc(820)] Initialization of all EGL display types failed.
[17738:0604/092303.702914:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[17738:0604/092303.704008:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
MESA-LOADER: failed to open radeonsi (search paths /snap/bitwarden/110/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
failed to load driver: radeonsi
MESA-LOADER: failed to open kms_swrast (search paths /snap/bitwarden/110/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast (search paths /snap/bitwarden/110/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
failed to load swrast driver
```

### Operating System

Linux

### Operating System Version

Ubuntu LTS 22.04

### Installation method

Snap

### Build Version

2024.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by janmyszkier** [comment]
:+1: will try to build this locally and track it down to something meaningful.

**Comment by bctechnzl** [comment]
same error for a version installed from Snap with Ubuntu 22:04
$ bitwarden
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Expected double-quoted property name in JSON at position 3678208 (line 95139 column 18)
    at JSON.parse (<anonymous>)
    at Conf._deserialize (/snap/bitwarden/113/resources/app.asar/main.js:8930:43)
    at get store (/snap/bitwarden/113/resources/app.asar/main.js:9141:43)
    at new Conf (/snap/bitwarden/113/resources/app.asar/main.js:8994:32)
    at new ElectronStore (/snap/bitwarden/113/resources/app.asar/main.js:13369:3)
    at new ElectronStorageService (/snap/bitwarden/113/resources/app.asar/main.js:93271:22)
    at new Main (/snap/bitwarden/113/resources/app.asar/main.js:93895:31)
    at 64164 (/snap/bitwarden/113/resources/app.asar/main.js:75981:18)
    at __webpack_require__ (/snap/bitwarden/113/resources/app.asar/main.js:97880:42)
    at /snap/bitwarden/113/resources/app.asar/main.js:97936:37
Gtk-Message: 13:54:53.062: Failed to load module "xapp-gtk3-module"

(bitwarden:15571): Gtk-WARNING **: 13:54:53.139: Theme parsing error: gtk.css:1413:23: 'font-feature-settings' is not a valid property name

(bitwarden:15571): Gtk-WARNING **: 13:54:53.141: Theme parsing error: gtk.css:3286:25: 'font-feature-settings' is not a valid property name

(bitwarden:15571): Gtk-WARNING **: 13:54:53.141: Theme parsing error: gtk.css:3748:23: 'font-feature-settings' is not a valid property name

(bitwarden:15571): Gtk-WARNING **: 13:54:53.778: Theme parsing error: gtk-dark.css:1413:23: 'font-feature-settings' is not a valid property name

(bitwarden:15571): Gtk-WARNING **: 13:54:53.781: Theme parsing error: gtk-dark.css:3286:25: 'font-feature-settings' is not a valid property name

(bitwarden:15571): Gtk-WARNING **: 13:54:53.781: Theme parsing error: gtk-dark.css:3748:23: 'font-feature-settings' is not a valid property name

**Comment by CastleBravoMegatons** [comment]
Same issue. I am running Pop!_OS 22.04 LTS. 

CLI Output returns:

`A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Expected double-quoted property name in JSON at position 20480 (line 508 column 7)
    at JSON.parse (<anonymous>)
    at Conf._deserialize (/opt/Bitwarden/resources/app.asar/main.js:8930:43)
    at get store (/opt/Bitwarden/resources/app.asar/main.js:9141:43)
    at new Conf (/opt/Bitwarden/resources/app.asar/main.js:8994:32)
    at new ElectronStore (/opt/Bitwarden/resources/app.asar/main.js:13369:3)
    at new ElectronStorageService (/opt/Bitwarden/resources/app.asar/main.js:93271:22)
    at new Main (/opt/Bitwarden/resources/app.asar/main.js:93895:31)
    at 64164 (/opt/Bitwarden/resources/app.asar/main.js:75981:18)
    at __webpack_require__ (/opt/Bitwarden/resources/app.asar/main.js:97880:42)
    at /opt/Bitwarden/resources/app.asar/main.js:97936:37
`
Window never opens.
GNOME Version 42.9
Windowing System is X11
My Processor is the 11th Gen Intel® Core™ i7-11800H @ 2.30GHz and my GPU is the Nvidia RTX 3050 Mobile

Issue occurred for me yesterday suddenly. A reinstall was not successful. I noticed that a lot of bitwarden processes start. I did notice that right before this, the logs (~/.config/Bitwarden/app.log) returned the following:

`[2024-07-22 14:39:48.545] [info]  TypeError: Cannot read properties of undefined (reading 'deleteBiometricKey')
    at BiometricsService.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:47363:55)
    at Generator.next (<anonymous>)
    at /opt/Bitwarden/resources/app.asar/main.js:47271:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/opt/Bitwarden/resources/app.asar/main.js:47267:12)
    at BiometricsService.deleteBiometricKey (/opt/Bitwarden/resources/app.asar/main.js:47361:16)
    at DesktopCredentialStorageListener.<anonymous> (/opt/Bitwarden/resources/app.asar/main.js:47569:45)
    at Generator.next (<anonymous>)
    at /opt/Bitwarden/resources/app.asar/main.js:47446:71
    at new Promise (<anonymous>)
`
Just found another useful error in ~/.config/Bitwarden/logs/renderer.log

`2024-07-22 15:39:44.124] [error] Unable to fetch ServerConfig: Error invoking remote method 'storageService': SyntaxError: Expected double-quoted property name in JSON at position 20480
`

I am not a Javascript programmer (I stick to Django and Flutter), but maybe we wrote some bad data to a file during a narrow set of circumstances? It's either that or I go blame Pop!_OS again.

**Comment by shervinsahba** [comment]
Perhaps similar issue. This started maybe a week or two ago, after what I assume were on my end some routine Arch Linux updates. It persists even when I downgrade bitwarden to a version that uses earlier versions of electron, like 2024.1.0. I'm unfamiliar with how to diagnose this further at this time...

6.10.0-arch1-2
Gnome 46
bitwarden 2024.6.4-1 (installed from Arch repos)


```
└─❯ bitwarden-desktop 
App threw an error during load
SyntaxError: Expected double-quoted property name in JSON at position 532480 (line 13258 column 55)
    at JSON.parse (<anonymous>)
    at Conf._deserialize (/usr/lib/bitwarden/app.asar/main.js:8930:43)
    at get store (/usr/lib/bitwarden/app.asar/main.js:9141:43)
    at new Conf (/usr/lib/bitwarden/app.asar/main.js:8994:32)
    at new ElectronStore (/usr/lib/bitwarden/app.asar/main.js:13369:3)
    at new ElectronStorageService (/usr/lib/bitwarden/app.asar/main.js:93271:22)
    at new Main (/usr/lib/bitwarden/app.asar/main.js:93895:31)
    at 64164 (/usr/lib/bitwarden/app.asar/main.js:75981:18)
    at __webpack_require__ (/usr/lib/bitwarden/app.asar/main.js:97880:42)
    at /usr/lib/bitwarden/app.asar/main.js:97936:37
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Expected double-quoted property name in JSON at position 532480 (line 13258 column 55)
    at JSON.parse (<anonymous>)
    at Conf._deserialize (/usr/lib/bitwarden/app.asar/main.js:8930:43)
    at get store (/usr/lib/bitwarden/app.asar/main.js:9141:43)
    at new Conf (/usr/lib/bitwarden/app.asar/main.js:8994:32)
    at new ElectronStore (/usr/lib/bitwarden/app.asar/main.js:13369:3)
    at new ElectronStorageService (/usr/lib/bitwarden/app.asar/main.js:93271:22)
    at new Main (/usr/lib/bitwarden/app.asar/main.js:93895:31)
    at 64164 (/usr/lib/bitwarden/app.asar/main.js:75981:18)
    at __webpack_require__ (/usr/lib/bitwarden/app.asar/main.js:97880:42)
    at /usr/lib/bitwarden/app.asar/main.js:97936:37
```

**Comment by janmyszkier** [comment]
@daniellbw i was hoping to build the desktop client to investigate this but it keeps failing the same way for months now. Just found the https://github.com/bitwarden/clients/issues/11611
which mentions my exact issue
```
[Main]       TS2307: Cannot find module '@bitwarden/sdk-internal' or its corresponding type declarations.
``` 
meaning I won't be able to build the app the way it currently works and debug this and I should just move away?

https://contributing.bitwarden.com/getting-started/clients/desktop/ doesn't mention what to do when `@bitwarden/sdk-internal` is missing and this seems to be OOTB experience.

**Comment by shingalated** [comment]
I'm having the same issue on NixOS.

```
App threw an error during load
SyntaxError: Expected double-quoted property name in JSON at position 36864 (line 911 column 1)
    at JSON.parse (<anonymous>)
    at Conf._deserialize (/nix/store/dlmvfvbyhsphylmclc6cvi30aqclxrqs-bitwarden-desktop-2024.8.1/opt/Bitwarden/resources/app.asar/main.js:8930:43)
    at get store (/nix/store/dlmvfvbyhsphylmclc6cvi30aqclxrqs-bitwarden-desktop-2024.8.1/opt/Bitwarden/resources/app.asar/main.js:9141:43)
    at new Conf (/nix/store/dlmvfvbyhsphylmclc6cvi30aqclxrqs-bitwarden-desktop-2024.8.1/opt/Bitwarden/resources/app.asar/main.js:8994:32)
    at new ElectronStore (/nix/store/dlmvfvbyhsphylmclc6cvi30aqclxrqs-bitwarden-desktop-2024.8.1/opt/Bitwarden/resources/app.asar/main.js:13371:3)
    at new ElectronStorageService (/nix/store/dlmvfvbyhsphylmclc6cvi30aqclxrqs-bitwarden-desktop-2024.8.1/opt/Bitwarden/resources/app.asar/main.js:87226:22)
    at new Main (/nix/store/dlmvfvbyhsphylmclc6cvi30aqclxrqs-bitwarden-desktop-2024.8.1/opt/Bitwarden/resources/app.asar/main.js:87834:31)
    at 72509 (/nix/store/dlmvfvbyhsphylmclc6cvi30aqclxrqs-bitwarden-desktop-2024.8.1/opt/Bitwarden/resources/app.asar/main.js:75983:18)
    at __webpack_require__ (/nix/store/dlmvfvbyhsphylmclc6cvi30aqclxrqs-bitwarden-desktop-2024.8.1/opt/Bitwarden/resources/app.asar/main.js:91975:42)
    at /nix/store/dlmvfvbyhsphylmclc6cvi30aqclxrqs-bitwarden-desktop-2024.8.1/opt/Bitwarden/resources/app.asar/main.js:92031:37
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Expected double-quoted property name in JSON at position 36864 (line 911 column 1)
    at JSON.parse (<anonymous>)
    at Conf._deserialize (/nix/store/dlmvfvbyhsphylmclc6cvi30aqclxrqs-bitwarden-desktop-2024.8.1/opt/Bitwarden/resources/app.asar/main.js:8930:43)
    at get store (/nix/store/dlmvfvbyhsphylmclc6cvi30aqclxrqs-bitwarden-desktop-2024.8.1/opt/Bitwarden/resources/app.asar/main.js:9141:43)
    at new Conf (/nix/store/dlmvfvbyhsphylmclc6cvi30aqclxrqs-bitwarden-desktop-2024.8.1/opt/Bitwarden/resources/app.asar/main.js:8994:32)
    at new ElectronStore (/nix/store/dlmvfvbyhsphylmclc6cvi30aqclxrqs-bitwarden-desktop-2024.8.1/opt/Bitwarden/resources/app.asar/main.js:13371:3)
    at new ElectronStorageService (/nix/store/dlmvfvbyhsphylmclc6cvi30aqclxrqs-bitwarden-desktop-2024.8.1/opt/Bitwarden/resources/app.asar/main.js:87226:22)
    at new Main (/nix/store/dlmvfvbyhsphylmclc6cvi30aqclxrqs-bitwarden-desktop-2024.8.1/opt/Bitwarden/resources/app.asar/main.js:87834:31)
    at 72509 (/nix/store/dlmvfvbyhsphylmclc6cvi30aqclxrqs-bitwarden-desktop-2024.8.1/opt/Bitwarden/resources/app.asar/main.js:75983:18)
    at __webpack_require__ (/nix/store/dlmvfvbyhsphylmclc6cvi30aqclxrqs-bitwarden-desktop-2024.8.1/opt/Bitwarden/resources/app.asar/main.js:91975:42)
    at /nix/store/dlmvfvbyhsphylmclc6cvi30aqclxrqs-bitwarden-desktop-2024.8.1/opt/Bitwarden/resources/app.asar/main.js:92031:37
```

**Comment by sebastian-hans-bbv** [comment]
Similar issue here. Bitwarden installed via Snap on Ubuntu 22.04.5 LTS. Running `bitwarden` on the command line yields this:

```
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Expected double-quoted property name in JSON at position 77824 (line 2201 column 2)
    at JSON.parse (<anonymous>)
    at Conf._deserialize (/snap/bitwarden/138/resources/app.asar/main.js:10101:43)
    at get store (/snap/bitwarden/138/resources/app.asar/main.js:10312:43)
    at new Conf (/snap/bitwarden/138/resources/app.asar/main.js:10165:32)
    at new ElectronStore (/snap/bitwarden/138/resources/app.asar/main.js:15062:3)
    at new ElectronStorageService (/snap/bitwarden/138/resources/app.asar/main.js:90013:22)
    at new Main (/snap/bitwarden/138/resources/app.asar/main.js:90746:31)
    at 83243 (/snap/bitwarden/138/resources/app.asar/main.js:71887:18)
    at __webpack_require__ (/snap/bitwarden/138/resources/app.asar/main.js:96438:42)
    at /snap/bitwarden/138/resources/app.asar/main.js:96602:37

(bitwarden-app:48847): Gtk-WARNING **: 09:18:41.351: Theme parsing error: gtk.css:1413:23: 'font-feature-settings' is not a valid property name

(bitwarden-app:48847): Gtk-WARNING **: 09:18:41.353: Theme parsing error: gtk.css:3286:25: 'font-feature-settings' is not a valid property name

(bitwarden-app:48847): Gtk-WARNING **: 09:18:41.354: Theme parsing error: gtk.css:3748:23: 'font-feature-settings' is not a valid property name
libGL error: MESA-LOADER: failed to open iris (search paths /snap/bitwarden/138/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast (search paths /snap/bitwarden/138/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: swrast
[48921:0502/091841.422731:ERROR:angle_platform_impl.cc(44)] Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[48921:0502/091841.422950:ERROR:gl_display.cc(493)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[48921:0502/091841.423001:ERROR:gl_display.cc(762)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[48921:0502/091841.423774:ERROR:angle_platform_impl.cc(44)] Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[48921:0502/091841.423878:ERROR:gl_display.cc(493)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[48921:0502/091841.423936:ERROR:gl_display.cc(762)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[48921:0502/091841.424016:ERROR:gl_display.cc(796)] Initialization of all EGL display types failed.
[48921:0502/091841.424059:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[48921:0502/091841.426002:ERROR:angle_platform_impl.cc(44)] Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[48921:0502/091841.426055:ERROR:gl_display.cc(493)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[48921:0502/091841.426071:ERROR:gl_display.cc(762)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[48921:0502/091841.426761:ERROR:angle_platform_impl.cc(44)] Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[48921:0502/091841.426780:ERROR:gl_display.cc(493)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[48921:0502/091841.426794:ERROR:gl_display.cc(762)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[48921:0502/091841.426809:ERROR:gl_display.cc(796)] Initialization of all EGL display types failed.
[48921:0502/091841.426823:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[48921:0502/091841.427744:ERROR:viz_main_impl.cc(185)] Exiting GPU process due to errors during initialization

(bitwarden-app:48847): Gtk-WARNING **: 09:18:41.438: Theme parsing error: gtk-dark.css:1413:23: 'font-feature-settings' is not a valid property name

(bitwarden-app:48847): Gtk-WARNING **: 09:18:41.440: Theme parsing error: gtk-dark.css:3286:25: 'font-feature-settings' is not a valid property name

(bitwarden-app:48847): Gtk-WARNING **: 09:18:41.441: Theme parsing error: gtk-dark.css:3748:23: 'font-feature-settings' is not a valid property name
libGL error: MESA-LOADER: failed to open iris (search paths /snap/bitwarden/138/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast (search paths /snap/bitwarden/138/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: swrast
[48950:0502/091841.491301:ERROR:angle_platform_impl.cc(44)] Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[48950:0502/091841.491465:ERROR:gl_display.cc(493)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[48950:0502/091841.491484:ERROR:gl_display.cc(762)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[48950:0502/091841.492217:ERROR:angle_platform_impl.cc(44)] Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[48950:0502/091841.492452:ERROR:gl_display.cc(493)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[48950:0502/091841.492519:ERROR:gl_display.cc(762)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[48950:0502/091841.492666:ERROR:gl_display.cc(796)] Initialization of all EGL display types failed.
[48950:0502/091841.492770:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[48950:0502/091841.494664:ERROR:angle_platform_impl.cc(44)] Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[48950:0502/091841.494789:ERROR:gl_display.cc(493)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[48950:0502/091841.494805:ERROR:gl_display.cc(762)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[48950:0502/091841.495574:ERROR:angle_platform_impl.cc(44)] Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1056 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[48950:0502/091841.495596:ERROR:gl_display.cc(493)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[48950:0502/091841.495609:ERROR:gl_display.cc(762)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[48950:0502/091841.495623:ERROR:gl_display.cc(796)] Initialization of all EGL display types failed.
[48950:0502/091841.495638:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[48950:0502/091841.496586:ERROR:viz_main_impl.cc(185)] Exiting GPU process due to errors during initialization
MESA-LOADER: failed to open iris (search paths /snap/bitwarden/138/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
failed to load driver: iris
MESA-LOADER: failed to open kms_swrast (search paths /snap/bitwarden/138/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast (search paths /snap/bitwarden/138/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
failed to load swrast driver
```
