### ISSUE TITLE
Error starting bitwarden (.deb)

### ISSUE THREAD

**Issue by tct123** [bitwarden/clients#9999]
### Steps To Reproduce

Go to terminal and type: bitwarden

### Expected Result

Working GUI.

### Actual Result

```
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unterminated string in JSON at position 143360 (line 3683 column 77)
    at JSON.parse (<anonymous>)
    at Conf._deserialize (/opt/Bitwarden/resources/app.asar/main.js:8930:43)
    at get store (/opt/Bitwarden/resources/app.asar/main.js:9141:43)
    at new Conf (/opt/Bitwarden/resources/app.asar/main.js:8994:32)
    at new ElectronStore (/opt/Bitwarden/resources/app.asar/main.js:13369:3)
    at new ElectronStorageService (/opt/Bitwarden/resources/app.asar/main.js:93271:22)
    at new Main (/opt/Bitwarden/resources/app.asar/main.js:93895:31)
    at 64164 (/opt/Bitwarden/resources/app.asar/main.js:75981:18)
    at __webpack_require__ (/opt/Bitwarden/resources/app.asar/main.js:97880:42)
    at /opt/Bitwarden/resources/app.asar/main.js:97936:37
```

### Operating System

Linux

### Operating System Version

Kali 24-05-30

### Installation method

Other

### Build Version

2024.6.4

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
